// Code generated by ent, DO NOT EDIT.

package domaincheckresult

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldLTE(FieldID, id))
}

// CheckID applies equality check predicate on the "check_id" field. It's identical to CheckIDEQ.
func CheckID(v uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldEQ(FieldCheckID, v))
}

// ExpiryDate applies equality check predicate on the "expiry_date" field. It's identical to ExpiryDateEQ.
func ExpiryDate(v time.Time) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldEQ(FieldExpiryDate, v))
}

// Registrar applies equality check predicate on the "registrar" field. It's identical to RegistrarEQ.
func Registrar(v string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldEQ(FieldRegistrar, v))
}

// DaysRemaining applies equality check predicate on the "days_remaining" field. It's identical to DaysRemainingEQ.
func DaysRemaining(v int) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldEQ(FieldDaysRemaining, v))
}

// CheckIDEQ applies the EQ predicate on the "check_id" field.
func CheckIDEQ(v uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldEQ(FieldCheckID, v))
}

// CheckIDNEQ applies the NEQ predicate on the "check_id" field.
func CheckIDNEQ(v uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldNEQ(FieldCheckID, v))
}

// CheckIDIn applies the In predicate on the "check_id" field.
func CheckIDIn(vs ...uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldIn(FieldCheckID, vs...))
}

// CheckIDNotIn applies the NotIn predicate on the "check_id" field.
func CheckIDNotIn(vs ...uuid.UUID) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldNotIn(FieldCheckID, vs...))
}

// ExpiryDateEQ applies the EQ predicate on the "expiry_date" field.
func ExpiryDateEQ(v time.Time) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldEQ(FieldExpiryDate, v))
}

// ExpiryDateNEQ applies the NEQ predicate on the "expiry_date" field.
func ExpiryDateNEQ(v time.Time) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldNEQ(FieldExpiryDate, v))
}

// ExpiryDateIn applies the In predicate on the "expiry_date" field.
func ExpiryDateIn(vs ...time.Time) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldIn(FieldExpiryDate, vs...))
}

// ExpiryDateNotIn applies the NotIn predicate on the "expiry_date" field.
func ExpiryDateNotIn(vs ...time.Time) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldNotIn(FieldExpiryDate, vs...))
}

// ExpiryDateGT applies the GT predicate on the "expiry_date" field.
func ExpiryDateGT(v time.Time) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldGT(FieldExpiryDate, v))
}

// ExpiryDateGTE applies the GTE predicate on the "expiry_date" field.
func ExpiryDateGTE(v time.Time) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldGTE(FieldExpiryDate, v))
}

// ExpiryDateLT applies the LT predicate on the "expiry_date" field.
func ExpiryDateLT(v time.Time) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldLT(FieldExpiryDate, v))
}

// ExpiryDateLTE applies the LTE predicate on the "expiry_date" field.
func ExpiryDateLTE(v time.Time) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldLTE(FieldExpiryDate, v))
}

// RegistrarEQ applies the EQ predicate on the "registrar" field.
func RegistrarEQ(v string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldEQ(FieldRegistrar, v))
}

// RegistrarNEQ applies the NEQ predicate on the "registrar" field.
func RegistrarNEQ(v string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldNEQ(FieldRegistrar, v))
}

// RegistrarIn applies the In predicate on the "registrar" field.
func RegistrarIn(vs ...string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldIn(FieldRegistrar, vs...))
}

// RegistrarNotIn applies the NotIn predicate on the "registrar" field.
func RegistrarNotIn(vs ...string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldNotIn(FieldRegistrar, vs...))
}

// RegistrarGT applies the GT predicate on the "registrar" field.
func RegistrarGT(v string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldGT(FieldRegistrar, v))
}

// RegistrarGTE applies the GTE predicate on the "registrar" field.
func RegistrarGTE(v string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldGTE(FieldRegistrar, v))
}

// RegistrarLT applies the LT predicate on the "registrar" field.
func RegistrarLT(v string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldLT(FieldRegistrar, v))
}

// RegistrarLTE applies the LTE predicate on the "registrar" field.
func RegistrarLTE(v string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldLTE(FieldRegistrar, v))
}

// RegistrarContains applies the Contains predicate on the "registrar" field.
func RegistrarContains(v string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldContains(FieldRegistrar, v))
}

// RegistrarHasPrefix applies the HasPrefix predicate on the "registrar" field.
func RegistrarHasPrefix(v string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldHasPrefix(FieldRegistrar, v))
}

// RegistrarHasSuffix applies the HasSuffix predicate on the "registrar" field.
func RegistrarHasSuffix(v string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldHasSuffix(FieldRegistrar, v))
}

// RegistrarEqualFold applies the EqualFold predicate on the "registrar" field.
func RegistrarEqualFold(v string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldEqualFold(FieldRegistrar, v))
}

// RegistrarContainsFold applies the ContainsFold predicate on the "registrar" field.
func RegistrarContainsFold(v string) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldContainsFold(FieldRegistrar, v))
}

// DaysRemainingEQ applies the EQ predicate on the "days_remaining" field.
func DaysRemainingEQ(v int) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldEQ(FieldDaysRemaining, v))
}

// DaysRemainingNEQ applies the NEQ predicate on the "days_remaining" field.
func DaysRemainingNEQ(v int) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldNEQ(FieldDaysRemaining, v))
}

// DaysRemainingIn applies the In predicate on the "days_remaining" field.
func DaysRemainingIn(vs ...int) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldIn(FieldDaysRemaining, vs...))
}

// DaysRemainingNotIn applies the NotIn predicate on the "days_remaining" field.
func DaysRemainingNotIn(vs ...int) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldNotIn(FieldDaysRemaining, vs...))
}

// DaysRemainingGT applies the GT predicate on the "days_remaining" field.
func DaysRemainingGT(v int) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldGT(FieldDaysRemaining, v))
}

// DaysRemainingGTE applies the GTE predicate on the "days_remaining" field.
func DaysRemainingGTE(v int) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldGTE(FieldDaysRemaining, v))
}

// DaysRemainingLT applies the LT predicate on the "days_remaining" field.
func DaysRemainingLT(v int) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldLT(FieldDaysRemaining, v))
}

// DaysRemainingLTE applies the LTE predicate on the "days_remaining" field.
func DaysRemainingLTE(v int) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.FieldLTE(FieldDaysRemaining, v))
}

// HasCheck applies the HasEdge predicate on the "check" edge.
func HasCheck() predicate.DomainCheckResult {
	return predicate.DomainCheckResult(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, CheckTable, CheckColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCheckWith applies the HasEdge predicate on the "check" edge with a given conditions (other predicates).
func HasCheckWith(preds ...predicate.MonitorCheck) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(func(s *sql.Selector) {
		step := newCheckStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DomainCheckResult) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DomainCheckResult) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DomainCheckResult) predicate.DomainCheckResult {
	return predicate.DomainCheckResult(sql.NotPredicates(p))
}
