// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/alert"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/alertevent"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitor"
)

// AlertEvent is the model entity for the AlertEvent schema.
type AlertEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// AlertID holds the value of the "alert_id" field.
	AlertID uuid.UUID `json:"alert_id,omitempty"`
	// MonitorID holds the value of the "monitor_id" field.
	MonitorID uuid.UUID `json:"monitor_id,omitempty"`
	// Status holds the value of the "status" field.
	Status alertevent.Status `json:"status,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AlertEventQuery when eager-loading is set.
	Edges        AlertEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AlertEventEdges holds the relations/edges for other nodes in the graph.
type AlertEventEdges struct {
	// Alert holds the value of the alert edge.
	Alert *Alert `json:"alert,omitempty"`
	// Monitor holds the value of the monitor edge.
	Monitor *Monitor `json:"monitor,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AlertOrErr returns the Alert value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertEventEdges) AlertOrErr() (*Alert, error) {
	if e.Alert != nil {
		return e.Alert, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: alert.Label}
	}
	return nil, &NotLoadedError{edge: "alert"}
}

// MonitorOrErr returns the Monitor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AlertEventEdges) MonitorOrErr() (*Monitor, error) {
	if e.Monitor != nil {
		return e.Monitor, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: monitor.Label}
	}
	return nil, &NotLoadedError{edge: "monitor"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AlertEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case alertevent.FieldStatus, alertevent.FieldMessage:
			values[i] = new(sql.NullString)
		case alertevent.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case alertevent.FieldID, alertevent.FieldAlertID, alertevent.FieldMonitorID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AlertEvent fields.
func (ae *AlertEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case alertevent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ae.ID = *value
			}
		case alertevent.FieldAlertID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field alert_id", values[i])
			} else if value != nil {
				ae.AlertID = *value
			}
		case alertevent.FieldMonitorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field monitor_id", values[i])
			} else if value != nil {
				ae.MonitorID = *value
			}
		case alertevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ae.Status = alertevent.Status(value.String)
			}
		case alertevent.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				ae.Message = value.String
			}
		case alertevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ae.CreatedAt = value.Time
			}
		default:
			ae.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AlertEvent.
// This includes values selected through modifiers, order, etc.
func (ae *AlertEvent) Value(name string) (ent.Value, error) {
	return ae.selectValues.Get(name)
}

// QueryAlert queries the "alert" edge of the AlertEvent entity.
func (ae *AlertEvent) QueryAlert() *AlertQuery {
	return NewAlertEventClient(ae.config).QueryAlert(ae)
}

// QueryMonitor queries the "monitor" edge of the AlertEvent entity.
func (ae *AlertEvent) QueryMonitor() *MonitorQuery {
	return NewAlertEventClient(ae.config).QueryMonitor(ae)
}

// Update returns a builder for updating this AlertEvent.
// Note that you need to call AlertEvent.Unwrap() before calling this method if this AlertEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (ae *AlertEvent) Update() *AlertEventUpdateOne {
	return NewAlertEventClient(ae.config).UpdateOne(ae)
}

// Unwrap unwraps the AlertEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ae *AlertEvent) Unwrap() *AlertEvent {
	_tx, ok := ae.config.driver.(*txDriver)
	if !ok {
		panic("ent: AlertEvent is not a transactional entity")
	}
	ae.config.driver = _tx.drv
	return ae
}

// String implements the fmt.Stringer.
func (ae *AlertEvent) String() string {
	var builder strings.Builder
	builder.WriteString("AlertEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ae.ID))
	builder.WriteString("alert_id=")
	builder.WriteString(fmt.Sprintf("%v", ae.AlertID))
	builder.WriteString(", ")
	builder.WriteString("monitor_id=")
	builder.WriteString(fmt.Sprintf("%v", ae.MonitorID))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", ae.Status))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(ae.Message)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ae.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AlertEvents is a parsable slice of AlertEvent.
type AlertEvents []*AlertEvent
