// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/alert"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/alertevent"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitor"
)

// AlertEventCreate is the builder for creating a AlertEvent entity.
type AlertEventCreate struct {
	config
	mutation *AlertEventMutation
	hooks    []Hook
}

// SetAlertID sets the "alert_id" field.
func (aec *AlertEventCreate) SetAlertID(u uuid.UUID) *AlertEventCreate {
	aec.mutation.SetAlertID(u)
	return aec
}

// SetMonitorID sets the "monitor_id" field.
func (aec *AlertEventCreate) SetMonitorID(u uuid.UUID) *AlertEventCreate {
	aec.mutation.SetMonitorID(u)
	return aec
}

// SetStatus sets the "status" field.
func (aec *AlertEventCreate) SetStatus(a alertevent.Status) *AlertEventCreate {
	aec.mutation.SetStatus(a)
	return aec
}

// SetMessage sets the "message" field.
func (aec *AlertEventCreate) SetMessage(s string) *AlertEventCreate {
	aec.mutation.SetMessage(s)
	return aec
}

// SetCreatedAt sets the "created_at" field.
func (aec *AlertEventCreate) SetCreatedAt(t time.Time) *AlertEventCreate {
	aec.mutation.SetCreatedAt(t)
	return aec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (aec *AlertEventCreate) SetNillableCreatedAt(t *time.Time) *AlertEventCreate {
	if t != nil {
		aec.SetCreatedAt(*t)
	}
	return aec
}

// SetID sets the "id" field.
func (aec *AlertEventCreate) SetID(u uuid.UUID) *AlertEventCreate {
	aec.mutation.SetID(u)
	return aec
}

// SetNillableID sets the "id" field if the given value is not nil.
func (aec *AlertEventCreate) SetNillableID(u *uuid.UUID) *AlertEventCreate {
	if u != nil {
		aec.SetID(*u)
	}
	return aec
}

// SetAlert sets the "alert" edge to the Alert entity.
func (aec *AlertEventCreate) SetAlert(a *Alert) *AlertEventCreate {
	return aec.SetAlertID(a.ID)
}

// SetMonitor sets the "monitor" edge to the Monitor entity.
func (aec *AlertEventCreate) SetMonitor(m *Monitor) *AlertEventCreate {
	return aec.SetMonitorID(m.ID)
}

// Mutation returns the AlertEventMutation object of the builder.
func (aec *AlertEventCreate) Mutation() *AlertEventMutation {
	return aec.mutation
}

// Save creates the AlertEvent in the database.
func (aec *AlertEventCreate) Save(ctx context.Context) (*AlertEvent, error) {
	aec.defaults()
	return withHooks(ctx, aec.sqlSave, aec.mutation, aec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (aec *AlertEventCreate) SaveX(ctx context.Context) *AlertEvent {
	v, err := aec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aec *AlertEventCreate) Exec(ctx context.Context) error {
	_, err := aec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aec *AlertEventCreate) ExecX(ctx context.Context) {
	if err := aec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aec *AlertEventCreate) defaults() {
	if _, ok := aec.mutation.CreatedAt(); !ok {
		v := alertevent.DefaultCreatedAt()
		aec.mutation.SetCreatedAt(v)
	}
	if _, ok := aec.mutation.ID(); !ok {
		v := alertevent.DefaultID()
		aec.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aec *AlertEventCreate) check() error {
	if _, ok := aec.mutation.AlertID(); !ok {
		return &ValidationError{Name: "alert_id", err: errors.New(`ent: missing required field "AlertEvent.alert_id"`)}
	}
	if _, ok := aec.mutation.MonitorID(); !ok {
		return &ValidationError{Name: "monitor_id", err: errors.New(`ent: missing required field "AlertEvent.monitor_id"`)}
	}
	if _, ok := aec.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AlertEvent.status"`)}
	}
	if v, ok := aec.mutation.Status(); ok {
		if err := alertevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AlertEvent.status": %w`, err)}
		}
	}
	if _, ok := aec.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "AlertEvent.message"`)}
	}
	if _, ok := aec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AlertEvent.created_at"`)}
	}
	if len(aec.mutation.AlertIDs()) == 0 {
		return &ValidationError{Name: "alert", err: errors.New(`ent: missing required edge "AlertEvent.alert"`)}
	}
	if len(aec.mutation.MonitorIDs()) == 0 {
		return &ValidationError{Name: "monitor", err: errors.New(`ent: missing required edge "AlertEvent.monitor"`)}
	}
	return nil
}

func (aec *AlertEventCreate) sqlSave(ctx context.Context) (*AlertEvent, error) {
	if err := aec.check(); err != nil {
		return nil, err
	}
	_node, _spec := aec.createSpec()
	if err := sqlgraph.CreateNode(ctx, aec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	aec.mutation.id = &_node.ID
	aec.mutation.done = true
	return _node, nil
}

func (aec *AlertEventCreate) createSpec() (*AlertEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &AlertEvent{config: aec.config}
		_spec = sqlgraph.NewCreateSpec(alertevent.Table, sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID))
	)
	if id, ok := aec.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := aec.mutation.Status(); ok {
		_spec.SetField(alertevent.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := aec.mutation.Message(); ok {
		_spec.SetField(alertevent.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := aec.mutation.CreatedAt(); ok {
		_spec.SetField(alertevent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := aec.mutation.AlertIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alertevent.AlertTable,
			Columns: []string{alertevent.AlertColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AlertID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := aec.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alertevent.MonitorTable,
			Columns: []string{alertevent.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.MonitorID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AlertEventCreateBulk is the builder for creating many AlertEvent entities in bulk.
type AlertEventCreateBulk struct {
	config
	err      error
	builders []*AlertEventCreate
}

// Save creates the AlertEvent entities in the database.
func (aecb *AlertEventCreateBulk) Save(ctx context.Context) ([]*AlertEvent, error) {
	if aecb.err != nil {
		return nil, aecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(aecb.builders))
	nodes := make([]*AlertEvent, len(aecb.builders))
	mutators := make([]Mutator, len(aecb.builders))
	for i := range aecb.builders {
		func(i int, root context.Context) {
			builder := aecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AlertEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, aecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, aecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, aecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (aecb *AlertEventCreateBulk) SaveX(ctx context.Context) []*AlertEvent {
	v, err := aecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (aecb *AlertEventCreateBulk) Exec(ctx context.Context) error {
	_, err := aecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aecb *AlertEventCreateBulk) ExecX(ctx context.Context) {
	if err := aecb.Exec(ctx); err != nil {
		panic(err)
	}
}
