// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/alert"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/alertevent"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitor"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/predicate"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/tenant"
)

// AlertUpdate is the builder for updating Alert entities.
type AlertUpdate struct {
	config
	hooks    []Hook
	mutation *AlertMutation
}

// Where appends a list predicates to the AlertUpdate builder.
func (au *AlertUpdate) Where(ps ...predicate.Alert) *AlertUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetTenantID sets the "tenant_id" field.
func (au *AlertUpdate) SetTenantID(u uuid.UUID) *AlertUpdate {
	au.mutation.SetTenantID(u)
	return au
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (au *AlertUpdate) SetNillableTenantID(u *uuid.UUID) *AlertUpdate {
	if u != nil {
		au.SetTenantID(*u)
	}
	return au
}

// SetMonitorID sets the "monitor_id" field.
func (au *AlertUpdate) SetMonitorID(u uuid.UUID) *AlertUpdate {
	au.mutation.SetMonitorID(u)
	return au
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (au *AlertUpdate) SetNillableMonitorID(u *uuid.UUID) *AlertUpdate {
	if u != nil {
		au.SetMonitorID(*u)
	}
	return au
}

// SetType sets the "type" field.
func (au *AlertUpdate) SetType(a alert.Type) *AlertUpdate {
	au.mutation.SetType(a)
	return au
}

// SetNillableType sets the "type" field if the given value is not nil.
func (au *AlertUpdate) SetNillableType(a *alert.Type) *AlertUpdate {
	if a != nil {
		au.SetType(*a)
	}
	return au
}

// SetThreshold sets the "threshold" field.
func (au *AlertUpdate) SetThreshold(i int) *AlertUpdate {
	au.mutation.ResetThreshold()
	au.mutation.SetThreshold(i)
	return au
}

// SetNillableThreshold sets the "threshold" field if the given value is not nil.
func (au *AlertUpdate) SetNillableThreshold(i *int) *AlertUpdate {
	if i != nil {
		au.SetThreshold(*i)
	}
	return au
}

// AddThreshold adds i to the "threshold" field.
func (au *AlertUpdate) AddThreshold(i int) *AlertUpdate {
	au.mutation.AddThreshold(i)
	return au
}

// SetCreatedAt sets the "created_at" field.
func (au *AlertUpdate) SetCreatedAt(t time.Time) *AlertUpdate {
	au.mutation.SetCreatedAt(t)
	return au
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (au *AlertUpdate) SetNillableCreatedAt(t *time.Time) *AlertUpdate {
	if t != nil {
		au.SetCreatedAt(*t)
	}
	return au
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (au *AlertUpdate) SetTenant(t *Tenant) *AlertUpdate {
	return au.SetTenantID(t.ID)
}

// SetMonitor sets the "monitor" edge to the Monitor entity.
func (au *AlertUpdate) SetMonitor(m *Monitor) *AlertUpdate {
	return au.SetMonitorID(m.ID)
}

// AddEventIDs adds the "events" edge to the AlertEvent entity by IDs.
func (au *AlertUpdate) AddEventIDs(ids ...uuid.UUID) *AlertUpdate {
	au.mutation.AddEventIDs(ids...)
	return au
}

// AddEvents adds the "events" edges to the AlertEvent entity.
func (au *AlertUpdate) AddEvents(a ...*AlertEvent) *AlertUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.AddEventIDs(ids...)
}

// Mutation returns the AlertMutation object of the builder.
func (au *AlertUpdate) Mutation() *AlertMutation {
	return au.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (au *AlertUpdate) ClearTenant() *AlertUpdate {
	au.mutation.ClearTenant()
	return au
}

// ClearMonitor clears the "monitor" edge to the Monitor entity.
func (au *AlertUpdate) ClearMonitor() *AlertUpdate {
	au.mutation.ClearMonitor()
	return au
}

// ClearEvents clears all "events" edges to the AlertEvent entity.
func (au *AlertUpdate) ClearEvents() *AlertUpdate {
	au.mutation.ClearEvents()
	return au
}

// RemoveEventIDs removes the "events" edge to AlertEvent entities by IDs.
func (au *AlertUpdate) RemoveEventIDs(ids ...uuid.UUID) *AlertUpdate {
	au.mutation.RemoveEventIDs(ids...)
	return au
}

// RemoveEvents removes "events" edges to AlertEvent entities.
func (au *AlertUpdate) RemoveEvents(a ...*AlertEvent) *AlertUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.RemoveEventIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AlertUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AlertUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AlertUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AlertUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AlertUpdate) check() error {
	if v, ok := au.mutation.GetType(); ok {
		if err := alert.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Alert.type": %w`, err)}
		}
	}
	if au.mutation.TenantCleared() && len(au.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Alert.tenant"`)
	}
	if au.mutation.MonitorCleared() && len(au.mutation.MonitorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Alert.monitor"`)
	}
	return nil
}

func (au *AlertUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(alert.Table, alert.Columns, sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.GetType(); ok {
		_spec.SetField(alert.FieldType, field.TypeEnum, value)
	}
	if value, ok := au.mutation.Threshold(); ok {
		_spec.SetField(alert.FieldThreshold, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedThreshold(); ok {
		_spec.AddField(alert.FieldThreshold, field.TypeInt, value)
	}
	if value, ok := au.mutation.CreatedAt(); ok {
		_spec.SetField(alert.FieldCreatedAt, field.TypeTime, value)
	}
	if au.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.TenantTable,
			Columns: []string{alert.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.TenantTable,
			Columns: []string{alert.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.MonitorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.MonitorTable,
			Columns: []string{alert.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.MonitorTable,
			Columns: []string{alert.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.EventsTable,
			Columns: []string{alert.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedEventsIDs(); len(nodes) > 0 && !au.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.EventsTable,
			Columns: []string{alert.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.EventsTable,
			Columns: []string{alert.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AlertUpdateOne is the builder for updating a single Alert entity.
type AlertUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlertMutation
}

// SetTenantID sets the "tenant_id" field.
func (auo *AlertUpdateOne) SetTenantID(u uuid.UUID) *AlertUpdateOne {
	auo.mutation.SetTenantID(u)
	return auo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (auo *AlertUpdateOne) SetNillableTenantID(u *uuid.UUID) *AlertUpdateOne {
	if u != nil {
		auo.SetTenantID(*u)
	}
	return auo
}

// SetMonitorID sets the "monitor_id" field.
func (auo *AlertUpdateOne) SetMonitorID(u uuid.UUID) *AlertUpdateOne {
	auo.mutation.SetMonitorID(u)
	return auo
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (auo *AlertUpdateOne) SetNillableMonitorID(u *uuid.UUID) *AlertUpdateOne {
	if u != nil {
		auo.SetMonitorID(*u)
	}
	return auo
}

// SetType sets the "type" field.
func (auo *AlertUpdateOne) SetType(a alert.Type) *AlertUpdateOne {
	auo.mutation.SetType(a)
	return auo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (auo *AlertUpdateOne) SetNillableType(a *alert.Type) *AlertUpdateOne {
	if a != nil {
		auo.SetType(*a)
	}
	return auo
}

// SetThreshold sets the "threshold" field.
func (auo *AlertUpdateOne) SetThreshold(i int) *AlertUpdateOne {
	auo.mutation.ResetThreshold()
	auo.mutation.SetThreshold(i)
	return auo
}

// SetNillableThreshold sets the "threshold" field if the given value is not nil.
func (auo *AlertUpdateOne) SetNillableThreshold(i *int) *AlertUpdateOne {
	if i != nil {
		auo.SetThreshold(*i)
	}
	return auo
}

// AddThreshold adds i to the "threshold" field.
func (auo *AlertUpdateOne) AddThreshold(i int) *AlertUpdateOne {
	auo.mutation.AddThreshold(i)
	return auo
}

// SetCreatedAt sets the "created_at" field.
func (auo *AlertUpdateOne) SetCreatedAt(t time.Time) *AlertUpdateOne {
	auo.mutation.SetCreatedAt(t)
	return auo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (auo *AlertUpdateOne) SetNillableCreatedAt(t *time.Time) *AlertUpdateOne {
	if t != nil {
		auo.SetCreatedAt(*t)
	}
	return auo
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (auo *AlertUpdateOne) SetTenant(t *Tenant) *AlertUpdateOne {
	return auo.SetTenantID(t.ID)
}

// SetMonitor sets the "monitor" edge to the Monitor entity.
func (auo *AlertUpdateOne) SetMonitor(m *Monitor) *AlertUpdateOne {
	return auo.SetMonitorID(m.ID)
}

// AddEventIDs adds the "events" edge to the AlertEvent entity by IDs.
func (auo *AlertUpdateOne) AddEventIDs(ids ...uuid.UUID) *AlertUpdateOne {
	auo.mutation.AddEventIDs(ids...)
	return auo
}

// AddEvents adds the "events" edges to the AlertEvent entity.
func (auo *AlertUpdateOne) AddEvents(a ...*AlertEvent) *AlertUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.AddEventIDs(ids...)
}

// Mutation returns the AlertMutation object of the builder.
func (auo *AlertUpdateOne) Mutation() *AlertMutation {
	return auo.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (auo *AlertUpdateOne) ClearTenant() *AlertUpdateOne {
	auo.mutation.ClearTenant()
	return auo
}

// ClearMonitor clears the "monitor" edge to the Monitor entity.
func (auo *AlertUpdateOne) ClearMonitor() *AlertUpdateOne {
	auo.mutation.ClearMonitor()
	return auo
}

// ClearEvents clears all "events" edges to the AlertEvent entity.
func (auo *AlertUpdateOne) ClearEvents() *AlertUpdateOne {
	auo.mutation.ClearEvents()
	return auo
}

// RemoveEventIDs removes the "events" edge to AlertEvent entities by IDs.
func (auo *AlertUpdateOne) RemoveEventIDs(ids ...uuid.UUID) *AlertUpdateOne {
	auo.mutation.RemoveEventIDs(ids...)
	return auo
}

// RemoveEvents removes "events" edges to AlertEvent entities.
func (auo *AlertUpdateOne) RemoveEvents(a ...*AlertEvent) *AlertUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.RemoveEventIDs(ids...)
}

// Where appends a list predicates to the AlertUpdate builder.
func (auo *AlertUpdateOne) Where(ps ...predicate.Alert) *AlertUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AlertUpdateOne) Select(field string, fields ...string) *AlertUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Alert entity.
func (auo *AlertUpdateOne) Save(ctx context.Context) (*Alert, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AlertUpdateOne) SaveX(ctx context.Context) *Alert {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AlertUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AlertUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AlertUpdateOne) check() error {
	if v, ok := auo.mutation.GetType(); ok {
		if err := alert.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Alert.type": %w`, err)}
		}
	}
	if auo.mutation.TenantCleared() && len(auo.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Alert.tenant"`)
	}
	if auo.mutation.MonitorCleared() && len(auo.mutation.MonitorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Alert.monitor"`)
	}
	return nil
}

func (auo *AlertUpdateOne) sqlSave(ctx context.Context) (_node *Alert, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(alert.Table, alert.Columns, sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Alert.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, alert.FieldID)
		for _, f := range fields {
			if !alert.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != alert.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.GetType(); ok {
		_spec.SetField(alert.FieldType, field.TypeEnum, value)
	}
	if value, ok := auo.mutation.Threshold(); ok {
		_spec.SetField(alert.FieldThreshold, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedThreshold(); ok {
		_spec.AddField(alert.FieldThreshold, field.TypeInt, value)
	}
	if value, ok := auo.mutation.CreatedAt(); ok {
		_spec.SetField(alert.FieldCreatedAt, field.TypeTime, value)
	}
	if auo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.TenantTable,
			Columns: []string{alert.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.TenantTable,
			Columns: []string{alert.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.MonitorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.MonitorTable,
			Columns: []string{alert.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   alert.MonitorTable,
			Columns: []string{alert.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.EventsTable,
			Columns: []string{alert.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedEventsIDs(); len(nodes) > 0 && !auo.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.EventsTable,
			Columns: []string{alert.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   alert.EventsTable,
			Columns: []string{alert.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Alert{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{alert.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
