// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/dnscheckresult"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitorcheck"
)

// DNSCheckResultCreate is the builder for creating a DNSCheckResult entity.
type DNSCheckResultCreate struct {
	config
	mutation *DNSCheckResultMutation
	hooks    []Hook
}

// SetCheckID sets the "check_id" field.
func (dcrc *DNSCheckResultCreate) SetCheckID(u uuid.UUID) *DNSCheckResultCreate {
	dcrc.mutation.SetCheckID(u)
	return dcrc
}

// SetHasARecord sets the "has_a_record" field.
func (dcrc *DNSCheckResultCreate) SetHasARecord(b bool) *DNSCheckResultCreate {
	dcrc.mutation.SetHasARecord(b)
	return dcrc
}

// SetHasAaaaRecord sets the "has_aaaa_record" field.
func (dcrc *DNSCheckResultCreate) SetHasAaaaRecord(b bool) *DNSCheckResultCreate {
	dcrc.mutation.SetHasAaaaRecord(b)
	return dcrc
}

// SetARecords sets the "a_records" field.
func (dcrc *DNSCheckResultCreate) SetARecords(s []string) *DNSCheckResultCreate {
	dcrc.mutation.SetARecords(s)
	return dcrc
}

// SetAaaaRecords sets the "aaaa_records" field.
func (dcrc *DNSCheckResultCreate) SetAaaaRecords(s []string) *DNSCheckResultCreate {
	dcrc.mutation.SetAaaaRecords(s)
	return dcrc
}

// SetMxRecords sets the "mx_records" field.
func (dcrc *DNSCheckResultCreate) SetMxRecords(s []string) *DNSCheckResultCreate {
	dcrc.mutation.SetMxRecords(s)
	return dcrc
}

// SetTxtRecords sets the "txt_records" field.
func (dcrc *DNSCheckResultCreate) SetTxtRecords(s []string) *DNSCheckResultCreate {
	dcrc.mutation.SetTxtRecords(s)
	return dcrc
}

// SetSpfValid sets the "spf_valid" field.
func (dcrc *DNSCheckResultCreate) SetSpfValid(b bool) *DNSCheckResultCreate {
	dcrc.mutation.SetSpfValid(b)
	return dcrc
}

// SetDmarcValid sets the "dmarc_valid" field.
func (dcrc *DNSCheckResultCreate) SetDmarcValid(b bool) *DNSCheckResultCreate {
	dcrc.mutation.SetDmarcValid(b)
	return dcrc
}

// SetID sets the "id" field.
func (dcrc *DNSCheckResultCreate) SetID(u uuid.UUID) *DNSCheckResultCreate {
	dcrc.mutation.SetID(u)
	return dcrc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (dcrc *DNSCheckResultCreate) SetNillableID(u *uuid.UUID) *DNSCheckResultCreate {
	if u != nil {
		dcrc.SetID(*u)
	}
	return dcrc
}

// SetCheck sets the "check" edge to the MonitorCheck entity.
func (dcrc *DNSCheckResultCreate) SetCheck(m *MonitorCheck) *DNSCheckResultCreate {
	return dcrc.SetCheckID(m.ID)
}

// Mutation returns the DNSCheckResultMutation object of the builder.
func (dcrc *DNSCheckResultCreate) Mutation() *DNSCheckResultMutation {
	return dcrc.mutation
}

// Save creates the DNSCheckResult in the database.
func (dcrc *DNSCheckResultCreate) Save(ctx context.Context) (*DNSCheckResult, error) {
	dcrc.defaults()
	return withHooks(ctx, dcrc.sqlSave, dcrc.mutation, dcrc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (dcrc *DNSCheckResultCreate) SaveX(ctx context.Context) *DNSCheckResult {
	v, err := dcrc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcrc *DNSCheckResultCreate) Exec(ctx context.Context) error {
	_, err := dcrc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcrc *DNSCheckResultCreate) ExecX(ctx context.Context) {
	if err := dcrc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (dcrc *DNSCheckResultCreate) defaults() {
	if _, ok := dcrc.mutation.ID(); !ok {
		v := dnscheckresult.DefaultID()
		dcrc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (dcrc *DNSCheckResultCreate) check() error {
	if _, ok := dcrc.mutation.CheckID(); !ok {
		return &ValidationError{Name: "check_id", err: errors.New(`ent: missing required field "DNSCheckResult.check_id"`)}
	}
	if _, ok := dcrc.mutation.HasARecord(); !ok {
		return &ValidationError{Name: "has_a_record", err: errors.New(`ent: missing required field "DNSCheckResult.has_a_record"`)}
	}
	if _, ok := dcrc.mutation.HasAaaaRecord(); !ok {
		return &ValidationError{Name: "has_aaaa_record", err: errors.New(`ent: missing required field "DNSCheckResult.has_aaaa_record"`)}
	}
	if _, ok := dcrc.mutation.SpfValid(); !ok {
		return &ValidationError{Name: "spf_valid", err: errors.New(`ent: missing required field "DNSCheckResult.spf_valid"`)}
	}
	if _, ok := dcrc.mutation.DmarcValid(); !ok {
		return &ValidationError{Name: "dmarc_valid", err: errors.New(`ent: missing required field "DNSCheckResult.dmarc_valid"`)}
	}
	if len(dcrc.mutation.CheckIDs()) == 0 {
		return &ValidationError{Name: "check", err: errors.New(`ent: missing required edge "DNSCheckResult.check"`)}
	}
	return nil
}

func (dcrc *DNSCheckResultCreate) sqlSave(ctx context.Context) (*DNSCheckResult, error) {
	if err := dcrc.check(); err != nil {
		return nil, err
	}
	_node, _spec := dcrc.createSpec()
	if err := sqlgraph.CreateNode(ctx, dcrc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	dcrc.mutation.id = &_node.ID
	dcrc.mutation.done = true
	return _node, nil
}

func (dcrc *DNSCheckResultCreate) createSpec() (*DNSCheckResult, *sqlgraph.CreateSpec) {
	var (
		_node = &DNSCheckResult{config: dcrc.config}
		_spec = sqlgraph.NewCreateSpec(dnscheckresult.Table, sqlgraph.NewFieldSpec(dnscheckresult.FieldID, field.TypeUUID))
	)
	if id, ok := dcrc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := dcrc.mutation.HasARecord(); ok {
		_spec.SetField(dnscheckresult.FieldHasARecord, field.TypeBool, value)
		_node.HasARecord = value
	}
	if value, ok := dcrc.mutation.HasAaaaRecord(); ok {
		_spec.SetField(dnscheckresult.FieldHasAaaaRecord, field.TypeBool, value)
		_node.HasAaaaRecord = value
	}
	if value, ok := dcrc.mutation.ARecords(); ok {
		_spec.SetField(dnscheckresult.FieldARecords, field.TypeJSON, value)
		_node.ARecords = value
	}
	if value, ok := dcrc.mutation.AaaaRecords(); ok {
		_spec.SetField(dnscheckresult.FieldAaaaRecords, field.TypeJSON, value)
		_node.AaaaRecords = value
	}
	if value, ok := dcrc.mutation.MxRecords(); ok {
		_spec.SetField(dnscheckresult.FieldMxRecords, field.TypeJSON, value)
		_node.MxRecords = value
	}
	if value, ok := dcrc.mutation.TxtRecords(); ok {
		_spec.SetField(dnscheckresult.FieldTxtRecords, field.TypeJSON, value)
		_node.TxtRecords = value
	}
	if value, ok := dcrc.mutation.SpfValid(); ok {
		_spec.SetField(dnscheckresult.FieldSpfValid, field.TypeBool, value)
		_node.SpfValid = value
	}
	if value, ok := dcrc.mutation.DmarcValid(); ok {
		_spec.SetField(dnscheckresult.FieldDmarcValid, field.TypeBool, value)
		_node.DmarcValid = value
	}
	if nodes := dcrc.mutation.CheckIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   dnscheckresult.CheckTable,
			Columns: []string{dnscheckresult.CheckColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitorcheck.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CheckID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// DNSCheckResultCreateBulk is the builder for creating many DNSCheckResult entities in bulk.
type DNSCheckResultCreateBulk struct {
	config
	err      error
	builders []*DNSCheckResultCreate
}

// Save creates the DNSCheckResult entities in the database.
func (dcrcb *DNSCheckResultCreateBulk) Save(ctx context.Context) ([]*DNSCheckResult, error) {
	if dcrcb.err != nil {
		return nil, dcrcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(dcrcb.builders))
	nodes := make([]*DNSCheckResult, len(dcrcb.builders))
	mutators := make([]Mutator, len(dcrcb.builders))
	for i := range dcrcb.builders {
		func(i int, root context.Context) {
			builder := dcrcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DNSCheckResultMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, dcrcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, dcrcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, dcrcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (dcrcb *DNSCheckResultCreateBulk) SaveX(ctx context.Context) []*DNSCheckResult {
	v, err := dcrcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (dcrcb *DNSCheckResultCreateBulk) Exec(ctx context.Context) error {
	_, err := dcrcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (dcrcb *DNSCheckResultCreateBulk) ExecX(ctx context.Context) {
	if err := dcrcb.Exec(ctx); err != nil {
		panic(err)
	}
}
