// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/domaincheckresult"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitorcheck"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/predicate"
)

// DomainCheckResultQuery is the builder for querying DomainCheckResult entities.
type DomainCheckResultQuery struct {
	config
	ctx        *QueryContext
	order      []domaincheckresult.OrderOption
	inters     []Interceptor
	predicates []predicate.DomainCheckResult
	withCheck  *MonitorCheckQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the DomainCheckResultQuery builder.
func (dcrq *DomainCheckResultQuery) Where(ps ...predicate.DomainCheckResult) *DomainCheckResultQuery {
	dcrq.predicates = append(dcrq.predicates, ps...)
	return dcrq
}

// Limit the number of records to be returned by this query.
func (dcrq *DomainCheckResultQuery) Limit(limit int) *DomainCheckResultQuery {
	dcrq.ctx.Limit = &limit
	return dcrq
}

// Offset to start from.
func (dcrq *DomainCheckResultQuery) Offset(offset int) *DomainCheckResultQuery {
	dcrq.ctx.Offset = &offset
	return dcrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (dcrq *DomainCheckResultQuery) Unique(unique bool) *DomainCheckResultQuery {
	dcrq.ctx.Unique = &unique
	return dcrq
}

// Order specifies how the records should be ordered.
func (dcrq *DomainCheckResultQuery) Order(o ...domaincheckresult.OrderOption) *DomainCheckResultQuery {
	dcrq.order = append(dcrq.order, o...)
	return dcrq
}

// QueryCheck chains the current query on the "check" edge.
func (dcrq *DomainCheckResultQuery) QueryCheck() *MonitorCheckQuery {
	query := (&MonitorCheckClient{config: dcrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := dcrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := dcrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(domaincheckresult.Table, domaincheckresult.FieldID, selector),
			sqlgraph.To(monitorcheck.Table, monitorcheck.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, domaincheckresult.CheckTable, domaincheckresult.CheckColumn),
		)
		fromU = sqlgraph.SetNeighbors(dcrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first DomainCheckResult entity from the query.
// Returns a *NotFoundError when no DomainCheckResult was found.
func (dcrq *DomainCheckResultQuery) First(ctx context.Context) (*DomainCheckResult, error) {
	nodes, err := dcrq.Limit(1).All(setContextOp(ctx, dcrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{domaincheckresult.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (dcrq *DomainCheckResultQuery) FirstX(ctx context.Context) *DomainCheckResult {
	node, err := dcrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first DomainCheckResult ID from the query.
// Returns a *NotFoundError when no DomainCheckResult ID was found.
func (dcrq *DomainCheckResultQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dcrq.Limit(1).IDs(setContextOp(ctx, dcrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{domaincheckresult.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (dcrq *DomainCheckResultQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := dcrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single DomainCheckResult entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one DomainCheckResult entity is found.
// Returns a *NotFoundError when no DomainCheckResult entities are found.
func (dcrq *DomainCheckResultQuery) Only(ctx context.Context) (*DomainCheckResult, error) {
	nodes, err := dcrq.Limit(2).All(setContextOp(ctx, dcrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{domaincheckresult.Label}
	default:
		return nil, &NotSingularError{domaincheckresult.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (dcrq *DomainCheckResultQuery) OnlyX(ctx context.Context) *DomainCheckResult {
	node, err := dcrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only DomainCheckResult ID in the query.
// Returns a *NotSingularError when more than one DomainCheckResult ID is found.
// Returns a *NotFoundError when no entities are found.
func (dcrq *DomainCheckResultQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = dcrq.Limit(2).IDs(setContextOp(ctx, dcrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{domaincheckresult.Label}
	default:
		err = &NotSingularError{domaincheckresult.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (dcrq *DomainCheckResultQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := dcrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of DomainCheckResults.
func (dcrq *DomainCheckResultQuery) All(ctx context.Context) ([]*DomainCheckResult, error) {
	ctx = setContextOp(ctx, dcrq.ctx, ent.OpQueryAll)
	if err := dcrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*DomainCheckResult, *DomainCheckResultQuery]()
	return withInterceptors[[]*DomainCheckResult](ctx, dcrq, qr, dcrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (dcrq *DomainCheckResultQuery) AllX(ctx context.Context) []*DomainCheckResult {
	nodes, err := dcrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of DomainCheckResult IDs.
func (dcrq *DomainCheckResultQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if dcrq.ctx.Unique == nil && dcrq.path != nil {
		dcrq.Unique(true)
	}
	ctx = setContextOp(ctx, dcrq.ctx, ent.OpQueryIDs)
	if err = dcrq.Select(domaincheckresult.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (dcrq *DomainCheckResultQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := dcrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (dcrq *DomainCheckResultQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, dcrq.ctx, ent.OpQueryCount)
	if err := dcrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, dcrq, querierCount[*DomainCheckResultQuery](), dcrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (dcrq *DomainCheckResultQuery) CountX(ctx context.Context) int {
	count, err := dcrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (dcrq *DomainCheckResultQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, dcrq.ctx, ent.OpQueryExist)
	switch _, err := dcrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (dcrq *DomainCheckResultQuery) ExistX(ctx context.Context) bool {
	exist, err := dcrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the DomainCheckResultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (dcrq *DomainCheckResultQuery) Clone() *DomainCheckResultQuery {
	if dcrq == nil {
		return nil
	}
	return &DomainCheckResultQuery{
		config:     dcrq.config,
		ctx:        dcrq.ctx.Clone(),
		order:      append([]domaincheckresult.OrderOption{}, dcrq.order...),
		inters:     append([]Interceptor{}, dcrq.inters...),
		predicates: append([]predicate.DomainCheckResult{}, dcrq.predicates...),
		withCheck:  dcrq.withCheck.Clone(),
		// clone intermediate query.
		sql:  dcrq.sql.Clone(),
		path: dcrq.path,
	}
}

// WithCheck tells the query-builder to eager-load the nodes that are connected to
// the "check" edge. The optional arguments are used to configure the query builder of the edge.
func (dcrq *DomainCheckResultQuery) WithCheck(opts ...func(*MonitorCheckQuery)) *DomainCheckResultQuery {
	query := (&MonitorCheckClient{config: dcrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	dcrq.withCheck = query
	return dcrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CheckID uuid.UUID `json:"check_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.DomainCheckResult.Query().
//		GroupBy(domaincheckresult.FieldCheckID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (dcrq *DomainCheckResultQuery) GroupBy(field string, fields ...string) *DomainCheckResultGroupBy {
	dcrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &DomainCheckResultGroupBy{build: dcrq}
	grbuild.flds = &dcrq.ctx.Fields
	grbuild.label = domaincheckresult.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CheckID uuid.UUID `json:"check_id,omitempty"`
//	}
//
//	client.DomainCheckResult.Query().
//		Select(domaincheckresult.FieldCheckID).
//		Scan(ctx, &v)
func (dcrq *DomainCheckResultQuery) Select(fields ...string) *DomainCheckResultSelect {
	dcrq.ctx.Fields = append(dcrq.ctx.Fields, fields...)
	sbuild := &DomainCheckResultSelect{DomainCheckResultQuery: dcrq}
	sbuild.label = domaincheckresult.Label
	sbuild.flds, sbuild.scan = &dcrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a DomainCheckResultSelect configured with the given aggregations.
func (dcrq *DomainCheckResultQuery) Aggregate(fns ...AggregateFunc) *DomainCheckResultSelect {
	return dcrq.Select().Aggregate(fns...)
}

func (dcrq *DomainCheckResultQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range dcrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, dcrq); err != nil {
				return err
			}
		}
	}
	for _, f := range dcrq.ctx.Fields {
		if !domaincheckresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if dcrq.path != nil {
		prev, err := dcrq.path(ctx)
		if err != nil {
			return err
		}
		dcrq.sql = prev
	}
	return nil
}

func (dcrq *DomainCheckResultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*DomainCheckResult, error) {
	var (
		nodes       = []*DomainCheckResult{}
		_spec       = dcrq.querySpec()
		loadedTypes = [1]bool{
			dcrq.withCheck != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*DomainCheckResult).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &DomainCheckResult{config: dcrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, dcrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := dcrq.withCheck; query != nil {
		if err := dcrq.loadCheck(ctx, query, nodes, nil,
			func(n *DomainCheckResult, e *MonitorCheck) { n.Edges.Check = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (dcrq *DomainCheckResultQuery) loadCheck(ctx context.Context, query *MonitorCheckQuery, nodes []*DomainCheckResult, init func(*DomainCheckResult), assign func(*DomainCheckResult, *MonitorCheck)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*DomainCheckResult)
	for i := range nodes {
		fk := nodes[i].CheckID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(monitorcheck.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "check_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (dcrq *DomainCheckResultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := dcrq.querySpec()
	_spec.Node.Columns = dcrq.ctx.Fields
	if len(dcrq.ctx.Fields) > 0 {
		_spec.Unique = dcrq.ctx.Unique != nil && *dcrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, dcrq.driver, _spec)
}

func (dcrq *DomainCheckResultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(domaincheckresult.Table, domaincheckresult.Columns, sqlgraph.NewFieldSpec(domaincheckresult.FieldID, field.TypeUUID))
	_spec.From = dcrq.sql
	if unique := dcrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if dcrq.path != nil {
		_spec.Unique = true
	}
	if fields := dcrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, domaincheckresult.FieldID)
		for i := range fields {
			if fields[i] != domaincheckresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if dcrq.withCheck != nil {
			_spec.Node.AddColumnOnce(domaincheckresult.FieldCheckID)
		}
	}
	if ps := dcrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := dcrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := dcrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := dcrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (dcrq *DomainCheckResultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(dcrq.driver.Dialect())
	t1 := builder.Table(domaincheckresult.Table)
	columns := dcrq.ctx.Fields
	if len(columns) == 0 {
		columns = domaincheckresult.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if dcrq.sql != nil {
		selector = dcrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if dcrq.ctx.Unique != nil && *dcrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range dcrq.predicates {
		p(selector)
	}
	for _, p := range dcrq.order {
		p(selector)
	}
	if offset := dcrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := dcrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// DomainCheckResultGroupBy is the group-by builder for DomainCheckResult entities.
type DomainCheckResultGroupBy struct {
	selector
	build *DomainCheckResultQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (dcrgb *DomainCheckResultGroupBy) Aggregate(fns ...AggregateFunc) *DomainCheckResultGroupBy {
	dcrgb.fns = append(dcrgb.fns, fns...)
	return dcrgb
}

// Scan applies the selector query and scans the result into the given value.
func (dcrgb *DomainCheckResultGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dcrgb.build.ctx, ent.OpQueryGroupBy)
	if err := dcrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DomainCheckResultQuery, *DomainCheckResultGroupBy](ctx, dcrgb.build, dcrgb, dcrgb.build.inters, v)
}

func (dcrgb *DomainCheckResultGroupBy) sqlScan(ctx context.Context, root *DomainCheckResultQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(dcrgb.fns))
	for _, fn := range dcrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*dcrgb.flds)+len(dcrgb.fns))
		for _, f := range *dcrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*dcrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dcrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// DomainCheckResultSelect is the builder for selecting fields of DomainCheckResult entities.
type DomainCheckResultSelect struct {
	*DomainCheckResultQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (dcrs *DomainCheckResultSelect) Aggregate(fns ...AggregateFunc) *DomainCheckResultSelect {
	dcrs.fns = append(dcrs.fns, fns...)
	return dcrs
}

// Scan applies the selector query and scans the result into the given value.
func (dcrs *DomainCheckResultSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, dcrs.ctx, ent.OpQuerySelect)
	if err := dcrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*DomainCheckResultQuery, *DomainCheckResultSelect](ctx, dcrs.DomainCheckResultQuery, dcrs, dcrs.inters, v)
}

func (dcrs *DomainCheckResultSelect) sqlScan(ctx context.Context, root *DomainCheckResultQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(dcrs.fns))
	for _, fn := range dcrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*dcrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := dcrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
