// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/httpcheckresult"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitorcheck"
)

// HTTPCheckResult is the model entity for the HTTPCheckResult schema.
type HTTPCheckResult struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CheckID holds the value of the "check_id" field.
	CheckID uuid.UUID `json:"check_id,omitempty"`
	// StatusCode holds the value of the "status_code" field.
	StatusCode int `json:"status_code,omitempty"`
	// ResponseTimeMs holds the value of the "response_time_ms" field.
	ResponseTimeMs int64 `json:"response_time_ms,omitempty"`
	// ResponseSizeBytes holds the value of the "response_size_bytes" field.
	ResponseSizeBytes int64 `json:"response_size_bytes,omitempty"`
	// FinalURL holds the value of the "final_url" field.
	FinalURL string `json:"final_url,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the HTTPCheckResultQuery when eager-loading is set.
	Edges        HTTPCheckResultEdges `json:"edges"`
	selectValues sql.SelectValues
}

// HTTPCheckResultEdges holds the relations/edges for other nodes in the graph.
type HTTPCheckResultEdges struct {
	// Check holds the value of the check edge.
	Check *MonitorCheck `json:"check,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// CheckOrErr returns the Check value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e HTTPCheckResultEdges) CheckOrErr() (*MonitorCheck, error) {
	if e.Check != nil {
		return e.Check, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: monitorcheck.Label}
	}
	return nil, &NotLoadedError{edge: "check"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HTTPCheckResult) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case httpcheckresult.FieldStatusCode, httpcheckresult.FieldResponseTimeMs, httpcheckresult.FieldResponseSizeBytes:
			values[i] = new(sql.NullInt64)
		case httpcheckresult.FieldFinalURL:
			values[i] = new(sql.NullString)
		case httpcheckresult.FieldID, httpcheckresult.FieldCheckID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HTTPCheckResult fields.
func (hcr *HTTPCheckResult) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case httpcheckresult.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				hcr.ID = *value
			}
		case httpcheckresult.FieldCheckID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field check_id", values[i])
			} else if value != nil {
				hcr.CheckID = *value
			}
		case httpcheckresult.FieldStatusCode:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_code", values[i])
			} else if value.Valid {
				hcr.StatusCode = int(value.Int64)
			}
		case httpcheckresult.FieldResponseTimeMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_time_ms", values[i])
			} else if value.Valid {
				hcr.ResponseTimeMs = value.Int64
			}
		case httpcheckresult.FieldResponseSizeBytes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field response_size_bytes", values[i])
			} else if value.Valid {
				hcr.ResponseSizeBytes = value.Int64
			}
		case httpcheckresult.FieldFinalURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field final_url", values[i])
			} else if value.Valid {
				hcr.FinalURL = value.String
			}
		default:
			hcr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HTTPCheckResult.
// This includes values selected through modifiers, order, etc.
func (hcr *HTTPCheckResult) Value(name string) (ent.Value, error) {
	return hcr.selectValues.Get(name)
}

// QueryCheck queries the "check" edge of the HTTPCheckResult entity.
func (hcr *HTTPCheckResult) QueryCheck() *MonitorCheckQuery {
	return NewHTTPCheckResultClient(hcr.config).QueryCheck(hcr)
}

// Update returns a builder for updating this HTTPCheckResult.
// Note that you need to call HTTPCheckResult.Unwrap() before calling this method if this HTTPCheckResult
// was returned from a transaction, and the transaction was committed or rolled back.
func (hcr *HTTPCheckResult) Update() *HTTPCheckResultUpdateOne {
	return NewHTTPCheckResultClient(hcr.config).UpdateOne(hcr)
}

// Unwrap unwraps the HTTPCheckResult entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (hcr *HTTPCheckResult) Unwrap() *HTTPCheckResult {
	_tx, ok := hcr.config.driver.(*txDriver)
	if !ok {
		panic("ent: HTTPCheckResult is not a transactional entity")
	}
	hcr.config.driver = _tx.drv
	return hcr
}

// String implements the fmt.Stringer.
func (hcr *HTTPCheckResult) String() string {
	var builder strings.Builder
	builder.WriteString("HTTPCheckResult(")
	builder.WriteString(fmt.Sprintf("id=%v, ", hcr.ID))
	builder.WriteString("check_id=")
	builder.WriteString(fmt.Sprintf("%v", hcr.CheckID))
	builder.WriteString(", ")
	builder.WriteString("status_code=")
	builder.WriteString(fmt.Sprintf("%v", hcr.StatusCode))
	builder.WriteString(", ")
	builder.WriteString("response_time_ms=")
	builder.WriteString(fmt.Sprintf("%v", hcr.ResponseTimeMs))
	builder.WriteString(", ")
	builder.WriteString("response_size_bytes=")
	builder.WriteString(fmt.Sprintf("%v", hcr.ResponseSizeBytes))
	builder.WriteString(", ")
	builder.WriteString("final_url=")
	builder.WriteString(hcr.FinalURL)
	builder.WriteByte(')')
	return builder.String()
}

// HTTPCheckResults is a parsable slice of HTTPCheckResult.
type HTTPCheckResults []*HTTPCheckResult
