// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/httpcheckresult"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/predicate"
)

// HTTPCheckResultDelete is the builder for deleting a HTTPCheckResult entity.
type HTTPCheckResultDelete struct {
	config
	hooks    []Hook
	mutation *HTTPCheckResultMutation
}

// Where appends a list predicates to the HTTPCheckResultDelete builder.
func (hcrd *HTTPCheckResultDelete) Where(ps ...predicate.HTTPCheckResult) *HTTPCheckResultDelete {
	hcrd.mutation.Where(ps...)
	return hcrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (hcrd *HTTPCheckResultDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, hcrd.sqlExec, hcrd.mutation, hcrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (hcrd *HTTPCheckResultDelete) ExecX(ctx context.Context) int {
	n, err := hcrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (hcrd *HTTPCheckResultDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(httpcheckresult.Table, sqlgraph.NewFieldSpec(httpcheckresult.FieldID, field.TypeUUID))
	if ps := hcrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, hcrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	hcrd.mutation.done = true
	return affected, err
}

// HTTPCheckResultDeleteOne is the builder for deleting a single HTTPCheckResult entity.
type HTTPCheckResultDeleteOne struct {
	hcrd *HTTPCheckResultDelete
}

// Where appends a list predicates to the HTTPCheckResultDelete builder.
func (hcrdo *HTTPCheckResultDeleteOne) Where(ps ...predicate.HTTPCheckResult) *HTTPCheckResultDeleteOne {
	hcrdo.hcrd.mutation.Where(ps...)
	return hcrdo
}

// Exec executes the deletion query.
func (hcrdo *HTTPCheckResultDeleteOne) Exec(ctx context.Context) error {
	n, err := hcrdo.hcrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{httpcheckresult.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (hcrdo *HTTPCheckResultDeleteOne) ExecX(ctx context.Context) {
	if err := hcrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
