// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/alert"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/alertevent"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitor"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitorcheck"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitorcheckconfig"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/tenant"
)

// MonitorCreate is the builder for creating a Monitor entity.
type MonitorCreate struct {
	config
	mutation *MonitorMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (mc *MonitorCreate) SetTenantID(u uuid.UUID) *MonitorCreate {
	mc.mutation.SetTenantID(u)
	return mc
}

// SetName sets the "name" field.
func (mc *MonitorCreate) SetName(s string) *MonitorCreate {
	mc.mutation.SetName(s)
	return mc
}

// SetURL sets the "url" field.
func (mc *MonitorCreate) SetURL(s string) *MonitorCreate {
	mc.mutation.SetURL(s)
	return mc
}

// SetDomain sets the "domain" field.
func (mc *MonitorCreate) SetDomain(s string) *MonitorCreate {
	mc.mutation.SetDomain(s)
	return mc
}

// SetType sets the "type" field.
func (mc *MonitorCreate) SetType(m monitor.Type) *MonitorCreate {
	mc.mutation.SetType(m)
	return mc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (mc *MonitorCreate) SetNillableType(m *monitor.Type) *MonitorCreate {
	if m != nil {
		mc.SetType(*m)
	}
	return mc
}

// SetEnabledChecks sets the "enabled_checks" field.
func (mc *MonitorCreate) SetEnabledChecks(m map[string]bool) *MonitorCreate {
	mc.mutation.SetEnabledChecks(m)
	return mc
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (mc *MonitorCreate) SetIntervalSeconds(i int) *MonitorCreate {
	mc.mutation.SetIntervalSeconds(i)
	return mc
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (mc *MonitorCreate) SetNillableIntervalSeconds(i *int) *MonitorCreate {
	if i != nil {
		mc.SetIntervalSeconds(*i)
	}
	return mc
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (mc *MonitorCreate) SetTimeoutSeconds(i int) *MonitorCreate {
	mc.mutation.SetTimeoutSeconds(i)
	return mc
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (mc *MonitorCreate) SetNillableTimeoutSeconds(i *int) *MonitorCreate {
	if i != nil {
		mc.SetTimeoutSeconds(*i)
	}
	return mc
}

// SetIsActive sets the "is_active" field.
func (mc *MonitorCreate) SetIsActive(b bool) *MonitorCreate {
	mc.mutation.SetIsActive(b)
	return mc
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (mc *MonitorCreate) SetNillableIsActive(b *bool) *MonitorCreate {
	if b != nil {
		mc.SetIsActive(*b)
	}
	return mc
}

// SetCreatedAt sets the "created_at" field.
func (mc *MonitorCreate) SetCreatedAt(t time.Time) *MonitorCreate {
	mc.mutation.SetCreatedAt(t)
	return mc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mc *MonitorCreate) SetNillableCreatedAt(t *time.Time) *MonitorCreate {
	if t != nil {
		mc.SetCreatedAt(*t)
	}
	return mc
}

// SetID sets the "id" field.
func (mc *MonitorCreate) SetID(u uuid.UUID) *MonitorCreate {
	mc.mutation.SetID(u)
	return mc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mc *MonitorCreate) SetNillableID(u *uuid.UUID) *MonitorCreate {
	if u != nil {
		mc.SetID(*u)
	}
	return mc
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (mc *MonitorCreate) SetTenant(t *Tenant) *MonitorCreate {
	return mc.SetTenantID(t.ID)
}

// AddCheckIDs adds the "checks" edge to the MonitorCheck entity by IDs.
func (mc *MonitorCreate) AddCheckIDs(ids ...uuid.UUID) *MonitorCreate {
	mc.mutation.AddCheckIDs(ids...)
	return mc
}

// AddChecks adds the "checks" edges to the MonitorCheck entity.
func (mc *MonitorCreate) AddChecks(m ...*MonitorCheck) *MonitorCreate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mc.AddCheckIDs(ids...)
}

// AddCheckConfigIDs adds the "check_configs" edge to the MonitorCheckConfig entity by IDs.
func (mc *MonitorCreate) AddCheckConfigIDs(ids ...uuid.UUID) *MonitorCreate {
	mc.mutation.AddCheckConfigIDs(ids...)
	return mc
}

// AddCheckConfigs adds the "check_configs" edges to the MonitorCheckConfig entity.
func (mc *MonitorCreate) AddCheckConfigs(m ...*MonitorCheckConfig) *MonitorCreate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return mc.AddCheckConfigIDs(ids...)
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (mc *MonitorCreate) AddAlertIDs(ids ...uuid.UUID) *MonitorCreate {
	mc.mutation.AddAlertIDs(ids...)
	return mc
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (mc *MonitorCreate) AddAlerts(a ...*Alert) *MonitorCreate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return mc.AddAlertIDs(ids...)
}

// AddAlertEventIDs adds the "alert_events" edge to the AlertEvent entity by IDs.
func (mc *MonitorCreate) AddAlertEventIDs(ids ...uuid.UUID) *MonitorCreate {
	mc.mutation.AddAlertEventIDs(ids...)
	return mc
}

// AddAlertEvents adds the "alert_events" edges to the AlertEvent entity.
func (mc *MonitorCreate) AddAlertEvents(a ...*AlertEvent) *MonitorCreate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return mc.AddAlertEventIDs(ids...)
}

// Mutation returns the MonitorMutation object of the builder.
func (mc *MonitorCreate) Mutation() *MonitorMutation {
	return mc.mutation
}

// Save creates the Monitor in the database.
func (mc *MonitorCreate) Save(ctx context.Context) (*Monitor, error) {
	mc.defaults()
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MonitorCreate) SaveX(ctx context.Context) *Monitor {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MonitorCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MonitorCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MonitorCreate) defaults() {
	if _, ok := mc.mutation.GetType(); !ok {
		v := monitor.DefaultType
		mc.mutation.SetType(v)
	}
	if _, ok := mc.mutation.IntervalSeconds(); !ok {
		v := monitor.DefaultIntervalSeconds
		mc.mutation.SetIntervalSeconds(v)
	}
	if _, ok := mc.mutation.TimeoutSeconds(); !ok {
		v := monitor.DefaultTimeoutSeconds
		mc.mutation.SetTimeoutSeconds(v)
	}
	if _, ok := mc.mutation.IsActive(); !ok {
		v := monitor.DefaultIsActive
		mc.mutation.SetIsActive(v)
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		v := monitor.DefaultCreatedAt()
		mc.mutation.SetCreatedAt(v)
	}
	if _, ok := mc.mutation.ID(); !ok {
		v := monitor.DefaultID()
		mc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MonitorCreate) check() error {
	if _, ok := mc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "Monitor.tenant_id"`)}
	}
	if _, ok := mc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Monitor.name"`)}
	}
	if v, ok := mc.mutation.Name(); ok {
		if err := monitor.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Monitor.name": %w`, err)}
		}
	}
	if _, ok := mc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "Monitor.url"`)}
	}
	if v, ok := mc.mutation.URL(); ok {
		if err := monitor.URLValidator(v); err != nil {
			return &ValidationError{Name: "url", err: fmt.Errorf(`ent: validator failed for field "Monitor.url": %w`, err)}
		}
	}
	if _, ok := mc.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "Monitor.domain"`)}
	}
	if v, ok := mc.mutation.Domain(); ok {
		if err := monitor.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "Monitor.domain": %w`, err)}
		}
	}
	if _, ok := mc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Monitor.type"`)}
	}
	if v, ok := mc.mutation.GetType(); ok {
		if err := monitor.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Monitor.type": %w`, err)}
		}
	}
	if _, ok := mc.mutation.IntervalSeconds(); !ok {
		return &ValidationError{Name: "interval_seconds", err: errors.New(`ent: missing required field "Monitor.interval_seconds"`)}
	}
	if _, ok := mc.mutation.TimeoutSeconds(); !ok {
		return &ValidationError{Name: "timeout_seconds", err: errors.New(`ent: missing required field "Monitor.timeout_seconds"`)}
	}
	if _, ok := mc.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "Monitor.is_active"`)}
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Monitor.created_at"`)}
	}
	if len(mc.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "Monitor.tenant"`)}
	}
	return nil
}

func (mc *MonitorCreate) sqlSave(ctx context.Context) (*Monitor, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MonitorCreate) createSpec() (*Monitor, *sqlgraph.CreateSpec) {
	var (
		_node = &Monitor{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(monitor.Table, sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID))
	)
	if id, ok := mc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mc.mutation.Name(); ok {
		_spec.SetField(monitor.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := mc.mutation.URL(); ok {
		_spec.SetField(monitor.FieldURL, field.TypeString, value)
		_node.URL = value
	}
	if value, ok := mc.mutation.Domain(); ok {
		_spec.SetField(monitor.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if value, ok := mc.mutation.GetType(); ok {
		_spec.SetField(monitor.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := mc.mutation.EnabledChecks(); ok {
		_spec.SetField(monitor.FieldEnabledChecks, field.TypeJSON, value)
		_node.EnabledChecks = value
	}
	if value, ok := mc.mutation.IntervalSeconds(); ok {
		_spec.SetField(monitor.FieldIntervalSeconds, field.TypeInt, value)
		_node.IntervalSeconds = value
	}
	if value, ok := mc.mutation.TimeoutSeconds(); ok {
		_spec.SetField(monitor.FieldTimeoutSeconds, field.TypeInt, value)
		_node.TimeoutSeconds = value
	}
	if value, ok := mc.mutation.IsActive(); ok {
		_spec.SetField(monitor.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.SetField(monitor.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := mc.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   monitor.TenantTable,
			Columns: []string{monitor.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mc.mutation.ChecksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   monitor.ChecksTable,
			Columns: []string{monitor.ChecksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitorcheck.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mc.mutation.CheckConfigsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   monitor.CheckConfigsTable,
			Columns: []string{monitor.CheckConfigsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitorcheckconfig.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mc.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   monitor.AlertsTable,
			Columns: []string{monitor.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mc.mutation.AlertEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   monitor.AlertEventsTable,
			Columns: []string{monitor.AlertEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MonitorCreateBulk is the builder for creating many Monitor entities in bulk.
type MonitorCreateBulk struct {
	config
	err      error
	builders []*MonitorCreate
}

// Save creates the Monitor entities in the database.
func (mcb *MonitorCreateBulk) Save(ctx context.Context) ([]*Monitor, error) {
	if mcb.err != nil {
		return nil, mcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Monitor, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MonitorMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MonitorCreateBulk) SaveX(ctx context.Context) []*Monitor {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MonitorCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MonitorCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
