// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitor"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitorcheckconfig"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/predicate"
)

// MonitorCheckConfigUpdate is the builder for updating MonitorCheckConfig entities.
type MonitorCheckConfigUpdate struct {
	config
	hooks    []Hook
	mutation *MonitorCheckConfigMutation
}

// Where appends a list predicates to the MonitorCheckConfigUpdate builder.
func (mccu *MonitorCheckConfigUpdate) Where(ps ...predicate.MonitorCheckConfig) *MonitorCheckConfigUpdate {
	mccu.mutation.Where(ps...)
	return mccu
}

// SetMonitorID sets the "monitor_id" field.
func (mccu *MonitorCheckConfigUpdate) SetMonitorID(u uuid.UUID) *MonitorCheckConfigUpdate {
	mccu.mutation.SetMonitorID(u)
	return mccu
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (mccu *MonitorCheckConfigUpdate) SetNillableMonitorID(u *uuid.UUID) *MonitorCheckConfigUpdate {
	if u != nil {
		mccu.SetMonitorID(*u)
	}
	return mccu
}

// SetCheckType sets the "check_type" field.
func (mccu *MonitorCheckConfigUpdate) SetCheckType(mt monitorcheckconfig.CheckType) *MonitorCheckConfigUpdate {
	mccu.mutation.SetCheckType(mt)
	return mccu
}

// SetNillableCheckType sets the "check_type" field if the given value is not nil.
func (mccu *MonitorCheckConfigUpdate) SetNillableCheckType(mt *monitorcheckconfig.CheckType) *MonitorCheckConfigUpdate {
	if mt != nil {
		mccu.SetCheckType(*mt)
	}
	return mccu
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (mccu *MonitorCheckConfigUpdate) SetIntervalSeconds(i int) *MonitorCheckConfigUpdate {
	mccu.mutation.ResetIntervalSeconds()
	mccu.mutation.SetIntervalSeconds(i)
	return mccu
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (mccu *MonitorCheckConfigUpdate) SetNillableIntervalSeconds(i *int) *MonitorCheckConfigUpdate {
	if i != nil {
		mccu.SetIntervalSeconds(*i)
	}
	return mccu
}

// AddIntervalSeconds adds i to the "interval_seconds" field.
func (mccu *MonitorCheckConfigUpdate) AddIntervalSeconds(i int) *MonitorCheckConfigUpdate {
	mccu.mutation.AddIntervalSeconds(i)
	return mccu
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (mccu *MonitorCheckConfigUpdate) SetTimeoutSeconds(i int) *MonitorCheckConfigUpdate {
	mccu.mutation.ResetTimeoutSeconds()
	mccu.mutation.SetTimeoutSeconds(i)
	return mccu
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (mccu *MonitorCheckConfigUpdate) SetNillableTimeoutSeconds(i *int) *MonitorCheckConfigUpdate {
	if i != nil {
		mccu.SetTimeoutSeconds(*i)
	}
	return mccu
}

// AddTimeoutSeconds adds i to the "timeout_seconds" field.
func (mccu *MonitorCheckConfigUpdate) AddTimeoutSeconds(i int) *MonitorCheckConfigUpdate {
	mccu.mutation.AddTimeoutSeconds(i)
	return mccu
}

// SetIsEnabled sets the "is_enabled" field.
func (mccu *MonitorCheckConfigUpdate) SetIsEnabled(b bool) *MonitorCheckConfigUpdate {
	mccu.mutation.SetIsEnabled(b)
	return mccu
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (mccu *MonitorCheckConfigUpdate) SetNillableIsEnabled(b *bool) *MonitorCheckConfigUpdate {
	if b != nil {
		mccu.SetIsEnabled(*b)
	}
	return mccu
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (mccu *MonitorCheckConfigUpdate) SetLastCheckedAt(t time.Time) *MonitorCheckConfigUpdate {
	mccu.mutation.SetLastCheckedAt(t)
	return mccu
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (mccu *MonitorCheckConfigUpdate) SetNillableLastCheckedAt(t *time.Time) *MonitorCheckConfigUpdate {
	if t != nil {
		mccu.SetLastCheckedAt(*t)
	}
	return mccu
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (mccu *MonitorCheckConfigUpdate) ClearLastCheckedAt() *MonitorCheckConfigUpdate {
	mccu.mutation.ClearLastCheckedAt()
	return mccu
}

// SetNextCheckAt sets the "next_check_at" field.
func (mccu *MonitorCheckConfigUpdate) SetNextCheckAt(t time.Time) *MonitorCheckConfigUpdate {
	mccu.mutation.SetNextCheckAt(t)
	return mccu
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (mccu *MonitorCheckConfigUpdate) SetNillableNextCheckAt(t *time.Time) *MonitorCheckConfigUpdate {
	if t != nil {
		mccu.SetNextCheckAt(*t)
	}
	return mccu
}

// SetCreatedAt sets the "created_at" field.
func (mccu *MonitorCheckConfigUpdate) SetCreatedAt(t time.Time) *MonitorCheckConfigUpdate {
	mccu.mutation.SetCreatedAt(t)
	return mccu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mccu *MonitorCheckConfigUpdate) SetNillableCreatedAt(t *time.Time) *MonitorCheckConfigUpdate {
	if t != nil {
		mccu.SetCreatedAt(*t)
	}
	return mccu
}

// SetMonitor sets the "monitor" edge to the Monitor entity.
func (mccu *MonitorCheckConfigUpdate) SetMonitor(m *Monitor) *MonitorCheckConfigUpdate {
	return mccu.SetMonitorID(m.ID)
}

// Mutation returns the MonitorCheckConfigMutation object of the builder.
func (mccu *MonitorCheckConfigUpdate) Mutation() *MonitorCheckConfigMutation {
	return mccu.mutation
}

// ClearMonitor clears the "monitor" edge to the Monitor entity.
func (mccu *MonitorCheckConfigUpdate) ClearMonitor() *MonitorCheckConfigUpdate {
	mccu.mutation.ClearMonitor()
	return mccu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mccu *MonitorCheckConfigUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mccu.sqlSave, mccu.mutation, mccu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mccu *MonitorCheckConfigUpdate) SaveX(ctx context.Context) int {
	affected, err := mccu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mccu *MonitorCheckConfigUpdate) Exec(ctx context.Context) error {
	_, err := mccu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mccu *MonitorCheckConfigUpdate) ExecX(ctx context.Context) {
	if err := mccu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mccu *MonitorCheckConfigUpdate) check() error {
	if v, ok := mccu.mutation.CheckType(); ok {
		if err := monitorcheckconfig.CheckTypeValidator(v); err != nil {
			return &ValidationError{Name: "check_type", err: fmt.Errorf(`ent: validator failed for field "MonitorCheckConfig.check_type": %w`, err)}
		}
	}
	if v, ok := mccu.mutation.IntervalSeconds(); ok {
		if err := monitorcheckconfig.IntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "interval_seconds", err: fmt.Errorf(`ent: validator failed for field "MonitorCheckConfig.interval_seconds": %w`, err)}
		}
	}
	if mccu.mutation.MonitorCleared() && len(mccu.mutation.MonitorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MonitorCheckConfig.monitor"`)
	}
	return nil
}

func (mccu *MonitorCheckConfigUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mccu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitorcheckconfig.Table, monitorcheckconfig.Columns, sqlgraph.NewFieldSpec(monitorcheckconfig.FieldID, field.TypeUUID))
	if ps := mccu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mccu.mutation.CheckType(); ok {
		_spec.SetField(monitorcheckconfig.FieldCheckType, field.TypeEnum, value)
	}
	if value, ok := mccu.mutation.IntervalSeconds(); ok {
		_spec.SetField(monitorcheckconfig.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := mccu.mutation.AddedIntervalSeconds(); ok {
		_spec.AddField(monitorcheckconfig.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := mccu.mutation.TimeoutSeconds(); ok {
		_spec.SetField(monitorcheckconfig.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := mccu.mutation.AddedTimeoutSeconds(); ok {
		_spec.AddField(monitorcheckconfig.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := mccu.mutation.IsEnabled(); ok {
		_spec.SetField(monitorcheckconfig.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := mccu.mutation.LastCheckedAt(); ok {
		_spec.SetField(monitorcheckconfig.FieldLastCheckedAt, field.TypeTime, value)
	}
	if mccu.mutation.LastCheckedAtCleared() {
		_spec.ClearField(monitorcheckconfig.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := mccu.mutation.NextCheckAt(); ok {
		_spec.SetField(monitorcheckconfig.FieldNextCheckAt, field.TypeTime, value)
	}
	if value, ok := mccu.mutation.CreatedAt(); ok {
		_spec.SetField(monitorcheckconfig.FieldCreatedAt, field.TypeTime, value)
	}
	if mccu.mutation.MonitorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   monitorcheckconfig.MonitorTable,
			Columns: []string{monitorcheckconfig.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mccu.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   monitorcheckconfig.MonitorTable,
			Columns: []string{monitorcheckconfig.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mccu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitorcheckconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mccu.mutation.done = true
	return n, nil
}

// MonitorCheckConfigUpdateOne is the builder for updating a single MonitorCheckConfig entity.
type MonitorCheckConfigUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MonitorCheckConfigMutation
}

// SetMonitorID sets the "monitor_id" field.
func (mccuo *MonitorCheckConfigUpdateOne) SetMonitorID(u uuid.UUID) *MonitorCheckConfigUpdateOne {
	mccuo.mutation.SetMonitorID(u)
	return mccuo
}

// SetNillableMonitorID sets the "monitor_id" field if the given value is not nil.
func (mccuo *MonitorCheckConfigUpdateOne) SetNillableMonitorID(u *uuid.UUID) *MonitorCheckConfigUpdateOne {
	if u != nil {
		mccuo.SetMonitorID(*u)
	}
	return mccuo
}

// SetCheckType sets the "check_type" field.
func (mccuo *MonitorCheckConfigUpdateOne) SetCheckType(mt monitorcheckconfig.CheckType) *MonitorCheckConfigUpdateOne {
	mccuo.mutation.SetCheckType(mt)
	return mccuo
}

// SetNillableCheckType sets the "check_type" field if the given value is not nil.
func (mccuo *MonitorCheckConfigUpdateOne) SetNillableCheckType(mt *monitorcheckconfig.CheckType) *MonitorCheckConfigUpdateOne {
	if mt != nil {
		mccuo.SetCheckType(*mt)
	}
	return mccuo
}

// SetIntervalSeconds sets the "interval_seconds" field.
func (mccuo *MonitorCheckConfigUpdateOne) SetIntervalSeconds(i int) *MonitorCheckConfigUpdateOne {
	mccuo.mutation.ResetIntervalSeconds()
	mccuo.mutation.SetIntervalSeconds(i)
	return mccuo
}

// SetNillableIntervalSeconds sets the "interval_seconds" field if the given value is not nil.
func (mccuo *MonitorCheckConfigUpdateOne) SetNillableIntervalSeconds(i *int) *MonitorCheckConfigUpdateOne {
	if i != nil {
		mccuo.SetIntervalSeconds(*i)
	}
	return mccuo
}

// AddIntervalSeconds adds i to the "interval_seconds" field.
func (mccuo *MonitorCheckConfigUpdateOne) AddIntervalSeconds(i int) *MonitorCheckConfigUpdateOne {
	mccuo.mutation.AddIntervalSeconds(i)
	return mccuo
}

// SetTimeoutSeconds sets the "timeout_seconds" field.
func (mccuo *MonitorCheckConfigUpdateOne) SetTimeoutSeconds(i int) *MonitorCheckConfigUpdateOne {
	mccuo.mutation.ResetTimeoutSeconds()
	mccuo.mutation.SetTimeoutSeconds(i)
	return mccuo
}

// SetNillableTimeoutSeconds sets the "timeout_seconds" field if the given value is not nil.
func (mccuo *MonitorCheckConfigUpdateOne) SetNillableTimeoutSeconds(i *int) *MonitorCheckConfigUpdateOne {
	if i != nil {
		mccuo.SetTimeoutSeconds(*i)
	}
	return mccuo
}

// AddTimeoutSeconds adds i to the "timeout_seconds" field.
func (mccuo *MonitorCheckConfigUpdateOne) AddTimeoutSeconds(i int) *MonitorCheckConfigUpdateOne {
	mccuo.mutation.AddTimeoutSeconds(i)
	return mccuo
}

// SetIsEnabled sets the "is_enabled" field.
func (mccuo *MonitorCheckConfigUpdateOne) SetIsEnabled(b bool) *MonitorCheckConfigUpdateOne {
	mccuo.mutation.SetIsEnabled(b)
	return mccuo
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (mccuo *MonitorCheckConfigUpdateOne) SetNillableIsEnabled(b *bool) *MonitorCheckConfigUpdateOne {
	if b != nil {
		mccuo.SetIsEnabled(*b)
	}
	return mccuo
}

// SetLastCheckedAt sets the "last_checked_at" field.
func (mccuo *MonitorCheckConfigUpdateOne) SetLastCheckedAt(t time.Time) *MonitorCheckConfigUpdateOne {
	mccuo.mutation.SetLastCheckedAt(t)
	return mccuo
}

// SetNillableLastCheckedAt sets the "last_checked_at" field if the given value is not nil.
func (mccuo *MonitorCheckConfigUpdateOne) SetNillableLastCheckedAt(t *time.Time) *MonitorCheckConfigUpdateOne {
	if t != nil {
		mccuo.SetLastCheckedAt(*t)
	}
	return mccuo
}

// ClearLastCheckedAt clears the value of the "last_checked_at" field.
func (mccuo *MonitorCheckConfigUpdateOne) ClearLastCheckedAt() *MonitorCheckConfigUpdateOne {
	mccuo.mutation.ClearLastCheckedAt()
	return mccuo
}

// SetNextCheckAt sets the "next_check_at" field.
func (mccuo *MonitorCheckConfigUpdateOne) SetNextCheckAt(t time.Time) *MonitorCheckConfigUpdateOne {
	mccuo.mutation.SetNextCheckAt(t)
	return mccuo
}

// SetNillableNextCheckAt sets the "next_check_at" field if the given value is not nil.
func (mccuo *MonitorCheckConfigUpdateOne) SetNillableNextCheckAt(t *time.Time) *MonitorCheckConfigUpdateOne {
	if t != nil {
		mccuo.SetNextCheckAt(*t)
	}
	return mccuo
}

// SetCreatedAt sets the "created_at" field.
func (mccuo *MonitorCheckConfigUpdateOne) SetCreatedAt(t time.Time) *MonitorCheckConfigUpdateOne {
	mccuo.mutation.SetCreatedAt(t)
	return mccuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mccuo *MonitorCheckConfigUpdateOne) SetNillableCreatedAt(t *time.Time) *MonitorCheckConfigUpdateOne {
	if t != nil {
		mccuo.SetCreatedAt(*t)
	}
	return mccuo
}

// SetMonitor sets the "monitor" edge to the Monitor entity.
func (mccuo *MonitorCheckConfigUpdateOne) SetMonitor(m *Monitor) *MonitorCheckConfigUpdateOne {
	return mccuo.SetMonitorID(m.ID)
}

// Mutation returns the MonitorCheckConfigMutation object of the builder.
func (mccuo *MonitorCheckConfigUpdateOne) Mutation() *MonitorCheckConfigMutation {
	return mccuo.mutation
}

// ClearMonitor clears the "monitor" edge to the Monitor entity.
func (mccuo *MonitorCheckConfigUpdateOne) ClearMonitor() *MonitorCheckConfigUpdateOne {
	mccuo.mutation.ClearMonitor()
	return mccuo
}

// Where appends a list predicates to the MonitorCheckConfigUpdate builder.
func (mccuo *MonitorCheckConfigUpdateOne) Where(ps ...predicate.MonitorCheckConfig) *MonitorCheckConfigUpdateOne {
	mccuo.mutation.Where(ps...)
	return mccuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mccuo *MonitorCheckConfigUpdateOne) Select(field string, fields ...string) *MonitorCheckConfigUpdateOne {
	mccuo.fields = append([]string{field}, fields...)
	return mccuo
}

// Save executes the query and returns the updated MonitorCheckConfig entity.
func (mccuo *MonitorCheckConfigUpdateOne) Save(ctx context.Context) (*MonitorCheckConfig, error) {
	return withHooks(ctx, mccuo.sqlSave, mccuo.mutation, mccuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mccuo *MonitorCheckConfigUpdateOne) SaveX(ctx context.Context) *MonitorCheckConfig {
	node, err := mccuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mccuo *MonitorCheckConfigUpdateOne) Exec(ctx context.Context) error {
	_, err := mccuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mccuo *MonitorCheckConfigUpdateOne) ExecX(ctx context.Context) {
	if err := mccuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mccuo *MonitorCheckConfigUpdateOne) check() error {
	if v, ok := mccuo.mutation.CheckType(); ok {
		if err := monitorcheckconfig.CheckTypeValidator(v); err != nil {
			return &ValidationError{Name: "check_type", err: fmt.Errorf(`ent: validator failed for field "MonitorCheckConfig.check_type": %w`, err)}
		}
	}
	if v, ok := mccuo.mutation.IntervalSeconds(); ok {
		if err := monitorcheckconfig.IntervalSecondsValidator(v); err != nil {
			return &ValidationError{Name: "interval_seconds", err: fmt.Errorf(`ent: validator failed for field "MonitorCheckConfig.interval_seconds": %w`, err)}
		}
	}
	if mccuo.mutation.MonitorCleared() && len(mccuo.mutation.MonitorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "MonitorCheckConfig.monitor"`)
	}
	return nil
}

func (mccuo *MonitorCheckConfigUpdateOne) sqlSave(ctx context.Context) (_node *MonitorCheckConfig, err error) {
	if err := mccuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(monitorcheckconfig.Table, monitorcheckconfig.Columns, sqlgraph.NewFieldSpec(monitorcheckconfig.FieldID, field.TypeUUID))
	id, ok := mccuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MonitorCheckConfig.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mccuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, monitorcheckconfig.FieldID)
		for _, f := range fields {
			if !monitorcheckconfig.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != monitorcheckconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mccuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mccuo.mutation.CheckType(); ok {
		_spec.SetField(monitorcheckconfig.FieldCheckType, field.TypeEnum, value)
	}
	if value, ok := mccuo.mutation.IntervalSeconds(); ok {
		_spec.SetField(monitorcheckconfig.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := mccuo.mutation.AddedIntervalSeconds(); ok {
		_spec.AddField(monitorcheckconfig.FieldIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := mccuo.mutation.TimeoutSeconds(); ok {
		_spec.SetField(monitorcheckconfig.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := mccuo.mutation.AddedTimeoutSeconds(); ok {
		_spec.AddField(monitorcheckconfig.FieldTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := mccuo.mutation.IsEnabled(); ok {
		_spec.SetField(monitorcheckconfig.FieldIsEnabled, field.TypeBool, value)
	}
	if value, ok := mccuo.mutation.LastCheckedAt(); ok {
		_spec.SetField(monitorcheckconfig.FieldLastCheckedAt, field.TypeTime, value)
	}
	if mccuo.mutation.LastCheckedAtCleared() {
		_spec.ClearField(monitorcheckconfig.FieldLastCheckedAt, field.TypeTime)
	}
	if value, ok := mccuo.mutation.NextCheckAt(); ok {
		_spec.SetField(monitorcheckconfig.FieldNextCheckAt, field.TypeTime, value)
	}
	if value, ok := mccuo.mutation.CreatedAt(); ok {
		_spec.SetField(monitorcheckconfig.FieldCreatedAt, field.TypeTime, value)
	}
	if mccuo.mutation.MonitorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   monitorcheckconfig.MonitorTable,
			Columns: []string{monitorcheckconfig.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mccuo.mutation.MonitorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   monitorcheckconfig.MonitorTable,
			Columns: []string{monitorcheckconfig.MonitorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &MonitorCheckConfig{config: mccuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mccuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{monitorcheckconfig.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mccuo.mutation.done = true
	return _node, nil
}
