// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitorcheckconfig"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/predicate"
)

// MonitorCheckConfigDelete is the builder for deleting a MonitorCheckConfig entity.
type MonitorCheckConfigDelete struct {
	config
	hooks    []Hook
	mutation *MonitorCheckConfigMutation
}

// Where appends a list predicates to the MonitorCheckConfigDelete builder.
func (mccd *MonitorCheckConfigDelete) Where(ps ...predicate.MonitorCheckConfig) *MonitorCheckConfigDelete {
	mccd.mutation.Where(ps...)
	return mccd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mccd *MonitorCheckConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mccd.sqlExec, mccd.mutation, mccd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mccd *MonitorCheckConfigDelete) ExecX(ctx context.Context) int {
	n, err := mccd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mccd *MonitorCheckConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(monitorcheckconfig.Table, sqlgraph.NewFieldSpec(monitorcheckconfig.FieldID, field.TypeUUID))
	if ps := mccd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mccd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mccd.mutation.done = true
	return affected, err
}

// MonitorCheckConfigDeleteOne is the builder for deleting a single MonitorCheckConfig entity.
type MonitorCheckConfigDeleteOne struct {
	mccd *MonitorCheckConfigDelete
}

// Where appends a list predicates to the MonitorCheckConfigDelete builder.
func (mccdo *MonitorCheckConfigDeleteOne) Where(ps ...predicate.MonitorCheckConfig) *MonitorCheckConfigDeleteOne {
	mccdo.mccd.mutation.Where(ps...)
	return mccdo
}

// Exec executes the deletion query.
func (mccdo *MonitorCheckConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := mccdo.mccd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{monitorcheckconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mccdo *MonitorCheckConfigDeleteOne) ExecX(ctx context.Context) {
	if err := mccdo.Exec(ctx); err != nil {
		panic(err)
	}
}
