// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/dnscheckresult"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/domaincheckresult"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/httpcheckresult"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitor"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitorcheck"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/sslcheckresult"
)

// MonitorCheck is the model entity for the MonitorCheck schema.
type MonitorCheck struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// MonitorID holds the value of the "monitor_id" field.
	MonitorID uuid.UUID `json:"monitor_id,omitempty"`
	// CheckType holds the value of the "check_type" field.
	CheckType monitorcheck.CheckType `json:"check_type,omitempty"`
	// Status holds the value of the "status" field.
	Status monitorcheck.Status `json:"status,omitempty"`
	// Error holds the value of the "error" field.
	Error *string `json:"error,omitempty"`
	// CheckedAt holds the value of the "checked_at" field.
	CheckedAt time.Time `json:"checked_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MonitorCheckQuery when eager-loading is set.
	Edges        MonitorCheckEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MonitorCheckEdges holds the relations/edges for other nodes in the graph.
type MonitorCheckEdges struct {
	// Monitor holds the value of the monitor edge.
	Monitor *Monitor `json:"monitor,omitempty"`
	// HTTPResult holds the value of the http_result edge.
	HTTPResult *HTTPCheckResult `json:"http_result,omitempty"`
	// SslResult holds the value of the ssl_result edge.
	SslResult *SSLCheckResult `json:"ssl_result,omitempty"`
	// DomainResult holds the value of the domain_result edge.
	DomainResult *DomainCheckResult `json:"domain_result,omitempty"`
	// DNSResult holds the value of the dns_result edge.
	DNSResult *DNSCheckResult `json:"dns_result,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// MonitorOrErr returns the Monitor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MonitorCheckEdges) MonitorOrErr() (*Monitor, error) {
	if e.Monitor != nil {
		return e.Monitor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: monitor.Label}
	}
	return nil, &NotLoadedError{edge: "monitor"}
}

// HTTPResultOrErr returns the HTTPResult value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MonitorCheckEdges) HTTPResultOrErr() (*HTTPCheckResult, error) {
	if e.HTTPResult != nil {
		return e.HTTPResult, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: httpcheckresult.Label}
	}
	return nil, &NotLoadedError{edge: "http_result"}
}

// SslResultOrErr returns the SslResult value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MonitorCheckEdges) SslResultOrErr() (*SSLCheckResult, error) {
	if e.SslResult != nil {
		return e.SslResult, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: sslcheckresult.Label}
	}
	return nil, &NotLoadedError{edge: "ssl_result"}
}

// DomainResultOrErr returns the DomainResult value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MonitorCheckEdges) DomainResultOrErr() (*DomainCheckResult, error) {
	if e.DomainResult != nil {
		return e.DomainResult, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: domaincheckresult.Label}
	}
	return nil, &NotLoadedError{edge: "domain_result"}
}

// DNSResultOrErr returns the DNSResult value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MonitorCheckEdges) DNSResultOrErr() (*DNSCheckResult, error) {
	if e.DNSResult != nil {
		return e.DNSResult, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: dnscheckresult.Label}
	}
	return nil, &NotLoadedError{edge: "dns_result"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*MonitorCheck) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case monitorcheck.FieldCheckType, monitorcheck.FieldStatus, monitorcheck.FieldError:
			values[i] = new(sql.NullString)
		case monitorcheck.FieldCheckedAt:
			values[i] = new(sql.NullTime)
		case monitorcheck.FieldID, monitorcheck.FieldMonitorID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the MonitorCheck fields.
func (mc *MonitorCheck) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case monitorcheck.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				mc.ID = *value
			}
		case monitorcheck.FieldMonitorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field monitor_id", values[i])
			} else if value != nil {
				mc.MonitorID = *value
			}
		case monitorcheck.FieldCheckType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field check_type", values[i])
			} else if value.Valid {
				mc.CheckType = monitorcheck.CheckType(value.String)
			}
		case monitorcheck.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				mc.Status = monitorcheck.Status(value.String)
			}
		case monitorcheck.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				mc.Error = new(string)
				*mc.Error = value.String
			}
		case monitorcheck.FieldCheckedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field checked_at", values[i])
			} else if value.Valid {
				mc.CheckedAt = value.Time
			}
		default:
			mc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the MonitorCheck.
// This includes values selected through modifiers, order, etc.
func (mc *MonitorCheck) Value(name string) (ent.Value, error) {
	return mc.selectValues.Get(name)
}

// QueryMonitor queries the "monitor" edge of the MonitorCheck entity.
func (mc *MonitorCheck) QueryMonitor() *MonitorQuery {
	return NewMonitorCheckClient(mc.config).QueryMonitor(mc)
}

// QueryHTTPResult queries the "http_result" edge of the MonitorCheck entity.
func (mc *MonitorCheck) QueryHTTPResult() *HTTPCheckResultQuery {
	return NewMonitorCheckClient(mc.config).QueryHTTPResult(mc)
}

// QuerySslResult queries the "ssl_result" edge of the MonitorCheck entity.
func (mc *MonitorCheck) QuerySslResult() *SSLCheckResultQuery {
	return NewMonitorCheckClient(mc.config).QuerySslResult(mc)
}

// QueryDomainResult queries the "domain_result" edge of the MonitorCheck entity.
func (mc *MonitorCheck) QueryDomainResult() *DomainCheckResultQuery {
	return NewMonitorCheckClient(mc.config).QueryDomainResult(mc)
}

// QueryDNSResult queries the "dns_result" edge of the MonitorCheck entity.
func (mc *MonitorCheck) QueryDNSResult() *DNSCheckResultQuery {
	return NewMonitorCheckClient(mc.config).QueryDNSResult(mc)
}

// Update returns a builder for updating this MonitorCheck.
// Note that you need to call MonitorCheck.Unwrap() before calling this method if this MonitorCheck
// was returned from a transaction, and the transaction was committed or rolled back.
func (mc *MonitorCheck) Update() *MonitorCheckUpdateOne {
	return NewMonitorCheckClient(mc.config).UpdateOne(mc)
}

// Unwrap unwraps the MonitorCheck entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (mc *MonitorCheck) Unwrap() *MonitorCheck {
	_tx, ok := mc.config.driver.(*txDriver)
	if !ok {
		panic("ent: MonitorCheck is not a transactional entity")
	}
	mc.config.driver = _tx.drv
	return mc
}

// String implements the fmt.Stringer.
func (mc *MonitorCheck) String() string {
	var builder strings.Builder
	builder.WriteString("MonitorCheck(")
	builder.WriteString(fmt.Sprintf("id=%v, ", mc.ID))
	builder.WriteString("monitor_id=")
	builder.WriteString(fmt.Sprintf("%v", mc.MonitorID))
	builder.WriteString(", ")
	builder.WriteString("check_type=")
	builder.WriteString(fmt.Sprintf("%v", mc.CheckType))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", mc.Status))
	builder.WriteString(", ")
	if v := mc.Error; v != nil {
		builder.WriteString("error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("checked_at=")
	builder.WriteString(mc.CheckedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// MonitorChecks is a parsable slice of MonitorCheck.
type MonitorChecks []*MonitorCheck
