// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/notificationchannel"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/tenant"
)

// NotificationChannelCreate is the builder for creating a NotificationChannel entity.
type NotificationChannelCreate struct {
	config
	mutation *NotificationChannelMutation
	hooks    []Hook
}

// SetTenantID sets the "tenant_id" field.
func (ncc *NotificationChannelCreate) SetTenantID(u uuid.UUID) *NotificationChannelCreate {
	ncc.mutation.SetTenantID(u)
	return ncc
}

// SetType sets the "type" field.
func (ncc *NotificationChannelCreate) SetType(n notificationchannel.Type) *NotificationChannelCreate {
	ncc.mutation.SetType(n)
	return ncc
}

// SetConfig sets the "config" field.
func (ncc *NotificationChannelCreate) SetConfig(m map[string]interface{}) *NotificationChannelCreate {
	ncc.mutation.SetConfig(m)
	return ncc
}

// SetCreatedAt sets the "created_at" field.
func (ncc *NotificationChannelCreate) SetCreatedAt(t time.Time) *NotificationChannelCreate {
	ncc.mutation.SetCreatedAt(t)
	return ncc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ncc *NotificationChannelCreate) SetNillableCreatedAt(t *time.Time) *NotificationChannelCreate {
	if t != nil {
		ncc.SetCreatedAt(*t)
	}
	return ncc
}

// SetID sets the "id" field.
func (ncc *NotificationChannelCreate) SetID(u uuid.UUID) *NotificationChannelCreate {
	ncc.mutation.SetID(u)
	return ncc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ncc *NotificationChannelCreate) SetNillableID(u *uuid.UUID) *NotificationChannelCreate {
	if u != nil {
		ncc.SetID(*u)
	}
	return ncc
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (ncc *NotificationChannelCreate) SetTenant(t *Tenant) *NotificationChannelCreate {
	return ncc.SetTenantID(t.ID)
}

// Mutation returns the NotificationChannelMutation object of the builder.
func (ncc *NotificationChannelCreate) Mutation() *NotificationChannelMutation {
	return ncc.mutation
}

// Save creates the NotificationChannel in the database.
func (ncc *NotificationChannelCreate) Save(ctx context.Context) (*NotificationChannel, error) {
	ncc.defaults()
	return withHooks(ctx, ncc.sqlSave, ncc.mutation, ncc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ncc *NotificationChannelCreate) SaveX(ctx context.Context) *NotificationChannel {
	v, err := ncc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ncc *NotificationChannelCreate) Exec(ctx context.Context) error {
	_, err := ncc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ncc *NotificationChannelCreate) ExecX(ctx context.Context) {
	if err := ncc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ncc *NotificationChannelCreate) defaults() {
	if _, ok := ncc.mutation.CreatedAt(); !ok {
		v := notificationchannel.DefaultCreatedAt()
		ncc.mutation.SetCreatedAt(v)
	}
	if _, ok := ncc.mutation.ID(); !ok {
		v := notificationchannel.DefaultID()
		ncc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ncc *NotificationChannelCreate) check() error {
	if _, ok := ncc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "NotificationChannel.tenant_id"`)}
	}
	if _, ok := ncc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "NotificationChannel.type"`)}
	}
	if v, ok := ncc.mutation.GetType(); ok {
		if err := notificationchannel.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "NotificationChannel.type": %w`, err)}
		}
	}
	if _, ok := ncc.mutation.Config(); !ok {
		return &ValidationError{Name: "config", err: errors.New(`ent: missing required field "NotificationChannel.config"`)}
	}
	if _, ok := ncc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "NotificationChannel.created_at"`)}
	}
	if len(ncc.mutation.TenantIDs()) == 0 {
		return &ValidationError{Name: "tenant", err: errors.New(`ent: missing required edge "NotificationChannel.tenant"`)}
	}
	return nil
}

func (ncc *NotificationChannelCreate) sqlSave(ctx context.Context) (*NotificationChannel, error) {
	if err := ncc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ncc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ncc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ncc.mutation.id = &_node.ID
	ncc.mutation.done = true
	return _node, nil
}

func (ncc *NotificationChannelCreate) createSpec() (*NotificationChannel, *sqlgraph.CreateSpec) {
	var (
		_node = &NotificationChannel{config: ncc.config}
		_spec = sqlgraph.NewCreateSpec(notificationchannel.Table, sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeUUID))
	)
	if id, ok := ncc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ncc.mutation.GetType(); ok {
		_spec.SetField(notificationchannel.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := ncc.mutation.Config(); ok {
		_spec.SetField(notificationchannel.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := ncc.mutation.CreatedAt(); ok {
		_spec.SetField(notificationchannel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := ncc.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   notificationchannel.TenantTable,
			Columns: []string{notificationchannel.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TenantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// NotificationChannelCreateBulk is the builder for creating many NotificationChannel entities in bulk.
type NotificationChannelCreateBulk struct {
	config
	err      error
	builders []*NotificationChannelCreate
}

// Save creates the NotificationChannel entities in the database.
func (nccb *NotificationChannelCreateBulk) Save(ctx context.Context) ([]*NotificationChannel, error) {
	if nccb.err != nil {
		return nil, nccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(nccb.builders))
	nodes := make([]*NotificationChannel, len(nccb.builders))
	mutators := make([]Mutator, len(nccb.builders))
	for i := range nccb.builders {
		func(i int, root context.Context) {
			builder := nccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*NotificationChannelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, nccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, nccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, nccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (nccb *NotificationChannelCreateBulk) SaveX(ctx context.Context) []*NotificationChannel {
	v, err := nccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (nccb *NotificationChannelCreateBulk) Exec(ctx context.Context) error {
	_, err := nccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nccb *NotificationChannelCreateBulk) ExecX(ctx context.Context) {
	if err := nccb.Exec(ctx); err != nil {
		panic(err)
	}
}
