// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/pushsubscription"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/tenant"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/user"
)

// PushSubscription is the model entity for the PushSubscription schema.
type PushSubscription struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// TenantID holds the value of the "tenant_id" field.
	TenantID uuid.UUID `json:"tenant_id,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// P256dh holds the value of the "p256dh" field.
	P256dh string `json:"p256dh,omitempty"`
	// Auth holds the value of the "auth" field.
	Auth string `json:"auth,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PushSubscriptionQuery when eager-loading is set.
	Edges        PushSubscriptionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PushSubscriptionEdges holds the relations/edges for other nodes in the graph.
type PushSubscriptionEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Tenant holds the value of the tenant edge.
	Tenant *Tenant `json:"tenant,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PushSubscriptionEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// TenantOrErr returns the Tenant value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PushSubscriptionEdges) TenantOrErr() (*Tenant, error) {
	if e.Tenant != nil {
		return e.Tenant, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: tenant.Label}
	}
	return nil, &NotLoadedError{edge: "tenant"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PushSubscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pushsubscription.FieldEndpoint, pushsubscription.FieldP256dh, pushsubscription.FieldAuth:
			values[i] = new(sql.NullString)
		case pushsubscription.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case pushsubscription.FieldID, pushsubscription.FieldUserID, pushsubscription.FieldTenantID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PushSubscription fields.
func (ps *PushSubscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pushsubscription.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ps.ID = *value
			}
		case pushsubscription.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				ps.UserID = *value
			}
		case pushsubscription.FieldTenantID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value != nil {
				ps.TenantID = *value
			}
		case pushsubscription.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				ps.Endpoint = value.String
			}
		case pushsubscription.FieldP256dh:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field p256dh", values[i])
			} else if value.Valid {
				ps.P256dh = value.String
			}
		case pushsubscription.FieldAuth:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth", values[i])
			} else if value.Valid {
				ps.Auth = value.String
			}
		case pushsubscription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ps.CreatedAt = value.Time
			}
		default:
			ps.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PushSubscription.
// This includes values selected through modifiers, order, etc.
func (ps *PushSubscription) Value(name string) (ent.Value, error) {
	return ps.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PushSubscription entity.
func (ps *PushSubscription) QueryUser() *UserQuery {
	return NewPushSubscriptionClient(ps.config).QueryUser(ps)
}

// QueryTenant queries the "tenant" edge of the PushSubscription entity.
func (ps *PushSubscription) QueryTenant() *TenantQuery {
	return NewPushSubscriptionClient(ps.config).QueryTenant(ps)
}

// Update returns a builder for updating this PushSubscription.
// Note that you need to call PushSubscription.Unwrap() before calling this method if this PushSubscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (ps *PushSubscription) Update() *PushSubscriptionUpdateOne {
	return NewPushSubscriptionClient(ps.config).UpdateOne(ps)
}

// Unwrap unwraps the PushSubscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ps *PushSubscription) Unwrap() *PushSubscription {
	_tx, ok := ps.config.driver.(*txDriver)
	if !ok {
		panic("ent: PushSubscription is not a transactional entity")
	}
	ps.config.driver = _tx.drv
	return ps
}

// String implements the fmt.Stringer.
func (ps *PushSubscription) String() string {
	var builder strings.Builder
	builder.WriteString("PushSubscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ps.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ps.UserID))
	builder.WriteString(", ")
	builder.WriteString("tenant_id=")
	builder.WriteString(fmt.Sprintf("%v", ps.TenantID))
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(ps.Endpoint)
	builder.WriteString(", ")
	builder.WriteString("p256dh=")
	builder.WriteString(ps.P256dh)
	builder.WriteString(", ")
	builder.WriteString("auth=")
	builder.WriteString(ps.Auth)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ps.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PushSubscriptions is a parsable slice of PushSubscription.
type PushSubscriptions []*PushSubscription
