// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/alert"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/alertevent"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/dnscheckresult"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/domaincheckresult"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/httpcheckresult"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/invite"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/membership"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitor"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitorcheck"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitorcheckconfig"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/notificationchannel"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/pushsubscription"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/schema"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/sslcheckresult"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/tenant"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/tenantsetting"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	alertFields := schema.Alert{}.Fields()
	_ = alertFields
	// alertDescThreshold is the schema descriptor for threshold field.
	alertDescThreshold := alertFields[4].Descriptor()
	// alert.DefaultThreshold holds the default value on creation for the threshold field.
	alert.DefaultThreshold = alertDescThreshold.Default.(int)
	// alertDescCreatedAt is the schema descriptor for created_at field.
	alertDescCreatedAt := alertFields[5].Descriptor()
	// alert.DefaultCreatedAt holds the default value on creation for the created_at field.
	alert.DefaultCreatedAt = alertDescCreatedAt.Default.(func() time.Time)
	// alertDescID is the schema descriptor for id field.
	alertDescID := alertFields[0].Descriptor()
	// alert.DefaultID holds the default value on creation for the id field.
	alert.DefaultID = alertDescID.Default.(func() uuid.UUID)
	alerteventFields := schema.AlertEvent{}.Fields()
	_ = alerteventFields
	// alerteventDescCreatedAt is the schema descriptor for created_at field.
	alerteventDescCreatedAt := alerteventFields[7].Descriptor()
	// alertevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	alertevent.DefaultCreatedAt = alerteventDescCreatedAt.Default.(func() time.Time)
	// alerteventDescID is the schema descriptor for id field.
	alerteventDescID := alerteventFields[0].Descriptor()
	// alertevent.DefaultID holds the default value on creation for the id field.
	alertevent.DefaultID = alerteventDescID.Default.(func() uuid.UUID)
	dnscheckresultFields := schema.DNSCheckResult{}.Fields()
	_ = dnscheckresultFields
	// dnscheckresultDescID is the schema descriptor for id field.
	dnscheckresultDescID := dnscheckresultFields[0].Descriptor()
	// dnscheckresult.DefaultID holds the default value on creation for the id field.
	dnscheckresult.DefaultID = dnscheckresultDescID.Default.(func() uuid.UUID)
	domaincheckresultFields := schema.DomainCheckResult{}.Fields()
	_ = domaincheckresultFields
	// domaincheckresultDescID is the schema descriptor for id field.
	domaincheckresultDescID := domaincheckresultFields[0].Descriptor()
	// domaincheckresult.DefaultID holds the default value on creation for the id field.
	domaincheckresult.DefaultID = domaincheckresultDescID.Default.(func() uuid.UUID)
	httpcheckresultFields := schema.HTTPCheckResult{}.Fields()
	_ = httpcheckresultFields
	// httpcheckresultDescID is the schema descriptor for id field.
	httpcheckresultDescID := httpcheckresultFields[0].Descriptor()
	// httpcheckresult.DefaultID holds the default value on creation for the id field.
	httpcheckresult.DefaultID = httpcheckresultDescID.Default.(func() uuid.UUID)
	inviteFields := schema.Invite{}.Fields()
	_ = inviteFields
	// inviteDescEmail is the schema descriptor for email field.
	inviteDescEmail := inviteFields[2].Descriptor()
	// invite.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	invite.EmailValidator = inviteDescEmail.Validators[0].(func(string) error)
	// inviteDescToken is the schema descriptor for token field.
	inviteDescToken := inviteFields[4].Descriptor()
	// invite.TokenValidator is a validator for the "token" field. It is called by the builders before save.
	invite.TokenValidator = inviteDescToken.Validators[0].(func(string) error)
	// inviteDescCreatedAt is the schema descriptor for created_at field.
	inviteDescCreatedAt := inviteFields[7].Descriptor()
	// invite.DefaultCreatedAt holds the default value on creation for the created_at field.
	invite.DefaultCreatedAt = inviteDescCreatedAt.Default.(func() time.Time)
	// inviteDescID is the schema descriptor for id field.
	inviteDescID := inviteFields[0].Descriptor()
	// invite.DefaultID holds the default value on creation for the id field.
	invite.DefaultID = inviteDescID.Default.(func() uuid.UUID)
	membershipFields := schema.Membership{}.Fields()
	_ = membershipFields
	// membershipDescCreatedAt is the schema descriptor for created_at field.
	membershipDescCreatedAt := membershipFields[4].Descriptor()
	// membership.DefaultCreatedAt holds the default value on creation for the created_at field.
	membership.DefaultCreatedAt = membershipDescCreatedAt.Default.(func() time.Time)
	// membershipDescID is the schema descriptor for id field.
	membershipDescID := membershipFields[0].Descriptor()
	// membership.DefaultID holds the default value on creation for the id field.
	membership.DefaultID = membershipDescID.Default.(func() uuid.UUID)
	monitorFields := schema.Monitor{}.Fields()
	_ = monitorFields
	// monitorDescName is the schema descriptor for name field.
	monitorDescName := monitorFields[2].Descriptor()
	// monitor.NameValidator is a validator for the "name" field. It is called by the builders before save.
	monitor.NameValidator = monitorDescName.Validators[0].(func(string) error)
	// monitorDescURL is the schema descriptor for url field.
	monitorDescURL := monitorFields[3].Descriptor()
	// monitor.URLValidator is a validator for the "url" field. It is called by the builders before save.
	monitor.URLValidator = monitorDescURL.Validators[0].(func(string) error)
	// monitorDescDomain is the schema descriptor for domain field.
	monitorDescDomain := monitorFields[4].Descriptor()
	// monitor.DomainValidator is a validator for the "domain" field. It is called by the builders before save.
	monitor.DomainValidator = monitorDescDomain.Validators[0].(func(string) error)
	// monitorDescIntervalSeconds is the schema descriptor for interval_seconds field.
	monitorDescIntervalSeconds := monitorFields[7].Descriptor()
	// monitor.DefaultIntervalSeconds holds the default value on creation for the interval_seconds field.
	monitor.DefaultIntervalSeconds = monitorDescIntervalSeconds.Default.(int)
	// monitorDescTimeoutSeconds is the schema descriptor for timeout_seconds field.
	monitorDescTimeoutSeconds := monitorFields[8].Descriptor()
	// monitor.DefaultTimeoutSeconds holds the default value on creation for the timeout_seconds field.
	monitor.DefaultTimeoutSeconds = monitorDescTimeoutSeconds.Default.(int)
	// monitorDescIsActive is the schema descriptor for is_active field.
	monitorDescIsActive := monitorFields[9].Descriptor()
	// monitor.DefaultIsActive holds the default value on creation for the is_active field.
	monitor.DefaultIsActive = monitorDescIsActive.Default.(bool)
	// monitorDescCreatedAt is the schema descriptor for created_at field.
	monitorDescCreatedAt := monitorFields[13].Descriptor()
	// monitor.DefaultCreatedAt holds the default value on creation for the created_at field.
	monitor.DefaultCreatedAt = monitorDescCreatedAt.Default.(func() time.Time)
	// monitorDescID is the schema descriptor for id field.
	monitorDescID := monitorFields[0].Descriptor()
	// monitor.DefaultID holds the default value on creation for the id field.
	monitor.DefaultID = monitorDescID.Default.(func() uuid.UUID)
	monitorcheckFields := schema.MonitorCheck{}.Fields()
	_ = monitorcheckFields
	// monitorcheckDescCheckedAt is the schema descriptor for checked_at field.
	monitorcheckDescCheckedAt := monitorcheckFields[5].Descriptor()
	// monitorcheck.DefaultCheckedAt holds the default value on creation for the checked_at field.
	monitorcheck.DefaultCheckedAt = monitorcheckDescCheckedAt.Default.(func() time.Time)
	// monitorcheckDescID is the schema descriptor for id field.
	monitorcheckDescID := monitorcheckFields[0].Descriptor()
	// monitorcheck.DefaultID holds the default value on creation for the id field.
	monitorcheck.DefaultID = monitorcheckDescID.Default.(func() uuid.UUID)
	monitorcheckconfigFields := schema.MonitorCheckConfig{}.Fields()
	_ = monitorcheckconfigFields
	// monitorcheckconfigDescIntervalSeconds is the schema descriptor for interval_seconds field.
	monitorcheckconfigDescIntervalSeconds := monitorcheckconfigFields[3].Descriptor()
	// monitorcheckconfig.IntervalSecondsValidator is a validator for the "interval_seconds" field. It is called by the builders before save.
	monitorcheckconfig.IntervalSecondsValidator = monitorcheckconfigDescIntervalSeconds.Validators[0].(func(int) error)
	// monitorcheckconfigDescTimeoutSeconds is the schema descriptor for timeout_seconds field.
	monitorcheckconfigDescTimeoutSeconds := monitorcheckconfigFields[4].Descriptor()
	// monitorcheckconfig.DefaultTimeoutSeconds holds the default value on creation for the timeout_seconds field.
	monitorcheckconfig.DefaultTimeoutSeconds = monitorcheckconfigDescTimeoutSeconds.Default.(int)
	// monitorcheckconfigDescIsEnabled is the schema descriptor for is_enabled field.
	monitorcheckconfigDescIsEnabled := monitorcheckconfigFields[5].Descriptor()
	// monitorcheckconfig.DefaultIsEnabled holds the default value on creation for the is_enabled field.
	monitorcheckconfig.DefaultIsEnabled = monitorcheckconfigDescIsEnabled.Default.(bool)
	// monitorcheckconfigDescNextCheckAt is the schema descriptor for next_check_at field.
	monitorcheckconfigDescNextCheckAt := monitorcheckconfigFields[7].Descriptor()
	// monitorcheckconfig.DefaultNextCheckAt holds the default value on creation for the next_check_at field.
	monitorcheckconfig.DefaultNextCheckAt = monitorcheckconfigDescNextCheckAt.Default.(func() time.Time)
	// monitorcheckconfigDescCreatedAt is the schema descriptor for created_at field.
	monitorcheckconfigDescCreatedAt := monitorcheckconfigFields[8].Descriptor()
	// monitorcheckconfig.DefaultCreatedAt holds the default value on creation for the created_at field.
	monitorcheckconfig.DefaultCreatedAt = monitorcheckconfigDescCreatedAt.Default.(func() time.Time)
	// monitorcheckconfigDescID is the schema descriptor for id field.
	monitorcheckconfigDescID := monitorcheckconfigFields[0].Descriptor()
	// monitorcheckconfig.DefaultID holds the default value on creation for the id field.
	monitorcheckconfig.DefaultID = monitorcheckconfigDescID.Default.(func() uuid.UUID)
	notificationchannelFields := schema.NotificationChannel{}.Fields()
	_ = notificationchannelFields
	// notificationchannelDescCreatedAt is the schema descriptor for created_at field.
	notificationchannelDescCreatedAt := notificationchannelFields[4].Descriptor()
	// notificationchannel.DefaultCreatedAt holds the default value on creation for the created_at field.
	notificationchannel.DefaultCreatedAt = notificationchannelDescCreatedAt.Default.(func() time.Time)
	// notificationchannelDescID is the schema descriptor for id field.
	notificationchannelDescID := notificationchannelFields[0].Descriptor()
	// notificationchannel.DefaultID holds the default value on creation for the id field.
	notificationchannel.DefaultID = notificationchannelDescID.Default.(func() uuid.UUID)
	pushsubscriptionFields := schema.PushSubscription{}.Fields()
	_ = pushsubscriptionFields
	// pushsubscriptionDescEndpoint is the schema descriptor for endpoint field.
	pushsubscriptionDescEndpoint := pushsubscriptionFields[3].Descriptor()
	// pushsubscription.EndpointValidator is a validator for the "endpoint" field. It is called by the builders before save.
	pushsubscription.EndpointValidator = pushsubscriptionDescEndpoint.Validators[0].(func(string) error)
	// pushsubscriptionDescP256dh is the schema descriptor for p256dh field.
	pushsubscriptionDescP256dh := pushsubscriptionFields[4].Descriptor()
	// pushsubscription.P256dhValidator is a validator for the "p256dh" field. It is called by the builders before save.
	pushsubscription.P256dhValidator = pushsubscriptionDescP256dh.Validators[0].(func(string) error)
	// pushsubscriptionDescAuth is the schema descriptor for auth field.
	pushsubscriptionDescAuth := pushsubscriptionFields[5].Descriptor()
	// pushsubscription.AuthValidator is a validator for the "auth" field. It is called by the builders before save.
	pushsubscription.AuthValidator = pushsubscriptionDescAuth.Validators[0].(func(string) error)
	// pushsubscriptionDescCreatedAt is the schema descriptor for created_at field.
	pushsubscriptionDescCreatedAt := pushsubscriptionFields[6].Descriptor()
	// pushsubscription.DefaultCreatedAt holds the default value on creation for the created_at field.
	pushsubscription.DefaultCreatedAt = pushsubscriptionDescCreatedAt.Default.(func() time.Time)
	// pushsubscriptionDescID is the schema descriptor for id field.
	pushsubscriptionDescID := pushsubscriptionFields[0].Descriptor()
	// pushsubscription.DefaultID holds the default value on creation for the id field.
	pushsubscription.DefaultID = pushsubscriptionDescID.Default.(func() uuid.UUID)
	sslcheckresultFields := schema.SSLCheckResult{}.Fields()
	_ = sslcheckresultFields
	// sslcheckresultDescID is the schema descriptor for id field.
	sslcheckresultDescID := sslcheckresultFields[0].Descriptor()
	// sslcheckresult.DefaultID holds the default value on creation for the id field.
	sslcheckresult.DefaultID = sslcheckresultDescID.Default.(func() uuid.UUID)
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescName is the schema descriptor for name field.
	tenantDescName := tenantFields[1].Descriptor()
	// tenant.NameValidator is a validator for the "name" field. It is called by the builders before save.
	tenant.NameValidator = tenantDescName.Validators[0].(func(string) error)
	// tenantDescPlan is the schema descriptor for plan field.
	tenantDescPlan := tenantFields[2].Descriptor()
	// tenant.DefaultPlan holds the default value on creation for the plan field.
	tenant.DefaultPlan = tenantDescPlan.Default.(string)
	// tenantDescCreatedAt is the schema descriptor for created_at field.
	tenantDescCreatedAt := tenantFields[3].Descriptor()
	// tenant.DefaultCreatedAt holds the default value on creation for the created_at field.
	tenant.DefaultCreatedAt = tenantDescCreatedAt.Default.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
	tenantsettingFields := schema.TenantSetting{}.Fields()
	_ = tenantsettingFields
	// tenantsettingDescHTTPIntervalSeconds is the schema descriptor for http_interval_seconds field.
	tenantsettingDescHTTPIntervalSeconds := tenantsettingFields[2].Descriptor()
	// tenantsetting.DefaultHTTPIntervalSeconds holds the default value on creation for the http_interval_seconds field.
	tenantsetting.DefaultHTTPIntervalSeconds = tenantsettingDescHTTPIntervalSeconds.Default.(int)
	// tenantsettingDescDNSIntervalSeconds is the schema descriptor for dns_interval_seconds field.
	tenantsettingDescDNSIntervalSeconds := tenantsettingFields[3].Descriptor()
	// tenantsetting.DefaultDNSIntervalSeconds holds the default value on creation for the dns_interval_seconds field.
	tenantsetting.DefaultDNSIntervalSeconds = tenantsettingDescDNSIntervalSeconds.Default.(int)
	// tenantsettingDescSslIntervalSeconds is the schema descriptor for ssl_interval_seconds field.
	tenantsettingDescSslIntervalSeconds := tenantsettingFields[4].Descriptor()
	// tenantsetting.DefaultSslIntervalSeconds holds the default value on creation for the ssl_interval_seconds field.
	tenantsetting.DefaultSslIntervalSeconds = tenantsettingDescSslIntervalSeconds.Default.(int)
	// tenantsettingDescDomainIntervalSeconds is the schema descriptor for domain_interval_seconds field.
	tenantsettingDescDomainIntervalSeconds := tenantsettingFields[5].Descriptor()
	// tenantsetting.DefaultDomainIntervalSeconds holds the default value on creation for the domain_interval_seconds field.
	tenantsetting.DefaultDomainIntervalSeconds = tenantsettingDescDomainIntervalSeconds.Default.(int)
	// tenantsettingDescEmailAuthIntervalSeconds is the schema descriptor for email_auth_interval_seconds field.
	tenantsettingDescEmailAuthIntervalSeconds := tenantsettingFields[6].Descriptor()
	// tenantsetting.DefaultEmailAuthIntervalSeconds holds the default value on creation for the email_auth_interval_seconds field.
	tenantsetting.DefaultEmailAuthIntervalSeconds = tenantsettingDescEmailAuthIntervalSeconds.Default.(int)
	// tenantsettingDescSslMinExpiryDays is the schema descriptor for ssl_min_expiry_days field.
	tenantsettingDescSslMinExpiryDays := tenantsettingFields[7].Descriptor()
	// tenantsetting.DefaultSslMinExpiryDays holds the default value on creation for the ssl_min_expiry_days field.
	tenantsetting.DefaultSslMinExpiryDays = tenantsettingDescSslMinExpiryDays.Default.(int)
	// tenantsettingDescDomainMinExpiryDays is the schema descriptor for domain_min_expiry_days field.
	tenantsettingDescDomainMinExpiryDays := tenantsettingFields[8].Descriptor()
	// tenantsetting.DefaultDomainMinExpiryDays holds the default value on creation for the domain_min_expiry_days field.
	tenantsetting.DefaultDomainMinExpiryDays = tenantsettingDescDomainMinExpiryDays.Default.(int)
	// tenantsettingDescUpdatedAt is the schema descriptor for updated_at field.
	tenantsettingDescUpdatedAt := tenantsettingFields[9].Descriptor()
	// tenantsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	tenantsetting.DefaultUpdatedAt = tenantsettingDescUpdatedAt.Default.(func() time.Time)
	// tenantsettingDescID is the schema descriptor for id field.
	tenantsettingDescID := tenantsettingFields[0].Descriptor()
	// tenantsetting.DefaultID holds the default value on creation for the id field.
	tenantsetting.DefaultID = tenantsettingDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
