// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitorcheck"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/predicate"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/sslcheckresult"
)

// SSLCheckResultQuery is the builder for querying SSLCheckResult entities.
type SSLCheckResultQuery struct {
	config
	ctx        *QueryContext
	order      []sslcheckresult.OrderOption
	inters     []Interceptor
	predicates []predicate.SSLCheckResult
	withCheck  *MonitorCheckQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SSLCheckResultQuery builder.
func (scrq *SSLCheckResultQuery) Where(ps ...predicate.SSLCheckResult) *SSLCheckResultQuery {
	scrq.predicates = append(scrq.predicates, ps...)
	return scrq
}

// Limit the number of records to be returned by this query.
func (scrq *SSLCheckResultQuery) Limit(limit int) *SSLCheckResultQuery {
	scrq.ctx.Limit = &limit
	return scrq
}

// Offset to start from.
func (scrq *SSLCheckResultQuery) Offset(offset int) *SSLCheckResultQuery {
	scrq.ctx.Offset = &offset
	return scrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (scrq *SSLCheckResultQuery) Unique(unique bool) *SSLCheckResultQuery {
	scrq.ctx.Unique = &unique
	return scrq
}

// Order specifies how the records should be ordered.
func (scrq *SSLCheckResultQuery) Order(o ...sslcheckresult.OrderOption) *SSLCheckResultQuery {
	scrq.order = append(scrq.order, o...)
	return scrq
}

// QueryCheck chains the current query on the "check" edge.
func (scrq *SSLCheckResultQuery) QueryCheck() *MonitorCheckQuery {
	query := (&MonitorCheckClient{config: scrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := scrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := scrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(sslcheckresult.Table, sslcheckresult.FieldID, selector),
			sqlgraph.To(monitorcheck.Table, monitorcheck.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, sslcheckresult.CheckTable, sslcheckresult.CheckColumn),
		)
		fromU = sqlgraph.SetNeighbors(scrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first SSLCheckResult entity from the query.
// Returns a *NotFoundError when no SSLCheckResult was found.
func (scrq *SSLCheckResultQuery) First(ctx context.Context) (*SSLCheckResult, error) {
	nodes, err := scrq.Limit(1).All(setContextOp(ctx, scrq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{sslcheckresult.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (scrq *SSLCheckResultQuery) FirstX(ctx context.Context) *SSLCheckResult {
	node, err := scrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SSLCheckResult ID from the query.
// Returns a *NotFoundError when no SSLCheckResult ID was found.
func (scrq *SSLCheckResultQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = scrq.Limit(1).IDs(setContextOp(ctx, scrq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{sslcheckresult.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (scrq *SSLCheckResultQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := scrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SSLCheckResult entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SSLCheckResult entity is found.
// Returns a *NotFoundError when no SSLCheckResult entities are found.
func (scrq *SSLCheckResultQuery) Only(ctx context.Context) (*SSLCheckResult, error) {
	nodes, err := scrq.Limit(2).All(setContextOp(ctx, scrq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{sslcheckresult.Label}
	default:
		return nil, &NotSingularError{sslcheckresult.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (scrq *SSLCheckResultQuery) OnlyX(ctx context.Context) *SSLCheckResult {
	node, err := scrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SSLCheckResult ID in the query.
// Returns a *NotSingularError when more than one SSLCheckResult ID is found.
// Returns a *NotFoundError when no entities are found.
func (scrq *SSLCheckResultQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = scrq.Limit(2).IDs(setContextOp(ctx, scrq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{sslcheckresult.Label}
	default:
		err = &NotSingularError{sslcheckresult.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (scrq *SSLCheckResultQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := scrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SSLCheckResults.
func (scrq *SSLCheckResultQuery) All(ctx context.Context) ([]*SSLCheckResult, error) {
	ctx = setContextOp(ctx, scrq.ctx, ent.OpQueryAll)
	if err := scrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SSLCheckResult, *SSLCheckResultQuery]()
	return withInterceptors[[]*SSLCheckResult](ctx, scrq, qr, scrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (scrq *SSLCheckResultQuery) AllX(ctx context.Context) []*SSLCheckResult {
	nodes, err := scrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SSLCheckResult IDs.
func (scrq *SSLCheckResultQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if scrq.ctx.Unique == nil && scrq.path != nil {
		scrq.Unique(true)
	}
	ctx = setContextOp(ctx, scrq.ctx, ent.OpQueryIDs)
	if err = scrq.Select(sslcheckresult.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (scrq *SSLCheckResultQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := scrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (scrq *SSLCheckResultQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, scrq.ctx, ent.OpQueryCount)
	if err := scrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, scrq, querierCount[*SSLCheckResultQuery](), scrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (scrq *SSLCheckResultQuery) CountX(ctx context.Context) int {
	count, err := scrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (scrq *SSLCheckResultQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, scrq.ctx, ent.OpQueryExist)
	switch _, err := scrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (scrq *SSLCheckResultQuery) ExistX(ctx context.Context) bool {
	exist, err := scrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SSLCheckResultQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (scrq *SSLCheckResultQuery) Clone() *SSLCheckResultQuery {
	if scrq == nil {
		return nil
	}
	return &SSLCheckResultQuery{
		config:     scrq.config,
		ctx:        scrq.ctx.Clone(),
		order:      append([]sslcheckresult.OrderOption{}, scrq.order...),
		inters:     append([]Interceptor{}, scrq.inters...),
		predicates: append([]predicate.SSLCheckResult{}, scrq.predicates...),
		withCheck:  scrq.withCheck.Clone(),
		// clone intermediate query.
		sql:  scrq.sql.Clone(),
		path: scrq.path,
	}
}

// WithCheck tells the query-builder to eager-load the nodes that are connected to
// the "check" edge. The optional arguments are used to configure the query builder of the edge.
func (scrq *SSLCheckResultQuery) WithCheck(opts ...func(*MonitorCheckQuery)) *SSLCheckResultQuery {
	query := (&MonitorCheckClient{config: scrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	scrq.withCheck = query
	return scrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CheckID uuid.UUID `json:"check_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SSLCheckResult.Query().
//		GroupBy(sslcheckresult.FieldCheckID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (scrq *SSLCheckResultQuery) GroupBy(field string, fields ...string) *SSLCheckResultGroupBy {
	scrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SSLCheckResultGroupBy{build: scrq}
	grbuild.flds = &scrq.ctx.Fields
	grbuild.label = sslcheckresult.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CheckID uuid.UUID `json:"check_id,omitempty"`
//	}
//
//	client.SSLCheckResult.Query().
//		Select(sslcheckresult.FieldCheckID).
//		Scan(ctx, &v)
func (scrq *SSLCheckResultQuery) Select(fields ...string) *SSLCheckResultSelect {
	scrq.ctx.Fields = append(scrq.ctx.Fields, fields...)
	sbuild := &SSLCheckResultSelect{SSLCheckResultQuery: scrq}
	sbuild.label = sslcheckresult.Label
	sbuild.flds, sbuild.scan = &scrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SSLCheckResultSelect configured with the given aggregations.
func (scrq *SSLCheckResultQuery) Aggregate(fns ...AggregateFunc) *SSLCheckResultSelect {
	return scrq.Select().Aggregate(fns...)
}

func (scrq *SSLCheckResultQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range scrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, scrq); err != nil {
				return err
			}
		}
	}
	for _, f := range scrq.ctx.Fields {
		if !sslcheckresult.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if scrq.path != nil {
		prev, err := scrq.path(ctx)
		if err != nil {
			return err
		}
		scrq.sql = prev
	}
	return nil
}

func (scrq *SSLCheckResultQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SSLCheckResult, error) {
	var (
		nodes       = []*SSLCheckResult{}
		_spec       = scrq.querySpec()
		loadedTypes = [1]bool{
			scrq.withCheck != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SSLCheckResult).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SSLCheckResult{config: scrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, scrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := scrq.withCheck; query != nil {
		if err := scrq.loadCheck(ctx, query, nodes, nil,
			func(n *SSLCheckResult, e *MonitorCheck) { n.Edges.Check = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (scrq *SSLCheckResultQuery) loadCheck(ctx context.Context, query *MonitorCheckQuery, nodes []*SSLCheckResult, init func(*SSLCheckResult), assign func(*SSLCheckResult, *MonitorCheck)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*SSLCheckResult)
	for i := range nodes {
		fk := nodes[i].CheckID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(monitorcheck.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "check_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (scrq *SSLCheckResultQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := scrq.querySpec()
	_spec.Node.Columns = scrq.ctx.Fields
	if len(scrq.ctx.Fields) > 0 {
		_spec.Unique = scrq.ctx.Unique != nil && *scrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, scrq.driver, _spec)
}

func (scrq *SSLCheckResultQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(sslcheckresult.Table, sslcheckresult.Columns, sqlgraph.NewFieldSpec(sslcheckresult.FieldID, field.TypeUUID))
	_spec.From = scrq.sql
	if unique := scrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if scrq.path != nil {
		_spec.Unique = true
	}
	if fields := scrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sslcheckresult.FieldID)
		for i := range fields {
			if fields[i] != sslcheckresult.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if scrq.withCheck != nil {
			_spec.Node.AddColumnOnce(sslcheckresult.FieldCheckID)
		}
	}
	if ps := scrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := scrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := scrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := scrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (scrq *SSLCheckResultQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(scrq.driver.Dialect())
	t1 := builder.Table(sslcheckresult.Table)
	columns := scrq.ctx.Fields
	if len(columns) == 0 {
		columns = sslcheckresult.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if scrq.sql != nil {
		selector = scrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if scrq.ctx.Unique != nil && *scrq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range scrq.predicates {
		p(selector)
	}
	for _, p := range scrq.order {
		p(selector)
	}
	if offset := scrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := scrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SSLCheckResultGroupBy is the group-by builder for SSLCheckResult entities.
type SSLCheckResultGroupBy struct {
	selector
	build *SSLCheckResultQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (scrgb *SSLCheckResultGroupBy) Aggregate(fns ...AggregateFunc) *SSLCheckResultGroupBy {
	scrgb.fns = append(scrgb.fns, fns...)
	return scrgb
}

// Scan applies the selector query and scans the result into the given value.
func (scrgb *SSLCheckResultGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scrgb.build.ctx, ent.OpQueryGroupBy)
	if err := scrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SSLCheckResultQuery, *SSLCheckResultGroupBy](ctx, scrgb.build, scrgb, scrgb.build.inters, v)
}

func (scrgb *SSLCheckResultGroupBy) sqlScan(ctx context.Context, root *SSLCheckResultQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(scrgb.fns))
	for _, fn := range scrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*scrgb.flds)+len(scrgb.fns))
		for _, f := range *scrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*scrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SSLCheckResultSelect is the builder for selecting fields of SSLCheckResult entities.
type SSLCheckResultSelect struct {
	*SSLCheckResultQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (scrs *SSLCheckResultSelect) Aggregate(fns ...AggregateFunc) *SSLCheckResultSelect {
	scrs.fns = append(scrs.fns, fns...)
	return scrs
}

// Scan applies the selector query and scans the result into the given value.
func (scrs *SSLCheckResultSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, scrs.ctx, ent.OpQuerySelect)
	if err := scrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SSLCheckResultQuery, *SSLCheckResultSelect](ctx, scrs.SSLCheckResultQuery, scrs, scrs.inters, v)
}

func (scrs *SSLCheckResultSelect) sqlScan(ctx context.Context, root *SSLCheckResultQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(scrs.fns))
	for _, fn := range scrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*scrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := scrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
