// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/predicate"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/sslcheckresult"
)

// SSLCheckResultDelete is the builder for deleting a SSLCheckResult entity.
type SSLCheckResultDelete struct {
	config
	hooks    []Hook
	mutation *SSLCheckResultMutation
}

// Where appends a list predicates to the SSLCheckResultDelete builder.
func (scrd *SSLCheckResultDelete) Where(ps ...predicate.SSLCheckResult) *SSLCheckResultDelete {
	scrd.mutation.Where(ps...)
	return scrd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (scrd *SSLCheckResultDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, scrd.sqlExec, scrd.mutation, scrd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (scrd *SSLCheckResultDelete) ExecX(ctx context.Context) int {
	n, err := scrd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (scrd *SSLCheckResultDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(sslcheckresult.Table, sqlgraph.NewFieldSpec(sslcheckresult.FieldID, field.TypeUUID))
	if ps := scrd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, scrd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	scrd.mutation.done = true
	return affected, err
}

// SSLCheckResultDeleteOne is the builder for deleting a single SSLCheckResult entity.
type SSLCheckResultDeleteOne struct {
	scrd *SSLCheckResultDelete
}

// Where appends a list predicates to the SSLCheckResultDelete builder.
func (scrdo *SSLCheckResultDeleteOne) Where(ps ...predicate.SSLCheckResult) *SSLCheckResultDeleteOne {
	scrdo.scrd.mutation.Where(ps...)
	return scrdo
}

// Exec executes the deletion query.
func (scrdo *SSLCheckResultDeleteOne) Exec(ctx context.Context) error {
	n, err := scrdo.scrd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{sslcheckresult.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (scrdo *SSLCheckResultDeleteOne) ExecX(ctx context.Context) {
	if err := scrdo.Exec(ctx); err != nil {
		panic(err)
	}
}
