// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/predicate"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/tenant"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/tenantsetting"
)

// TenantSettingUpdate is the builder for updating TenantSetting entities.
type TenantSettingUpdate struct {
	config
	hooks    []Hook
	mutation *TenantSettingMutation
}

// Where appends a list predicates to the TenantSettingUpdate builder.
func (tsu *TenantSettingUpdate) Where(ps ...predicate.TenantSetting) *TenantSettingUpdate {
	tsu.mutation.Where(ps...)
	return tsu
}

// SetTenantID sets the "tenant_id" field.
func (tsu *TenantSettingUpdate) SetTenantID(u uuid.UUID) *TenantSettingUpdate {
	tsu.mutation.SetTenantID(u)
	return tsu
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (tsu *TenantSettingUpdate) SetNillableTenantID(u *uuid.UUID) *TenantSettingUpdate {
	if u != nil {
		tsu.SetTenantID(*u)
	}
	return tsu
}

// SetHTTPIntervalSeconds sets the "http_interval_seconds" field.
func (tsu *TenantSettingUpdate) SetHTTPIntervalSeconds(i int) *TenantSettingUpdate {
	tsu.mutation.ResetHTTPIntervalSeconds()
	tsu.mutation.SetHTTPIntervalSeconds(i)
	return tsu
}

// SetNillableHTTPIntervalSeconds sets the "http_interval_seconds" field if the given value is not nil.
func (tsu *TenantSettingUpdate) SetNillableHTTPIntervalSeconds(i *int) *TenantSettingUpdate {
	if i != nil {
		tsu.SetHTTPIntervalSeconds(*i)
	}
	return tsu
}

// AddHTTPIntervalSeconds adds i to the "http_interval_seconds" field.
func (tsu *TenantSettingUpdate) AddHTTPIntervalSeconds(i int) *TenantSettingUpdate {
	tsu.mutation.AddHTTPIntervalSeconds(i)
	return tsu
}

// SetDNSIntervalSeconds sets the "dns_interval_seconds" field.
func (tsu *TenantSettingUpdate) SetDNSIntervalSeconds(i int) *TenantSettingUpdate {
	tsu.mutation.ResetDNSIntervalSeconds()
	tsu.mutation.SetDNSIntervalSeconds(i)
	return tsu
}

// SetNillableDNSIntervalSeconds sets the "dns_interval_seconds" field if the given value is not nil.
func (tsu *TenantSettingUpdate) SetNillableDNSIntervalSeconds(i *int) *TenantSettingUpdate {
	if i != nil {
		tsu.SetDNSIntervalSeconds(*i)
	}
	return tsu
}

// AddDNSIntervalSeconds adds i to the "dns_interval_seconds" field.
func (tsu *TenantSettingUpdate) AddDNSIntervalSeconds(i int) *TenantSettingUpdate {
	tsu.mutation.AddDNSIntervalSeconds(i)
	return tsu
}

// SetSslIntervalSeconds sets the "ssl_interval_seconds" field.
func (tsu *TenantSettingUpdate) SetSslIntervalSeconds(i int) *TenantSettingUpdate {
	tsu.mutation.ResetSslIntervalSeconds()
	tsu.mutation.SetSslIntervalSeconds(i)
	return tsu
}

// SetNillableSslIntervalSeconds sets the "ssl_interval_seconds" field if the given value is not nil.
func (tsu *TenantSettingUpdate) SetNillableSslIntervalSeconds(i *int) *TenantSettingUpdate {
	if i != nil {
		tsu.SetSslIntervalSeconds(*i)
	}
	return tsu
}

// AddSslIntervalSeconds adds i to the "ssl_interval_seconds" field.
func (tsu *TenantSettingUpdate) AddSslIntervalSeconds(i int) *TenantSettingUpdate {
	tsu.mutation.AddSslIntervalSeconds(i)
	return tsu
}

// SetDomainIntervalSeconds sets the "domain_interval_seconds" field.
func (tsu *TenantSettingUpdate) SetDomainIntervalSeconds(i int) *TenantSettingUpdate {
	tsu.mutation.ResetDomainIntervalSeconds()
	tsu.mutation.SetDomainIntervalSeconds(i)
	return tsu
}

// SetNillableDomainIntervalSeconds sets the "domain_interval_seconds" field if the given value is not nil.
func (tsu *TenantSettingUpdate) SetNillableDomainIntervalSeconds(i *int) *TenantSettingUpdate {
	if i != nil {
		tsu.SetDomainIntervalSeconds(*i)
	}
	return tsu
}

// AddDomainIntervalSeconds adds i to the "domain_interval_seconds" field.
func (tsu *TenantSettingUpdate) AddDomainIntervalSeconds(i int) *TenantSettingUpdate {
	tsu.mutation.AddDomainIntervalSeconds(i)
	return tsu
}

// SetEmailAuthIntervalSeconds sets the "email_auth_interval_seconds" field.
func (tsu *TenantSettingUpdate) SetEmailAuthIntervalSeconds(i int) *TenantSettingUpdate {
	tsu.mutation.ResetEmailAuthIntervalSeconds()
	tsu.mutation.SetEmailAuthIntervalSeconds(i)
	return tsu
}

// SetNillableEmailAuthIntervalSeconds sets the "email_auth_interval_seconds" field if the given value is not nil.
func (tsu *TenantSettingUpdate) SetNillableEmailAuthIntervalSeconds(i *int) *TenantSettingUpdate {
	if i != nil {
		tsu.SetEmailAuthIntervalSeconds(*i)
	}
	return tsu
}

// AddEmailAuthIntervalSeconds adds i to the "email_auth_interval_seconds" field.
func (tsu *TenantSettingUpdate) AddEmailAuthIntervalSeconds(i int) *TenantSettingUpdate {
	tsu.mutation.AddEmailAuthIntervalSeconds(i)
	return tsu
}

// SetSslMinExpiryDays sets the "ssl_min_expiry_days" field.
func (tsu *TenantSettingUpdate) SetSslMinExpiryDays(i int) *TenantSettingUpdate {
	tsu.mutation.ResetSslMinExpiryDays()
	tsu.mutation.SetSslMinExpiryDays(i)
	return tsu
}

// SetNillableSslMinExpiryDays sets the "ssl_min_expiry_days" field if the given value is not nil.
func (tsu *TenantSettingUpdate) SetNillableSslMinExpiryDays(i *int) *TenantSettingUpdate {
	if i != nil {
		tsu.SetSslMinExpiryDays(*i)
	}
	return tsu
}

// AddSslMinExpiryDays adds i to the "ssl_min_expiry_days" field.
func (tsu *TenantSettingUpdate) AddSslMinExpiryDays(i int) *TenantSettingUpdate {
	tsu.mutation.AddSslMinExpiryDays(i)
	return tsu
}

// SetDomainMinExpiryDays sets the "domain_min_expiry_days" field.
func (tsu *TenantSettingUpdate) SetDomainMinExpiryDays(i int) *TenantSettingUpdate {
	tsu.mutation.ResetDomainMinExpiryDays()
	tsu.mutation.SetDomainMinExpiryDays(i)
	return tsu
}

// SetNillableDomainMinExpiryDays sets the "domain_min_expiry_days" field if the given value is not nil.
func (tsu *TenantSettingUpdate) SetNillableDomainMinExpiryDays(i *int) *TenantSettingUpdate {
	if i != nil {
		tsu.SetDomainMinExpiryDays(*i)
	}
	return tsu
}

// AddDomainMinExpiryDays adds i to the "domain_min_expiry_days" field.
func (tsu *TenantSettingUpdate) AddDomainMinExpiryDays(i int) *TenantSettingUpdate {
	tsu.mutation.AddDomainMinExpiryDays(i)
	return tsu
}

// SetUpdatedAt sets the "updated_at" field.
func (tsu *TenantSettingUpdate) SetUpdatedAt(t time.Time) *TenantSettingUpdate {
	tsu.mutation.SetUpdatedAt(t)
	return tsu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tsu *TenantSettingUpdate) SetNillableUpdatedAt(t *time.Time) *TenantSettingUpdate {
	if t != nil {
		tsu.SetUpdatedAt(*t)
	}
	return tsu
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (tsu *TenantSettingUpdate) SetTenant(t *Tenant) *TenantSettingUpdate {
	return tsu.SetTenantID(t.ID)
}

// Mutation returns the TenantSettingMutation object of the builder.
func (tsu *TenantSettingUpdate) Mutation() *TenantSettingMutation {
	return tsu.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (tsu *TenantSettingUpdate) ClearTenant() *TenantSettingUpdate {
	tsu.mutation.ClearTenant()
	return tsu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tsu *TenantSettingUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tsu.sqlSave, tsu.mutation, tsu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsu *TenantSettingUpdate) SaveX(ctx context.Context) int {
	affected, err := tsu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tsu *TenantSettingUpdate) Exec(ctx context.Context) error {
	_, err := tsu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsu *TenantSettingUpdate) ExecX(ctx context.Context) {
	if err := tsu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsu *TenantSettingUpdate) check() error {
	if tsu.mutation.TenantCleared() && len(tsu.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantSetting.tenant"`)
	}
	return nil
}

func (tsu *TenantSettingUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tsu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantsetting.Table, tenantsetting.Columns, sqlgraph.NewFieldSpec(tenantsetting.FieldID, field.TypeUUID))
	if ps := tsu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsu.mutation.HTTPIntervalSeconds(); ok {
		_spec.SetField(tenantsetting.FieldHTTPIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.AddedHTTPIntervalSeconds(); ok {
		_spec.AddField(tenantsetting.FieldHTTPIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.DNSIntervalSeconds(); ok {
		_spec.SetField(tenantsetting.FieldDNSIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.AddedDNSIntervalSeconds(); ok {
		_spec.AddField(tenantsetting.FieldDNSIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.SslIntervalSeconds(); ok {
		_spec.SetField(tenantsetting.FieldSslIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.AddedSslIntervalSeconds(); ok {
		_spec.AddField(tenantsetting.FieldSslIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.DomainIntervalSeconds(); ok {
		_spec.SetField(tenantsetting.FieldDomainIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.AddedDomainIntervalSeconds(); ok {
		_spec.AddField(tenantsetting.FieldDomainIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.EmailAuthIntervalSeconds(); ok {
		_spec.SetField(tenantsetting.FieldEmailAuthIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.AddedEmailAuthIntervalSeconds(); ok {
		_spec.AddField(tenantsetting.FieldEmailAuthIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.SslMinExpiryDays(); ok {
		_spec.SetField(tenantsetting.FieldSslMinExpiryDays, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.AddedSslMinExpiryDays(); ok {
		_spec.AddField(tenantsetting.FieldSslMinExpiryDays, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.DomainMinExpiryDays(); ok {
		_spec.SetField(tenantsetting.FieldDomainMinExpiryDays, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.AddedDomainMinExpiryDays(); ok {
		_spec.AddField(tenantsetting.FieldDomainMinExpiryDays, field.TypeInt, value)
	}
	if value, ok := tsu.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if tsu.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tenantsetting.TenantTable,
			Columns: []string{tenantsetting.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsu.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tenantsetting.TenantTable,
			Columns: []string{tenantsetting.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tsu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tsu.mutation.done = true
	return n, nil
}

// TenantSettingUpdateOne is the builder for updating a single TenantSetting entity.
type TenantSettingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantSettingMutation
}

// SetTenantID sets the "tenant_id" field.
func (tsuo *TenantSettingUpdateOne) SetTenantID(u uuid.UUID) *TenantSettingUpdateOne {
	tsuo.mutation.SetTenantID(u)
	return tsuo
}

// SetNillableTenantID sets the "tenant_id" field if the given value is not nil.
func (tsuo *TenantSettingUpdateOne) SetNillableTenantID(u *uuid.UUID) *TenantSettingUpdateOne {
	if u != nil {
		tsuo.SetTenantID(*u)
	}
	return tsuo
}

// SetHTTPIntervalSeconds sets the "http_interval_seconds" field.
func (tsuo *TenantSettingUpdateOne) SetHTTPIntervalSeconds(i int) *TenantSettingUpdateOne {
	tsuo.mutation.ResetHTTPIntervalSeconds()
	tsuo.mutation.SetHTTPIntervalSeconds(i)
	return tsuo
}

// SetNillableHTTPIntervalSeconds sets the "http_interval_seconds" field if the given value is not nil.
func (tsuo *TenantSettingUpdateOne) SetNillableHTTPIntervalSeconds(i *int) *TenantSettingUpdateOne {
	if i != nil {
		tsuo.SetHTTPIntervalSeconds(*i)
	}
	return tsuo
}

// AddHTTPIntervalSeconds adds i to the "http_interval_seconds" field.
func (tsuo *TenantSettingUpdateOne) AddHTTPIntervalSeconds(i int) *TenantSettingUpdateOne {
	tsuo.mutation.AddHTTPIntervalSeconds(i)
	return tsuo
}

// SetDNSIntervalSeconds sets the "dns_interval_seconds" field.
func (tsuo *TenantSettingUpdateOne) SetDNSIntervalSeconds(i int) *TenantSettingUpdateOne {
	tsuo.mutation.ResetDNSIntervalSeconds()
	tsuo.mutation.SetDNSIntervalSeconds(i)
	return tsuo
}

// SetNillableDNSIntervalSeconds sets the "dns_interval_seconds" field if the given value is not nil.
func (tsuo *TenantSettingUpdateOne) SetNillableDNSIntervalSeconds(i *int) *TenantSettingUpdateOne {
	if i != nil {
		tsuo.SetDNSIntervalSeconds(*i)
	}
	return tsuo
}

// AddDNSIntervalSeconds adds i to the "dns_interval_seconds" field.
func (tsuo *TenantSettingUpdateOne) AddDNSIntervalSeconds(i int) *TenantSettingUpdateOne {
	tsuo.mutation.AddDNSIntervalSeconds(i)
	return tsuo
}

// SetSslIntervalSeconds sets the "ssl_interval_seconds" field.
func (tsuo *TenantSettingUpdateOne) SetSslIntervalSeconds(i int) *TenantSettingUpdateOne {
	tsuo.mutation.ResetSslIntervalSeconds()
	tsuo.mutation.SetSslIntervalSeconds(i)
	return tsuo
}

// SetNillableSslIntervalSeconds sets the "ssl_interval_seconds" field if the given value is not nil.
func (tsuo *TenantSettingUpdateOne) SetNillableSslIntervalSeconds(i *int) *TenantSettingUpdateOne {
	if i != nil {
		tsuo.SetSslIntervalSeconds(*i)
	}
	return tsuo
}

// AddSslIntervalSeconds adds i to the "ssl_interval_seconds" field.
func (tsuo *TenantSettingUpdateOne) AddSslIntervalSeconds(i int) *TenantSettingUpdateOne {
	tsuo.mutation.AddSslIntervalSeconds(i)
	return tsuo
}

// SetDomainIntervalSeconds sets the "domain_interval_seconds" field.
func (tsuo *TenantSettingUpdateOne) SetDomainIntervalSeconds(i int) *TenantSettingUpdateOne {
	tsuo.mutation.ResetDomainIntervalSeconds()
	tsuo.mutation.SetDomainIntervalSeconds(i)
	return tsuo
}

// SetNillableDomainIntervalSeconds sets the "domain_interval_seconds" field if the given value is not nil.
func (tsuo *TenantSettingUpdateOne) SetNillableDomainIntervalSeconds(i *int) *TenantSettingUpdateOne {
	if i != nil {
		tsuo.SetDomainIntervalSeconds(*i)
	}
	return tsuo
}

// AddDomainIntervalSeconds adds i to the "domain_interval_seconds" field.
func (tsuo *TenantSettingUpdateOne) AddDomainIntervalSeconds(i int) *TenantSettingUpdateOne {
	tsuo.mutation.AddDomainIntervalSeconds(i)
	return tsuo
}

// SetEmailAuthIntervalSeconds sets the "email_auth_interval_seconds" field.
func (tsuo *TenantSettingUpdateOne) SetEmailAuthIntervalSeconds(i int) *TenantSettingUpdateOne {
	tsuo.mutation.ResetEmailAuthIntervalSeconds()
	tsuo.mutation.SetEmailAuthIntervalSeconds(i)
	return tsuo
}

// SetNillableEmailAuthIntervalSeconds sets the "email_auth_interval_seconds" field if the given value is not nil.
func (tsuo *TenantSettingUpdateOne) SetNillableEmailAuthIntervalSeconds(i *int) *TenantSettingUpdateOne {
	if i != nil {
		tsuo.SetEmailAuthIntervalSeconds(*i)
	}
	return tsuo
}

// AddEmailAuthIntervalSeconds adds i to the "email_auth_interval_seconds" field.
func (tsuo *TenantSettingUpdateOne) AddEmailAuthIntervalSeconds(i int) *TenantSettingUpdateOne {
	tsuo.mutation.AddEmailAuthIntervalSeconds(i)
	return tsuo
}

// SetSslMinExpiryDays sets the "ssl_min_expiry_days" field.
func (tsuo *TenantSettingUpdateOne) SetSslMinExpiryDays(i int) *TenantSettingUpdateOne {
	tsuo.mutation.ResetSslMinExpiryDays()
	tsuo.mutation.SetSslMinExpiryDays(i)
	return tsuo
}

// SetNillableSslMinExpiryDays sets the "ssl_min_expiry_days" field if the given value is not nil.
func (tsuo *TenantSettingUpdateOne) SetNillableSslMinExpiryDays(i *int) *TenantSettingUpdateOne {
	if i != nil {
		tsuo.SetSslMinExpiryDays(*i)
	}
	return tsuo
}

// AddSslMinExpiryDays adds i to the "ssl_min_expiry_days" field.
func (tsuo *TenantSettingUpdateOne) AddSslMinExpiryDays(i int) *TenantSettingUpdateOne {
	tsuo.mutation.AddSslMinExpiryDays(i)
	return tsuo
}

// SetDomainMinExpiryDays sets the "domain_min_expiry_days" field.
func (tsuo *TenantSettingUpdateOne) SetDomainMinExpiryDays(i int) *TenantSettingUpdateOne {
	tsuo.mutation.ResetDomainMinExpiryDays()
	tsuo.mutation.SetDomainMinExpiryDays(i)
	return tsuo
}

// SetNillableDomainMinExpiryDays sets the "domain_min_expiry_days" field if the given value is not nil.
func (tsuo *TenantSettingUpdateOne) SetNillableDomainMinExpiryDays(i *int) *TenantSettingUpdateOne {
	if i != nil {
		tsuo.SetDomainMinExpiryDays(*i)
	}
	return tsuo
}

// AddDomainMinExpiryDays adds i to the "domain_min_expiry_days" field.
func (tsuo *TenantSettingUpdateOne) AddDomainMinExpiryDays(i int) *TenantSettingUpdateOne {
	tsuo.mutation.AddDomainMinExpiryDays(i)
	return tsuo
}

// SetUpdatedAt sets the "updated_at" field.
func (tsuo *TenantSettingUpdateOne) SetUpdatedAt(t time.Time) *TenantSettingUpdateOne {
	tsuo.mutation.SetUpdatedAt(t)
	return tsuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tsuo *TenantSettingUpdateOne) SetNillableUpdatedAt(t *time.Time) *TenantSettingUpdateOne {
	if t != nil {
		tsuo.SetUpdatedAt(*t)
	}
	return tsuo
}

// SetTenant sets the "tenant" edge to the Tenant entity.
func (tsuo *TenantSettingUpdateOne) SetTenant(t *Tenant) *TenantSettingUpdateOne {
	return tsuo.SetTenantID(t.ID)
}

// Mutation returns the TenantSettingMutation object of the builder.
func (tsuo *TenantSettingUpdateOne) Mutation() *TenantSettingMutation {
	return tsuo.mutation
}

// ClearTenant clears the "tenant" edge to the Tenant entity.
func (tsuo *TenantSettingUpdateOne) ClearTenant() *TenantSettingUpdateOne {
	tsuo.mutation.ClearTenant()
	return tsuo
}

// Where appends a list predicates to the TenantSettingUpdate builder.
func (tsuo *TenantSettingUpdateOne) Where(ps ...predicate.TenantSetting) *TenantSettingUpdateOne {
	tsuo.mutation.Where(ps...)
	return tsuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tsuo *TenantSettingUpdateOne) Select(field string, fields ...string) *TenantSettingUpdateOne {
	tsuo.fields = append([]string{field}, fields...)
	return tsuo
}

// Save executes the query and returns the updated TenantSetting entity.
func (tsuo *TenantSettingUpdateOne) Save(ctx context.Context) (*TenantSetting, error) {
	return withHooks(ctx, tsuo.sqlSave, tsuo.mutation, tsuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tsuo *TenantSettingUpdateOne) SaveX(ctx context.Context) *TenantSetting {
	node, err := tsuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tsuo *TenantSettingUpdateOne) Exec(ctx context.Context) error {
	_, err := tsuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tsuo *TenantSettingUpdateOne) ExecX(ctx context.Context) {
	if err := tsuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tsuo *TenantSettingUpdateOne) check() error {
	if tsuo.mutation.TenantCleared() && len(tsuo.mutation.TenantIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TenantSetting.tenant"`)
	}
	return nil
}

func (tsuo *TenantSettingUpdateOne) sqlSave(ctx context.Context) (_node *TenantSetting, err error) {
	if err := tsuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenantsetting.Table, tenantsetting.Columns, sqlgraph.NewFieldSpec(tenantsetting.FieldID, field.TypeUUID))
	id, ok := tsuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TenantSetting.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tsuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenantsetting.FieldID)
		for _, f := range fields {
			if !tenantsetting.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenantsetting.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tsuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tsuo.mutation.HTTPIntervalSeconds(); ok {
		_spec.SetField(tenantsetting.FieldHTTPIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.AddedHTTPIntervalSeconds(); ok {
		_spec.AddField(tenantsetting.FieldHTTPIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.DNSIntervalSeconds(); ok {
		_spec.SetField(tenantsetting.FieldDNSIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.AddedDNSIntervalSeconds(); ok {
		_spec.AddField(tenantsetting.FieldDNSIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.SslIntervalSeconds(); ok {
		_spec.SetField(tenantsetting.FieldSslIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.AddedSslIntervalSeconds(); ok {
		_spec.AddField(tenantsetting.FieldSslIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.DomainIntervalSeconds(); ok {
		_spec.SetField(tenantsetting.FieldDomainIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.AddedDomainIntervalSeconds(); ok {
		_spec.AddField(tenantsetting.FieldDomainIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.EmailAuthIntervalSeconds(); ok {
		_spec.SetField(tenantsetting.FieldEmailAuthIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.AddedEmailAuthIntervalSeconds(); ok {
		_spec.AddField(tenantsetting.FieldEmailAuthIntervalSeconds, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.SslMinExpiryDays(); ok {
		_spec.SetField(tenantsetting.FieldSslMinExpiryDays, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.AddedSslMinExpiryDays(); ok {
		_spec.AddField(tenantsetting.FieldSslMinExpiryDays, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.DomainMinExpiryDays(); ok {
		_spec.SetField(tenantsetting.FieldDomainMinExpiryDays, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.AddedDomainMinExpiryDays(); ok {
		_spec.AddField(tenantsetting.FieldDomainMinExpiryDays, field.TypeInt, value)
	}
	if value, ok := tsuo.mutation.UpdatedAt(); ok {
		_spec.SetField(tenantsetting.FieldUpdatedAt, field.TypeTime, value)
	}
	if tsuo.mutation.TenantCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tenantsetting.TenantTable,
			Columns: []string{tenantsetting.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tsuo.mutation.TenantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   tenantsetting.TenantTable,
			Columns: []string{tenantsetting.TenantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TenantSetting{config: tsuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tsuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenantsetting.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tsuo.mutation.done = true
	return _node, nil
}
