// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/alert"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/alertevent"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/invite"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/membership"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/monitor"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/notificationchannel"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/predicate"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/pushsubscription"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/tenant"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/tenantsetting"
)

// TenantUpdate is the builder for updating Tenant entities.
type TenantUpdate struct {
	config
	hooks    []Hook
	mutation *TenantMutation
}

// Where appends a list predicates to the TenantUpdate builder.
func (tu *TenantUpdate) Where(ps ...predicate.Tenant) *TenantUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetName sets the "name" field.
func (tu *TenantUpdate) SetName(s string) *TenantUpdate {
	tu.mutation.SetName(s)
	return tu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableName(s *string) *TenantUpdate {
	if s != nil {
		tu.SetName(*s)
	}
	return tu
}

// SetPlan sets the "plan" field.
func (tu *TenantUpdate) SetPlan(s string) *TenantUpdate {
	tu.mutation.SetPlan(s)
	return tu
}

// SetNillablePlan sets the "plan" field if the given value is not nil.
func (tu *TenantUpdate) SetNillablePlan(s *string) *TenantUpdate {
	if s != nil {
		tu.SetPlan(*s)
	}
	return tu
}

// SetCreatedAt sets the "created_at" field.
func (tu *TenantUpdate) SetCreatedAt(t time.Time) *TenantUpdate {
	tu.mutation.SetCreatedAt(t)
	return tu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tu *TenantUpdate) SetNillableCreatedAt(t *time.Time) *TenantUpdate {
	if t != nil {
		tu.SetCreatedAt(*t)
	}
	return tu
}

// AddMembershipIDs adds the "memberships" edge to the Membership entity by IDs.
func (tu *TenantUpdate) AddMembershipIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.AddMembershipIDs(ids...)
	return tu
}

// AddMemberships adds the "memberships" edges to the Membership entity.
func (tu *TenantUpdate) AddMemberships(m ...*Membership) *TenantUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return tu.AddMembershipIDs(ids...)
}

// AddMonitorIDs adds the "monitors" edge to the Monitor entity by IDs.
func (tu *TenantUpdate) AddMonitorIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.AddMonitorIDs(ids...)
	return tu
}

// AddMonitors adds the "monitors" edges to the Monitor entity.
func (tu *TenantUpdate) AddMonitors(m ...*Monitor) *TenantUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return tu.AddMonitorIDs(ids...)
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (tu *TenantUpdate) AddAlertIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.AddAlertIDs(ids...)
	return tu
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (tu *TenantUpdate) AddAlerts(a ...*Alert) *TenantUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tu.AddAlertIDs(ids...)
}

// AddNotificationChannelIDs adds the "notification_channels" edge to the NotificationChannel entity by IDs.
func (tu *TenantUpdate) AddNotificationChannelIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.AddNotificationChannelIDs(ids...)
	return tu
}

// AddNotificationChannels adds the "notification_channels" edges to the NotificationChannel entity.
func (tu *TenantUpdate) AddNotificationChannels(n ...*NotificationChannel) *TenantUpdate {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return tu.AddNotificationChannelIDs(ids...)
}

// SetSettingsID sets the "settings" edge to the TenantSetting entity by ID.
func (tu *TenantUpdate) SetSettingsID(id uuid.UUID) *TenantUpdate {
	tu.mutation.SetSettingsID(id)
	return tu
}

// SetNillableSettingsID sets the "settings" edge to the TenantSetting entity by ID if the given value is not nil.
func (tu *TenantUpdate) SetNillableSettingsID(id *uuid.UUID) *TenantUpdate {
	if id != nil {
		tu = tu.SetSettingsID(*id)
	}
	return tu
}

// SetSettings sets the "settings" edge to the TenantSetting entity.
func (tu *TenantUpdate) SetSettings(t *TenantSetting) *TenantUpdate {
	return tu.SetSettingsID(t.ID)
}

// AddInviteIDs adds the "invites" edge to the Invite entity by IDs.
func (tu *TenantUpdate) AddInviteIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.AddInviteIDs(ids...)
	return tu
}

// AddInvites adds the "invites" edges to the Invite entity.
func (tu *TenantUpdate) AddInvites(i ...*Invite) *TenantUpdate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return tu.AddInviteIDs(ids...)
}

// AddAlertEventIDs adds the "alert_events" edge to the AlertEvent entity by IDs.
func (tu *TenantUpdate) AddAlertEventIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.AddAlertEventIDs(ids...)
	return tu
}

// AddAlertEvents adds the "alert_events" edges to the AlertEvent entity.
func (tu *TenantUpdate) AddAlertEvents(a ...*AlertEvent) *TenantUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tu.AddAlertEventIDs(ids...)
}

// AddPushSubscriptionIDs adds the "push_subscriptions" edge to the PushSubscription entity by IDs.
func (tu *TenantUpdate) AddPushSubscriptionIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.AddPushSubscriptionIDs(ids...)
	return tu
}

// AddPushSubscriptions adds the "push_subscriptions" edges to the PushSubscription entity.
func (tu *TenantUpdate) AddPushSubscriptions(p ...*PushSubscription) *TenantUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tu.AddPushSubscriptionIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (tu *TenantUpdate) Mutation() *TenantMutation {
	return tu.mutation
}

// ClearMemberships clears all "memberships" edges to the Membership entity.
func (tu *TenantUpdate) ClearMemberships() *TenantUpdate {
	tu.mutation.ClearMemberships()
	return tu
}

// RemoveMembershipIDs removes the "memberships" edge to Membership entities by IDs.
func (tu *TenantUpdate) RemoveMembershipIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.RemoveMembershipIDs(ids...)
	return tu
}

// RemoveMemberships removes "memberships" edges to Membership entities.
func (tu *TenantUpdate) RemoveMemberships(m ...*Membership) *TenantUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return tu.RemoveMembershipIDs(ids...)
}

// ClearMonitors clears all "monitors" edges to the Monitor entity.
func (tu *TenantUpdate) ClearMonitors() *TenantUpdate {
	tu.mutation.ClearMonitors()
	return tu
}

// RemoveMonitorIDs removes the "monitors" edge to Monitor entities by IDs.
func (tu *TenantUpdate) RemoveMonitorIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.RemoveMonitorIDs(ids...)
	return tu
}

// RemoveMonitors removes "monitors" edges to Monitor entities.
func (tu *TenantUpdate) RemoveMonitors(m ...*Monitor) *TenantUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return tu.RemoveMonitorIDs(ids...)
}

// ClearAlerts clears all "alerts" edges to the Alert entity.
func (tu *TenantUpdate) ClearAlerts() *TenantUpdate {
	tu.mutation.ClearAlerts()
	return tu
}

// RemoveAlertIDs removes the "alerts" edge to Alert entities by IDs.
func (tu *TenantUpdate) RemoveAlertIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.RemoveAlertIDs(ids...)
	return tu
}

// RemoveAlerts removes "alerts" edges to Alert entities.
func (tu *TenantUpdate) RemoveAlerts(a ...*Alert) *TenantUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tu.RemoveAlertIDs(ids...)
}

// ClearNotificationChannels clears all "notification_channels" edges to the NotificationChannel entity.
func (tu *TenantUpdate) ClearNotificationChannels() *TenantUpdate {
	tu.mutation.ClearNotificationChannels()
	return tu
}

// RemoveNotificationChannelIDs removes the "notification_channels" edge to NotificationChannel entities by IDs.
func (tu *TenantUpdate) RemoveNotificationChannelIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.RemoveNotificationChannelIDs(ids...)
	return tu
}

// RemoveNotificationChannels removes "notification_channels" edges to NotificationChannel entities.
func (tu *TenantUpdate) RemoveNotificationChannels(n ...*NotificationChannel) *TenantUpdate {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return tu.RemoveNotificationChannelIDs(ids...)
}

// ClearSettings clears the "settings" edge to the TenantSetting entity.
func (tu *TenantUpdate) ClearSettings() *TenantUpdate {
	tu.mutation.ClearSettings()
	return tu
}

// ClearInvites clears all "invites" edges to the Invite entity.
func (tu *TenantUpdate) ClearInvites() *TenantUpdate {
	tu.mutation.ClearInvites()
	return tu
}

// RemoveInviteIDs removes the "invites" edge to Invite entities by IDs.
func (tu *TenantUpdate) RemoveInviteIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.RemoveInviteIDs(ids...)
	return tu
}

// RemoveInvites removes "invites" edges to Invite entities.
func (tu *TenantUpdate) RemoveInvites(i ...*Invite) *TenantUpdate {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return tu.RemoveInviteIDs(ids...)
}

// ClearAlertEvents clears all "alert_events" edges to the AlertEvent entity.
func (tu *TenantUpdate) ClearAlertEvents() *TenantUpdate {
	tu.mutation.ClearAlertEvents()
	return tu
}

// RemoveAlertEventIDs removes the "alert_events" edge to AlertEvent entities by IDs.
func (tu *TenantUpdate) RemoveAlertEventIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.RemoveAlertEventIDs(ids...)
	return tu
}

// RemoveAlertEvents removes "alert_events" edges to AlertEvent entities.
func (tu *TenantUpdate) RemoveAlertEvents(a ...*AlertEvent) *TenantUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tu.RemoveAlertEventIDs(ids...)
}

// ClearPushSubscriptions clears all "push_subscriptions" edges to the PushSubscription entity.
func (tu *TenantUpdate) ClearPushSubscriptions() *TenantUpdate {
	tu.mutation.ClearPushSubscriptions()
	return tu
}

// RemovePushSubscriptionIDs removes the "push_subscriptions" edge to PushSubscription entities by IDs.
func (tu *TenantUpdate) RemovePushSubscriptionIDs(ids ...uuid.UUID) *TenantUpdate {
	tu.mutation.RemovePushSubscriptionIDs(ids...)
	return tu
}

// RemovePushSubscriptions removes "push_subscriptions" edges to PushSubscription entities.
func (tu *TenantUpdate) RemovePushSubscriptions(p ...*PushSubscription) *TenantUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tu.RemovePushSubscriptionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TenantUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TenantUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TenantUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TenantUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *TenantUpdate) check() error {
	if v, ok := tu.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	return nil
}

func (tu *TenantUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := tu.mutation.Plan(); ok {
		_spec.SetField(tenant.FieldPlan, field.TypeString, value)
	}
	if value, ok := tu.mutation.CreatedAt(); ok {
		_spec.SetField(tenant.FieldCreatedAt, field.TypeTime, value)
	}
	if tu.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !tu.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MonitorsTable,
			Columns: []string{tenant.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedMonitorsIDs(); len(nodes) > 0 && !tu.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MonitorsTable,
			Columns: []string{tenant.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.MonitorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MonitorsTable,
			Columns: []string{tenant.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AlertsTable,
			Columns: []string{tenant.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedAlertsIDs(); len(nodes) > 0 && !tu.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AlertsTable,
			Columns: []string{tenant.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AlertsTable,
			Columns: []string{tenant.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.NotificationChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotificationChannelsTable,
			Columns: []string{tenant.NotificationChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedNotificationChannelsIDs(); len(nodes) > 0 && !tu.mutation.NotificationChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotificationChannelsTable,
			Columns: []string{tenant.NotificationChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.NotificationChannelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotificationChannelsTable,
			Columns: []string{tenant.NotificationChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.SettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   tenant.SettingsTable,
			Columns: []string{tenant.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantsetting.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.SettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   tenant.SettingsTable,
			Columns: []string{tenant.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantsetting.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.InvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.InvitesTable,
			Columns: []string{tenant.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedInvitesIDs(); len(nodes) > 0 && !tu.mutation.InvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.InvitesTable,
			Columns: []string{tenant.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.InvitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.InvitesTable,
			Columns: []string{tenant.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.AlertEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AlertEventsTable,
			Columns: []string{tenant.AlertEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedAlertEventsIDs(); len(nodes) > 0 && !tu.mutation.AlertEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AlertEventsTable,
			Columns: []string{tenant.AlertEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.AlertEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AlertEventsTable,
			Columns: []string{tenant.AlertEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.PushSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.PushSubscriptionsTable,
			Columns: []string{tenant.PushSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pushsubscription.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedPushSubscriptionsIDs(); len(nodes) > 0 && !tu.mutation.PushSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.PushSubscriptionsTable,
			Columns: []string{tenant.PushSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pushsubscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.PushSubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.PushSubscriptionsTable,
			Columns: []string{tenant.PushSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pushsubscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TenantUpdateOne is the builder for updating a single Tenant entity.
type TenantUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TenantMutation
}

// SetName sets the "name" field.
func (tuo *TenantUpdateOne) SetName(s string) *TenantUpdateOne {
	tuo.mutation.SetName(s)
	return tuo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableName(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetName(*s)
	}
	return tuo
}

// SetPlan sets the "plan" field.
func (tuo *TenantUpdateOne) SetPlan(s string) *TenantUpdateOne {
	tuo.mutation.SetPlan(s)
	return tuo
}

// SetNillablePlan sets the "plan" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillablePlan(s *string) *TenantUpdateOne {
	if s != nil {
		tuo.SetPlan(*s)
	}
	return tuo
}

// SetCreatedAt sets the "created_at" field.
func (tuo *TenantUpdateOne) SetCreatedAt(t time.Time) *TenantUpdateOne {
	tuo.mutation.SetCreatedAt(t)
	return tuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableCreatedAt(t *time.Time) *TenantUpdateOne {
	if t != nil {
		tuo.SetCreatedAt(*t)
	}
	return tuo
}

// AddMembershipIDs adds the "memberships" edge to the Membership entity by IDs.
func (tuo *TenantUpdateOne) AddMembershipIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.AddMembershipIDs(ids...)
	return tuo
}

// AddMemberships adds the "memberships" edges to the Membership entity.
func (tuo *TenantUpdateOne) AddMemberships(m ...*Membership) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return tuo.AddMembershipIDs(ids...)
}

// AddMonitorIDs adds the "monitors" edge to the Monitor entity by IDs.
func (tuo *TenantUpdateOne) AddMonitorIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.AddMonitorIDs(ids...)
	return tuo
}

// AddMonitors adds the "monitors" edges to the Monitor entity.
func (tuo *TenantUpdateOne) AddMonitors(m ...*Monitor) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return tuo.AddMonitorIDs(ids...)
}

// AddAlertIDs adds the "alerts" edge to the Alert entity by IDs.
func (tuo *TenantUpdateOne) AddAlertIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.AddAlertIDs(ids...)
	return tuo
}

// AddAlerts adds the "alerts" edges to the Alert entity.
func (tuo *TenantUpdateOne) AddAlerts(a ...*Alert) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tuo.AddAlertIDs(ids...)
}

// AddNotificationChannelIDs adds the "notification_channels" edge to the NotificationChannel entity by IDs.
func (tuo *TenantUpdateOne) AddNotificationChannelIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.AddNotificationChannelIDs(ids...)
	return tuo
}

// AddNotificationChannels adds the "notification_channels" edges to the NotificationChannel entity.
func (tuo *TenantUpdateOne) AddNotificationChannels(n ...*NotificationChannel) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return tuo.AddNotificationChannelIDs(ids...)
}

// SetSettingsID sets the "settings" edge to the TenantSetting entity by ID.
func (tuo *TenantUpdateOne) SetSettingsID(id uuid.UUID) *TenantUpdateOne {
	tuo.mutation.SetSettingsID(id)
	return tuo
}

// SetNillableSettingsID sets the "settings" edge to the TenantSetting entity by ID if the given value is not nil.
func (tuo *TenantUpdateOne) SetNillableSettingsID(id *uuid.UUID) *TenantUpdateOne {
	if id != nil {
		tuo = tuo.SetSettingsID(*id)
	}
	return tuo
}

// SetSettings sets the "settings" edge to the TenantSetting entity.
func (tuo *TenantUpdateOne) SetSettings(t *TenantSetting) *TenantUpdateOne {
	return tuo.SetSettingsID(t.ID)
}

// AddInviteIDs adds the "invites" edge to the Invite entity by IDs.
func (tuo *TenantUpdateOne) AddInviteIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.AddInviteIDs(ids...)
	return tuo
}

// AddInvites adds the "invites" edges to the Invite entity.
func (tuo *TenantUpdateOne) AddInvites(i ...*Invite) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return tuo.AddInviteIDs(ids...)
}

// AddAlertEventIDs adds the "alert_events" edge to the AlertEvent entity by IDs.
func (tuo *TenantUpdateOne) AddAlertEventIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.AddAlertEventIDs(ids...)
	return tuo
}

// AddAlertEvents adds the "alert_events" edges to the AlertEvent entity.
func (tuo *TenantUpdateOne) AddAlertEvents(a ...*AlertEvent) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tuo.AddAlertEventIDs(ids...)
}

// AddPushSubscriptionIDs adds the "push_subscriptions" edge to the PushSubscription entity by IDs.
func (tuo *TenantUpdateOne) AddPushSubscriptionIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.AddPushSubscriptionIDs(ids...)
	return tuo
}

// AddPushSubscriptions adds the "push_subscriptions" edges to the PushSubscription entity.
func (tuo *TenantUpdateOne) AddPushSubscriptions(p ...*PushSubscription) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tuo.AddPushSubscriptionIDs(ids...)
}

// Mutation returns the TenantMutation object of the builder.
func (tuo *TenantUpdateOne) Mutation() *TenantMutation {
	return tuo.mutation
}

// ClearMemberships clears all "memberships" edges to the Membership entity.
func (tuo *TenantUpdateOne) ClearMemberships() *TenantUpdateOne {
	tuo.mutation.ClearMemberships()
	return tuo
}

// RemoveMembershipIDs removes the "memberships" edge to Membership entities by IDs.
func (tuo *TenantUpdateOne) RemoveMembershipIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.RemoveMembershipIDs(ids...)
	return tuo
}

// RemoveMemberships removes "memberships" edges to Membership entities.
func (tuo *TenantUpdateOne) RemoveMemberships(m ...*Membership) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return tuo.RemoveMembershipIDs(ids...)
}

// ClearMonitors clears all "monitors" edges to the Monitor entity.
func (tuo *TenantUpdateOne) ClearMonitors() *TenantUpdateOne {
	tuo.mutation.ClearMonitors()
	return tuo
}

// RemoveMonitorIDs removes the "monitors" edge to Monitor entities by IDs.
func (tuo *TenantUpdateOne) RemoveMonitorIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.RemoveMonitorIDs(ids...)
	return tuo
}

// RemoveMonitors removes "monitors" edges to Monitor entities.
func (tuo *TenantUpdateOne) RemoveMonitors(m ...*Monitor) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return tuo.RemoveMonitorIDs(ids...)
}

// ClearAlerts clears all "alerts" edges to the Alert entity.
func (tuo *TenantUpdateOne) ClearAlerts() *TenantUpdateOne {
	tuo.mutation.ClearAlerts()
	return tuo
}

// RemoveAlertIDs removes the "alerts" edge to Alert entities by IDs.
func (tuo *TenantUpdateOne) RemoveAlertIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.RemoveAlertIDs(ids...)
	return tuo
}

// RemoveAlerts removes "alerts" edges to Alert entities.
func (tuo *TenantUpdateOne) RemoveAlerts(a ...*Alert) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tuo.RemoveAlertIDs(ids...)
}

// ClearNotificationChannels clears all "notification_channels" edges to the NotificationChannel entity.
func (tuo *TenantUpdateOne) ClearNotificationChannels() *TenantUpdateOne {
	tuo.mutation.ClearNotificationChannels()
	return tuo
}

// RemoveNotificationChannelIDs removes the "notification_channels" edge to NotificationChannel entities by IDs.
func (tuo *TenantUpdateOne) RemoveNotificationChannelIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.RemoveNotificationChannelIDs(ids...)
	return tuo
}

// RemoveNotificationChannels removes "notification_channels" edges to NotificationChannel entities.
func (tuo *TenantUpdateOne) RemoveNotificationChannels(n ...*NotificationChannel) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(n))
	for i := range n {
		ids[i] = n[i].ID
	}
	return tuo.RemoveNotificationChannelIDs(ids...)
}

// ClearSettings clears the "settings" edge to the TenantSetting entity.
func (tuo *TenantUpdateOne) ClearSettings() *TenantUpdateOne {
	tuo.mutation.ClearSettings()
	return tuo
}

// ClearInvites clears all "invites" edges to the Invite entity.
func (tuo *TenantUpdateOne) ClearInvites() *TenantUpdateOne {
	tuo.mutation.ClearInvites()
	return tuo
}

// RemoveInviteIDs removes the "invites" edge to Invite entities by IDs.
func (tuo *TenantUpdateOne) RemoveInviteIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.RemoveInviteIDs(ids...)
	return tuo
}

// RemoveInvites removes "invites" edges to Invite entities.
func (tuo *TenantUpdateOne) RemoveInvites(i ...*Invite) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(i))
	for j := range i {
		ids[j] = i[j].ID
	}
	return tuo.RemoveInviteIDs(ids...)
}

// ClearAlertEvents clears all "alert_events" edges to the AlertEvent entity.
func (tuo *TenantUpdateOne) ClearAlertEvents() *TenantUpdateOne {
	tuo.mutation.ClearAlertEvents()
	return tuo
}

// RemoveAlertEventIDs removes the "alert_events" edge to AlertEvent entities by IDs.
func (tuo *TenantUpdateOne) RemoveAlertEventIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.RemoveAlertEventIDs(ids...)
	return tuo
}

// RemoveAlertEvents removes "alert_events" edges to AlertEvent entities.
func (tuo *TenantUpdateOne) RemoveAlertEvents(a ...*AlertEvent) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return tuo.RemoveAlertEventIDs(ids...)
}

// ClearPushSubscriptions clears all "push_subscriptions" edges to the PushSubscription entity.
func (tuo *TenantUpdateOne) ClearPushSubscriptions() *TenantUpdateOne {
	tuo.mutation.ClearPushSubscriptions()
	return tuo
}

// RemovePushSubscriptionIDs removes the "push_subscriptions" edge to PushSubscription entities by IDs.
func (tuo *TenantUpdateOne) RemovePushSubscriptionIDs(ids ...uuid.UUID) *TenantUpdateOne {
	tuo.mutation.RemovePushSubscriptionIDs(ids...)
	return tuo
}

// RemovePushSubscriptions removes "push_subscriptions" edges to PushSubscription entities.
func (tuo *TenantUpdateOne) RemovePushSubscriptions(p ...*PushSubscription) *TenantUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return tuo.RemovePushSubscriptionIDs(ids...)
}

// Where appends a list predicates to the TenantUpdate builder.
func (tuo *TenantUpdateOne) Where(ps ...predicate.Tenant) *TenantUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TenantUpdateOne) Select(field string, fields ...string) *TenantUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Tenant entity.
func (tuo *TenantUpdateOne) Save(ctx context.Context) (*Tenant, error) {
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TenantUpdateOne) SaveX(ctx context.Context) *Tenant {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TenantUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TenantUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *TenantUpdateOne) check() error {
	if v, ok := tuo.mutation.Name(); ok {
		if err := tenant.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Tenant.name": %w`, err)}
		}
	}
	return nil
}

func (tuo *TenantUpdateOne) sqlSave(ctx context.Context) (_node *Tenant, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tenant.Table, tenant.Columns, sqlgraph.NewFieldSpec(tenant.FieldID, field.TypeUUID))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Tenant.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tenant.FieldID)
		for _, f := range fields {
			if !tenant.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tenant.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.Name(); ok {
		_spec.SetField(tenant.FieldName, field.TypeString, value)
	}
	if value, ok := tuo.mutation.Plan(); ok {
		_spec.SetField(tenant.FieldPlan, field.TypeString, value)
	}
	if value, ok := tuo.mutation.CreatedAt(); ok {
		_spec.SetField(tenant.FieldCreatedAt, field.TypeTime, value)
	}
	if tuo.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedMembershipsIDs(); len(nodes) > 0 && !tuo.mutation.MembershipsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.MembershipsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MembershipsTable,
			Columns: []string{tenant.MembershipsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(membership.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MonitorsTable,
			Columns: []string{tenant.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedMonitorsIDs(); len(nodes) > 0 && !tuo.mutation.MonitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MonitorsTable,
			Columns: []string{tenant.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.MonitorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.MonitorsTable,
			Columns: []string{tenant.MonitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(monitor.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AlertsTable,
			Columns: []string{tenant.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedAlertsIDs(); len(nodes) > 0 && !tuo.mutation.AlertsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AlertsTable,
			Columns: []string{tenant.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.AlertsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AlertsTable,
			Columns: []string{tenant.AlertsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alert.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.NotificationChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotificationChannelsTable,
			Columns: []string{tenant.NotificationChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedNotificationChannelsIDs(); len(nodes) > 0 && !tuo.mutation.NotificationChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotificationChannelsTable,
			Columns: []string{tenant.NotificationChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.NotificationChannelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.NotificationChannelsTable,
			Columns: []string{tenant.NotificationChannelsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(notificationchannel.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.SettingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   tenant.SettingsTable,
			Columns: []string{tenant.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantsetting.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.SettingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   tenant.SettingsTable,
			Columns: []string{tenant.SettingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tenantsetting.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.InvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.InvitesTable,
			Columns: []string{tenant.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedInvitesIDs(); len(nodes) > 0 && !tuo.mutation.InvitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.InvitesTable,
			Columns: []string{tenant.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.InvitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.InvitesTable,
			Columns: []string{tenant.InvitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(invite.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.AlertEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AlertEventsTable,
			Columns: []string{tenant.AlertEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedAlertEventsIDs(); len(nodes) > 0 && !tuo.mutation.AlertEventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AlertEventsTable,
			Columns: []string{tenant.AlertEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.AlertEventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.AlertEventsTable,
			Columns: []string{tenant.AlertEventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(alertevent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.PushSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.PushSubscriptionsTable,
			Columns: []string{tenant.PushSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pushsubscription.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedPushSubscriptionsIDs(); len(nodes) > 0 && !tuo.mutation.PushSubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.PushSubscriptionsTable,
			Columns: []string{tenant.PushSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pushsubscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.PushSubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   tenant.PushSubscriptionsTable,
			Columns: []string{tenant.PushSubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(pushsubscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Tenant{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tenant.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
