// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Alert is the predicate function for alert builders.
type Alert func(*sql.Selector)

// AlertEvent is the predicate function for alertevent builders.
type AlertEvent func(*sql.Selector)

// DNSCheckResult is the predicate function for dnscheckresult builders.
type DNSCheckResult func(*sql.Selector)

// DomainCheckResult is the predicate function for domaincheckresult builders.
type DomainCheckResult func(*sql.Selector)

// HTTPCheckResult is the predicate function for httpcheckresult builders.
type HTTPCheckResult func(*sql.Selector)

// Membership is the predicate function for membership builders.
type Membership func(*sql.Selector)

// Monitor is the predicate function for monitor builders.
type Monitor func(*sql.Selector)

// MonitorCheck is the predicate function for monitorcheck builders.
type MonitorCheck func(*sql.Selector)

// MonitorCheckConfig is the predicate function for monitorcheckconfig builders.
type MonitorCheckConfig func(*sql.Selector)

// NotificationChannel is the predicate function for notificationchannel builders.
type NotificationChannel func(*sql.Selector)

// SSLCheckResult is the predicate function for sslcheckresult builders.
type SSLCheckResult func(*sql.Selector)

// Tenant is the predicate function for tenant builders.
type Tenant func(*sql.Selector)

// TenantSetting is the predicate function for tenantsetting builders.
type TenantSetting func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
