// Code generated by ent, DO NOT EDIT.

package monitorcheckconfig

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the monitorcheckconfig type in the database.
	Label = "monitor_check_config"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMonitorID holds the string denoting the monitor_id field in the database.
	FieldMonitorID = "monitor_id"
	// FieldCheckType holds the string denoting the check_type field in the database.
	FieldCheckType = "check_type"
	// FieldIntervalSeconds holds the string denoting the interval_seconds field in the database.
	FieldIntervalSeconds = "interval_seconds"
	// FieldTimeoutSeconds holds the string denoting the timeout_seconds field in the database.
	FieldTimeoutSeconds = "timeout_seconds"
	// FieldIsEnabled holds the string denoting the is_enabled field in the database.
	FieldIsEnabled = "is_enabled"
	// FieldLastCheckedAt holds the string denoting the last_checked_at field in the database.
	FieldLastCheckedAt = "last_checked_at"
	// FieldNextCheckAt holds the string denoting the next_check_at field in the database.
	FieldNextCheckAt = "next_check_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeMonitor holds the string denoting the monitor edge name in mutations.
	EdgeMonitor = "monitor"
	// Table holds the table name of the monitorcheckconfig in the database.
	Table = "monitor_check_configs"
	// MonitorTable is the table that holds the monitor relation/edge.
	MonitorTable = "monitor_check_configs"
	// MonitorInverseTable is the table name for the Monitor entity.
	// It exists in this package in order to avoid circular dependency with the "monitor" package.
	MonitorInverseTable = "monitors"
	// MonitorColumn is the table column denoting the monitor relation/edge.
	MonitorColumn = "monitor_id"
)

// Columns holds all SQL columns for monitorcheckconfig fields.
var Columns = []string{
	FieldID,
	FieldMonitorID,
	FieldCheckType,
	FieldIntervalSeconds,
	FieldTimeoutSeconds,
	FieldIsEnabled,
	FieldLastCheckedAt,
	FieldNextCheckAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IntervalSecondsValidator is a validator for the "interval_seconds" field. It is called by the builders before save.
	IntervalSecondsValidator func(int) error
	// DefaultTimeoutSeconds holds the default value on creation for the "timeout_seconds" field.
	DefaultTimeoutSeconds int
	// DefaultIsEnabled holds the default value on creation for the "is_enabled" field.
	DefaultIsEnabled bool
	// DefaultNextCheckAt holds the default value on creation for the "next_check_at" field.
	DefaultNextCheckAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// CheckType defines the type for the "check_type" enum field.
type CheckType string

// CheckType values.
const (
	CheckTypeHTTP      CheckType = "http"
	CheckTypeDNS       CheckType = "dns"
	CheckTypeSsl       CheckType = "ssl"
	CheckTypeDomain    CheckType = "domain"
	CheckTypeEmailAuth CheckType = "email_auth"
)

func (ct CheckType) String() string {
	return string(ct)
}

// CheckTypeValidator is a validator for the "check_type" field enum values. It is called by the builders before save.
func CheckTypeValidator(ct CheckType) error {
	switch ct {
	case CheckTypeHTTP, CheckTypeDNS, CheckTypeSsl, CheckTypeDomain, CheckTypeEmailAuth:
		return nil
	default:
		return fmt.Errorf("monitorcheckconfig: invalid enum value for check_type field: %q", ct)
	}
}

// OrderOption defines the ordering options for the MonitorCheckConfig queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMonitorID orders the results by the monitor_id field.
func ByMonitorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonitorID, opts...).ToFunc()
}

// ByCheckType orders the results by the check_type field.
func ByCheckType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckType, opts...).ToFunc()
}

// ByIntervalSeconds orders the results by the interval_seconds field.
func ByIntervalSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntervalSeconds, opts...).ToFunc()
}

// ByTimeoutSeconds orders the results by the timeout_seconds field.
func ByTimeoutSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeoutSeconds, opts...).ToFunc()
}

// ByIsEnabled orders the results by the is_enabled field.
func ByIsEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEnabled, opts...).ToFunc()
}

// ByLastCheckedAt orders the results by the last_checked_at field.
func ByLastCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastCheckedAt, opts...).ToFunc()
}

// ByNextCheckAt orders the results by the next_check_at field.
func ByNextCheckAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextCheckAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByMonitorField orders the results by monitor field.
func ByMonitorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMonitorStep(), sql.OrderByField(field, opts...))
	}
}
func newMonitorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MonitorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MonitorTable, MonitorColumn),
	)
}
