// Code generated by ent, DO NOT EDIT.

package dnscheckresult

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldLTE(FieldID, id))
}

// CheckID applies equality check predicate on the "check_id" field. It's identical to CheckIDEQ.
func CheckID(v uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldEQ(FieldCheckID, v))
}

// HasARecord applies equality check predicate on the "has_a_record" field. It's identical to HasARecordEQ.
func HasARecord(v bool) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldEQ(FieldHasARecord, v))
}

// HasAaaaRecord applies equality check predicate on the "has_aaaa_record" field. It's identical to HasAaaaRecordEQ.
func HasAaaaRecord(v bool) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldEQ(FieldHasAaaaRecord, v))
}

// SpfValid applies equality check predicate on the "spf_valid" field. It's identical to SpfValidEQ.
func SpfValid(v bool) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldEQ(FieldSpfValid, v))
}

// DmarcValid applies equality check predicate on the "dmarc_valid" field. It's identical to DmarcValidEQ.
func DmarcValid(v bool) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldEQ(FieldDmarcValid, v))
}

// CheckIDEQ applies the EQ predicate on the "check_id" field.
func CheckIDEQ(v uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldEQ(FieldCheckID, v))
}

// CheckIDNEQ applies the NEQ predicate on the "check_id" field.
func CheckIDNEQ(v uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldNEQ(FieldCheckID, v))
}

// CheckIDIn applies the In predicate on the "check_id" field.
func CheckIDIn(vs ...uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldIn(FieldCheckID, vs...))
}

// CheckIDNotIn applies the NotIn predicate on the "check_id" field.
func CheckIDNotIn(vs ...uuid.UUID) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldNotIn(FieldCheckID, vs...))
}

// HasARecordEQ applies the EQ predicate on the "has_a_record" field.
func HasARecordEQ(v bool) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldEQ(FieldHasARecord, v))
}

// HasARecordNEQ applies the NEQ predicate on the "has_a_record" field.
func HasARecordNEQ(v bool) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldNEQ(FieldHasARecord, v))
}

// HasAaaaRecordEQ applies the EQ predicate on the "has_aaaa_record" field.
func HasAaaaRecordEQ(v bool) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldEQ(FieldHasAaaaRecord, v))
}

// HasAaaaRecordNEQ applies the NEQ predicate on the "has_aaaa_record" field.
func HasAaaaRecordNEQ(v bool) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldNEQ(FieldHasAaaaRecord, v))
}

// ARecordsIsNil applies the IsNil predicate on the "a_records" field.
func ARecordsIsNil() predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldIsNull(FieldARecords))
}

// ARecordsNotNil applies the NotNil predicate on the "a_records" field.
func ARecordsNotNil() predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldNotNull(FieldARecords))
}

// AaaaRecordsIsNil applies the IsNil predicate on the "aaaa_records" field.
func AaaaRecordsIsNil() predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldIsNull(FieldAaaaRecords))
}

// AaaaRecordsNotNil applies the NotNil predicate on the "aaaa_records" field.
func AaaaRecordsNotNil() predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldNotNull(FieldAaaaRecords))
}

// MxRecordsIsNil applies the IsNil predicate on the "mx_records" field.
func MxRecordsIsNil() predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldIsNull(FieldMxRecords))
}

// MxRecordsNotNil applies the NotNil predicate on the "mx_records" field.
func MxRecordsNotNil() predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldNotNull(FieldMxRecords))
}

// TxtRecordsIsNil applies the IsNil predicate on the "txt_records" field.
func TxtRecordsIsNil() predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldIsNull(FieldTxtRecords))
}

// TxtRecordsNotNil applies the NotNil predicate on the "txt_records" field.
func TxtRecordsNotNil() predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldNotNull(FieldTxtRecords))
}

// SpfValidEQ applies the EQ predicate on the "spf_valid" field.
func SpfValidEQ(v bool) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldEQ(FieldSpfValid, v))
}

// SpfValidNEQ applies the NEQ predicate on the "spf_valid" field.
func SpfValidNEQ(v bool) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldNEQ(FieldSpfValid, v))
}

// DmarcValidEQ applies the EQ predicate on the "dmarc_valid" field.
func DmarcValidEQ(v bool) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldEQ(FieldDmarcValid, v))
}

// DmarcValidNEQ applies the NEQ predicate on the "dmarc_valid" field.
func DmarcValidNEQ(v bool) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.FieldNEQ(FieldDmarcValid, v))
}

// HasCheck applies the HasEdge predicate on the "check" edge.
func HasCheck() predicate.DNSCheckResult {
	return predicate.DNSCheckResult(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, CheckTable, CheckColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCheckWith applies the HasEdge predicate on the "check" edge with a given conditions (other predicates).
func HasCheckWith(preds ...predicate.MonitorCheck) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(func(s *sql.Selector) {
		step := newCheckStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DNSCheckResult) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DNSCheckResult) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DNSCheckResult) predicate.DNSCheckResult {
	return predicate.DNSCheckResult(sql.NotPredicates(p))
}
