// Code generated by ent, DO NOT EDIT.

package monitorcheck

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the monitorcheck type in the database.
	Label = "monitor_check"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMonitorID holds the string denoting the monitor_id field in the database.
	FieldMonitorID = "monitor_id"
	// FieldCheckType holds the string denoting the check_type field in the database.
	FieldCheckType = "check_type"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// FieldCheckedAt holds the string denoting the checked_at field in the database.
	FieldCheckedAt = "checked_at"
	// EdgeMonitor holds the string denoting the monitor edge name in mutations.
	EdgeMonitor = "monitor"
	// EdgeHTTPResult holds the string denoting the http_result edge name in mutations.
	EdgeHTTPResult = "http_result"
	// EdgeSslResult holds the string denoting the ssl_result edge name in mutations.
	EdgeSslResult = "ssl_result"
	// EdgeDomainResult holds the string denoting the domain_result edge name in mutations.
	EdgeDomainResult = "domain_result"
	// EdgeDNSResult holds the string denoting the dns_result edge name in mutations.
	EdgeDNSResult = "dns_result"
	// Table holds the table name of the monitorcheck in the database.
	Table = "monitor_checks"
	// MonitorTable is the table that holds the monitor relation/edge.
	MonitorTable = "monitor_checks"
	// MonitorInverseTable is the table name for the Monitor entity.
	// It exists in this package in order to avoid circular dependency with the "monitor" package.
	MonitorInverseTable = "monitors"
	// MonitorColumn is the table column denoting the monitor relation/edge.
	MonitorColumn = "monitor_id"
	// HTTPResultTable is the table that holds the http_result relation/edge.
	HTTPResultTable = "http_check_results"
	// HTTPResultInverseTable is the table name for the HTTPCheckResult entity.
	// It exists in this package in order to avoid circular dependency with the "httpcheckresult" package.
	HTTPResultInverseTable = "http_check_results"
	// HTTPResultColumn is the table column denoting the http_result relation/edge.
	HTTPResultColumn = "check_id"
	// SslResultTable is the table that holds the ssl_result relation/edge.
	SslResultTable = "ssl_check_results"
	// SslResultInverseTable is the table name for the SSLCheckResult entity.
	// It exists in this package in order to avoid circular dependency with the "sslcheckresult" package.
	SslResultInverseTable = "ssl_check_results"
	// SslResultColumn is the table column denoting the ssl_result relation/edge.
	SslResultColumn = "check_id"
	// DomainResultTable is the table that holds the domain_result relation/edge.
	DomainResultTable = "domain_check_results"
	// DomainResultInverseTable is the table name for the DomainCheckResult entity.
	// It exists in this package in order to avoid circular dependency with the "domaincheckresult" package.
	DomainResultInverseTable = "domain_check_results"
	// DomainResultColumn is the table column denoting the domain_result relation/edge.
	DomainResultColumn = "check_id"
	// DNSResultTable is the table that holds the dns_result relation/edge.
	DNSResultTable = "dns_check_results"
	// DNSResultInverseTable is the table name for the DNSCheckResult entity.
	// It exists in this package in order to avoid circular dependency with the "dnscheckresult" package.
	DNSResultInverseTable = "dns_check_results"
	// DNSResultColumn is the table column denoting the dns_result relation/edge.
	DNSResultColumn = "check_id"
)

// Columns holds all SQL columns for monitorcheck fields.
var Columns = []string{
	FieldID,
	FieldMonitorID,
	FieldCheckType,
	FieldStatus,
	FieldError,
	FieldCheckedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCheckedAt holds the default value on creation for the "checked_at" field.
	DefaultCheckedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// CheckType defines the type for the "check_type" enum field.
type CheckType string

// CheckType values.
const (
	CheckTypeHTTP  CheckType = "http"
	CheckTypeSsl   CheckType = "ssl"
	CheckTypeDNS   CheckType = "dns"
	CheckTypeWhois CheckType = "whois"
)

func (ct CheckType) String() string {
	return string(ct)
}

// CheckTypeValidator is a validator for the "check_type" field enum values. It is called by the builders before save.
func CheckTypeValidator(ct CheckType) error {
	switch ct {
	case CheckTypeHTTP, CheckTypeSsl, CheckTypeDNS, CheckTypeWhois:
		return nil
	default:
		return fmt.Errorf("monitorcheck: invalid enum value for check_type field: %q", ct)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// Status values.
const (
	StatusSuccess     Status = "success"
	StatusFailure     Status = "failure"
	StatusRateLimited Status = "rate_limited"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusSuccess, StatusFailure, StatusRateLimited:
		return nil
	default:
		return fmt.Errorf("monitorcheck: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the MonitorCheck queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByMonitorID orders the results by the monitor_id field.
func ByMonitorID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonitorID, opts...).ToFunc()
}

// ByCheckType orders the results by the check_type field.
func ByCheckType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckType, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByCheckedAt orders the results by the checked_at field.
func ByCheckedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckedAt, opts...).ToFunc()
}

// ByMonitorField orders the results by monitor field.
func ByMonitorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMonitorStep(), sql.OrderByField(field, opts...))
	}
}

// ByHTTPResultField orders the results by http_result field.
func ByHTTPResultField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newHTTPResultStep(), sql.OrderByField(field, opts...))
	}
}

// BySslResultField orders the results by ssl_result field.
func BySslResultField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSslResultStep(), sql.OrderByField(field, opts...))
	}
}

// ByDomainResultField orders the results by domain_result field.
func ByDomainResultField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDomainResultStep(), sql.OrderByField(field, opts...))
	}
}

// ByDNSResultField orders the results by dns_result field.
func ByDNSResultField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDNSResultStep(), sql.OrderByField(field, opts...))
	}
}
func newMonitorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MonitorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, MonitorTable, MonitorColumn),
	)
}
func newHTTPResultStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(HTTPResultInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, HTTPResultTable, HTTPResultColumn),
	)
}
func newSslResultStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SslResultInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, SslResultTable, SslResultColumn),
	)
}
func newDomainResultStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DomainResultInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, DomainResultTable, DomainResultColumn),
	)
}
func newDNSResultStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DNSResultInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, DNSResultTable, DNSResultColumn),
	)
}
