// Code generated by ent, DO NOT EDIT.

package monitorcheck

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/kanakmegha/WebsitePingerV2/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldLTE(FieldID, id))
}

// MonitorID applies equality check predicate on the "monitor_id" field. It's identical to MonitorIDEQ.
func MonitorID(v uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldEQ(FieldMonitorID, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldEQ(FieldError, v))
}

// CheckedAt applies equality check predicate on the "checked_at" field. It's identical to CheckedAtEQ.
func CheckedAt(v time.Time) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldEQ(FieldCheckedAt, v))
}

// MonitorIDEQ applies the EQ predicate on the "monitor_id" field.
func MonitorIDEQ(v uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldEQ(FieldMonitorID, v))
}

// MonitorIDNEQ applies the NEQ predicate on the "monitor_id" field.
func MonitorIDNEQ(v uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNEQ(FieldMonitorID, v))
}

// MonitorIDIn applies the In predicate on the "monitor_id" field.
func MonitorIDIn(vs ...uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldIn(FieldMonitorID, vs...))
}

// MonitorIDNotIn applies the NotIn predicate on the "monitor_id" field.
func MonitorIDNotIn(vs ...uuid.UUID) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNotIn(FieldMonitorID, vs...))
}

// CheckTypeEQ applies the EQ predicate on the "check_type" field.
func CheckTypeEQ(v CheckType) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldEQ(FieldCheckType, v))
}

// CheckTypeNEQ applies the NEQ predicate on the "check_type" field.
func CheckTypeNEQ(v CheckType) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNEQ(FieldCheckType, v))
}

// CheckTypeIn applies the In predicate on the "check_type" field.
func CheckTypeIn(vs ...CheckType) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldIn(FieldCheckType, vs...))
}

// CheckTypeNotIn applies the NotIn predicate on the "check_type" field.
func CheckTypeNotIn(vs ...CheckType) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNotIn(FieldCheckType, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNotIn(FieldStatus, vs...))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldContainsFold(FieldError, v))
}

// CheckedAtEQ applies the EQ predicate on the "checked_at" field.
func CheckedAtEQ(v time.Time) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldEQ(FieldCheckedAt, v))
}

// CheckedAtNEQ applies the NEQ predicate on the "checked_at" field.
func CheckedAtNEQ(v time.Time) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNEQ(FieldCheckedAt, v))
}

// CheckedAtIn applies the In predicate on the "checked_at" field.
func CheckedAtIn(vs ...time.Time) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldIn(FieldCheckedAt, vs...))
}

// CheckedAtNotIn applies the NotIn predicate on the "checked_at" field.
func CheckedAtNotIn(vs ...time.Time) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldNotIn(FieldCheckedAt, vs...))
}

// CheckedAtGT applies the GT predicate on the "checked_at" field.
func CheckedAtGT(v time.Time) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldGT(FieldCheckedAt, v))
}

// CheckedAtGTE applies the GTE predicate on the "checked_at" field.
func CheckedAtGTE(v time.Time) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldGTE(FieldCheckedAt, v))
}

// CheckedAtLT applies the LT predicate on the "checked_at" field.
func CheckedAtLT(v time.Time) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldLT(FieldCheckedAt, v))
}

// CheckedAtLTE applies the LTE predicate on the "checked_at" field.
func CheckedAtLTE(v time.Time) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.FieldLTE(FieldCheckedAt, v))
}

// HasMonitor applies the HasEdge predicate on the "monitor" edge.
func HasMonitor() predicate.MonitorCheck {
	return predicate.MonitorCheck(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MonitorTable, MonitorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMonitorWith applies the HasEdge predicate on the "monitor" edge with a given conditions (other predicates).
func HasMonitorWith(preds ...predicate.Monitor) predicate.MonitorCheck {
	return predicate.MonitorCheck(func(s *sql.Selector) {
		step := newMonitorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasHTTPResult applies the HasEdge predicate on the "http_result" edge.
func HasHTTPResult() predicate.MonitorCheck {
	return predicate.MonitorCheck(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, HTTPResultTable, HTTPResultColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasHTTPResultWith applies the HasEdge predicate on the "http_result" edge with a given conditions (other predicates).
func HasHTTPResultWith(preds ...predicate.HTTPCheckResult) predicate.MonitorCheck {
	return predicate.MonitorCheck(func(s *sql.Selector) {
		step := newHTTPResultStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasSslResult applies the HasEdge predicate on the "ssl_result" edge.
func HasSslResult() predicate.MonitorCheck {
	return predicate.MonitorCheck(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, SslResultTable, SslResultColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSslResultWith applies the HasEdge predicate on the "ssl_result" edge with a given conditions (other predicates).
func HasSslResultWith(preds ...predicate.SSLCheckResult) predicate.MonitorCheck {
	return predicate.MonitorCheck(func(s *sql.Selector) {
		step := newSslResultStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDomainResult applies the HasEdge predicate on the "domain_result" edge.
func HasDomainResult() predicate.MonitorCheck {
	return predicate.MonitorCheck(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, DomainResultTable, DomainResultColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDomainResultWith applies the HasEdge predicate on the "domain_result" edge with a given conditions (other predicates).
func HasDomainResultWith(preds ...predicate.DomainCheckResult) predicate.MonitorCheck {
	return predicate.MonitorCheck(func(s *sql.Selector) {
		step := newDomainResultStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDNSResult applies the HasEdge predicate on the "dns_result" edge.
func HasDNSResult() predicate.MonitorCheck {
	return predicate.MonitorCheck(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, DNSResultTable, DNSResultColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDNSResultWith applies the HasEdge predicate on the "dns_result" edge with a given conditions (other predicates).
func HasDNSResultWith(preds ...predicate.DNSCheckResult) predicate.MonitorCheck {
	return predicate.MonitorCheck(func(s *sql.Selector) {
		step := newDNSResultStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.MonitorCheck) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.MonitorCheck) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.MonitorCheck) predicate.MonitorCheck {
	return predicate.MonitorCheck(sql.NotPredicates(p))
}
