<script lang="ts">
	import { alertStore, alertFilter, filteredAlerts } from '$lib/stores/alerts';
	import AlertList from '$lib/components/AlertList.svelte';
</script>

<svelte:head>
	<title>Alerts Feed | Pinger</title>
</svelte:head>

<div class="space-y-8">
	<div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between border-b border-slate-800 pb-6">
		<div>
			<h1 class="text-2xl font-extrabold text-white">Alert Events & Incidents</h1>
			<p class="mt-1 text-xs text-slate-400">Idempotent alert events generated by monitoring checks</p>
		</div>

		<div class="flex items-center rounded-lg border border-slate-800 bg-slate-900 p-1 text-xs font-semibold">
			<button
				onclick={() => alertFilter.set('all')}
				class="rounded-md px-3.5 py-1.5 transition {$alertFilter === 'all' ? 'bg-emerald-500 text-slate-950 font-bold' : 'text-slate-400 hover:text-white'}"
			>
				All Events
			</button>
			<button
				onclick={() => alertFilter.set('triggered')}
				class="rounded-md px-3.5 py-1.5 transition {$alertFilter === 'triggered' ? 'bg-red-500 text-white font-bold' : 'text-slate-400 hover:text-white'}"
			>
				Triggered
			</button>
			<button
				onclick={() => alertFilter.set('resolved')}
				class="rounded-md px-3.5 py-1.5 transition {$alertFilter === 'resolved' ? 'bg-emerald-500 text-slate-950 font-bold' : 'text-slate-400 hover:text-white'}"
			>
				Resolved
			</button>
		</div>
	</div>

	<AlertList alerts={$filteredAlerts} />
</div>
