// Code generated by ent, DO NOT EDIT.

package httpcheckresult

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the httpcheckresult type in the database.
	Label = "http_check_result"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCheckID holds the string denoting the check_id field in the database.
	FieldCheckID = "check_id"
	// FieldStatusCode holds the string denoting the status_code field in the database.
	FieldStatusCode = "status_code"
	// FieldResponseTimeMs holds the string denoting the response_time_ms field in the database.
	FieldResponseTimeMs = "response_time_ms"
	// FieldResponseSizeBytes holds the string denoting the response_size_bytes field in the database.
	FieldResponseSizeBytes = "response_size_bytes"
	// FieldFinalURL holds the string denoting the final_url field in the database.
	FieldFinalURL = "final_url"
	// EdgeCheck holds the string denoting the check edge name in mutations.
	EdgeCheck = "check"
	// Table holds the table name of the httpcheckresult in the database.
	Table = "http_check_results"
	// CheckTable is the table that holds the check relation/edge.
	CheckTable = "http_check_results"
	// CheckInverseTable is the table name for the MonitorCheck entity.
	// It exists in this package in order to avoid circular dependency with the "monitorcheck" package.
	CheckInverseTable = "monitor_checks"
	// CheckColumn is the table column denoting the check relation/edge.
	CheckColumn = "check_id"
)

// Columns holds all SQL columns for httpcheckresult fields.
var Columns = []string{
	FieldID,
	FieldCheckID,
	FieldStatusCode,
	FieldResponseTimeMs,
	FieldResponseSizeBytes,
	FieldFinalURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the HTTPCheckResult queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCheckID orders the results by the check_id field.
func ByCheckID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCheckID, opts...).ToFunc()
}

// ByStatusCode orders the results by the status_code field.
func ByStatusCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusCode, opts...).ToFunc()
}

// ByResponseTimeMs orders the results by the response_time_ms field.
func ByResponseTimeMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseTimeMs, opts...).ToFunc()
}

// ByResponseSizeBytes orders the results by the response_size_bytes field.
func ByResponseSizeBytes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResponseSizeBytes, opts...).ToFunc()
}

// ByFinalURL orders the results by the final_url field.
func ByFinalURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinalURL, opts...).ToFunc()
}

// ByCheckField orders the results by check field.
func ByCheckField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCheckStep(), sql.OrderByField(field, opts...))
	}
}
func newCheckStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CheckInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, CheckTable, CheckColumn),
	)
}
